### ISSUE TITLE
Add option to list files when importing an unrecognized album

### ISSUE THREAD

**Issue by arthurlutz** [sampsyo/beets#1085]
When importing my music collection, sometimes (often?) when beets cannot identify an album, I open up another terminal to look into the folder it is trying to import and then do a website search on musicbrainz to enter the ID of the album in question. It would be nice to have an extra option (among  A,M,S,U,T,G,E,I,B) that would display a list of the files that we are looking at. "L" for example. This could then help the user use the E for search or I if one is using the musicbrainz website.

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you'd like to keep discussing.
