### ISSUE TITLE
HTOA/pregap tracks (AKA track 0)

### ISSUE THREAD

**Issue by pdf** [sampsyo/beets#1104]
MusicBrainz now appears to support HTOA/pregap tracks in the DB, it would be good to be able to support them in beets.  Currently beets wants to either rename or drop these additional tracks.

**Comment by ruippeixotog** [comment]
I stumbled today with this problem when importing [this album](http://musicbrainz.org/release/8eb2b179-643d-3507-b64c-29fcc6745156) (API result [here](http://musicbrainz.org/ws/2/release/8eb2b179-643d-3507-b64c-29fcc6745156?inc=recordings)). Is there any timeline for adding this feature?

I agree with @pdf suggestion about generating two matches as to account for drives that doesn't support ripping HTOA. But meanwhile, I think that the most correct behavior for beets would be to treat pregap tracks as other normal tracks. While users with missing pregap tracks could still import those albums with just a missing track "warning", users with pregap tracks wouldn't have to drop them completely or manually import and tag them.

Personally, I consider pregap tracks important and I would take them as missing if I didn't have them, even if it was for hardware reasons :)

**Comment by sampsyo** [comment]
Just including the tracks does seem fine to me. There's no specific timeline, but contributions would be appreciated!

**Comment by ruippeixotog** [comment]
Ok, no problem, I'll see what I can do :)

**Comment by ruippeixotog** [comment]
Musicbrainzngs doesn't return pregap tracks yet - I just did a [pull request](https://github.com/alastair/python-musicbrainzngs/pull/165) adding support for them. Once that is merged I already have Musicbrainz working with pregap tracks, but I suppose it'll have to wait until a new version of musicbrainzngs is released...

**Comment by sampsyo** [comment]
Awesome! Maybe we should add support to beets now, but let it detect whether the data is present. That way, well be ready when the new version of the library is out (or if people want to run it from git).

**Comment by ruippeixotog** [comment]
Ok, I did pull request #1493 for that then :)
