### ISSUE TITLE
artresizer fails to resize images on windows

### ISSUE THREAD

**Issue by peter-sc** [sampsyo/beets#1142]
Hello, using beets 1.3.9, installed via pip on windows with Python 2.7. Beets can't resize album art, even if imagemagick's convert is in path and is called before the windows convert command. 
The temp file of resized picture is created, but with 0 size.

Config file:
embedart:
    auto: yes
    maxwidth: 1024
    compare_threshold: 0
    ifempty: no

Output:
D:\Music-cleaned\>beet -v embedart U2 the best of
user configuration: C:\Users\user.DOMAIN\AppData\Roaming\beets\config.yaml
data directory: C:\Users\user.DOMAIN\AppData\Roaming\beets
Sending event: pluginload
artresizer: method is (2, (6, 9, 0))
library database: C:\Users\user.DOMAIN\AppData\Roaming\beets\library.db
library directory: D:\Music-cleaned
Sending event: library_opened
Resizing album art to 1024 pixels wide
artresizer: ImageMagick resizing \\?\D:\Music-cleaned\U2\The Best of 1980-1990\folder.jpg to c:\users\user~1.dom\appdata\local\temp\tmpgt5kzs.jpg
artresizer: IM convert failed for \\?\D:\Music-cleaned\U2\The Best of 1980-1990\folder.jpg
Embedding album art into U2 - The Best of 1980ÔÇô1990.
embedart: embedding \\?\D:\Music-cleaned\U2\The Best of 1980-1990\folder.jpg
Sending event: write

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you have any more information that could help us reproduce the problem.
