### ISSUE TITLE
How to properly rescan / reanalyze already imported albums?

### ISSUE THREAD

**Issue by andrewboni** [sampsyo/beets#1168]
I already have many albums imported via `beet import`, but I recently enabled a few more plugins (to fetch things like last.fm tags and echonest info).

What's the correct way to have beets reanalyze my existing library to pull in this new information?

I tried just doing a `beet import ...` on albums already in my library, but this seems like the wrong way to do it:

```bash
❯ beets import ~/Music/Tokyo\ Police\ Club

/Users/me/Music/Tokyo Police Club/A Lesson in Crime (2006) [MP3] (7 items)
Tagging:
    Tokyo Police Club - A Lesson in Crime
URL:
    http://musicbrainz.org/release/5e109707-6013-4874-826f-d2657911fb43
(Similarity: 100.0%) (CD, 2006, CA, Paper Bag Records)
This album is already in the library!
Old: 7 items, MP3, 219kbps, 16:23
New: 7 items, MP3, 219kbps, 16:23
[S]kip new, Keep both, Remove old? s
```

I would like to avoid having to do this for my entire collection. Any ideas? Thanks!

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you want to keep discussing.
