### ISSUE TITLE
_no such field media_ from disambiguation function

### ISSUE THREAD

**Issue by asayler** [sampsyo/beets#1193]
I'm getting an error trying to use the "media" field to disambiguate albums of the same artist/name. This used to work fine prior to upgrading to 1.3.9. For example, trying to use the 'media' field as one of the disambiguation options leads to output like:
```
2011 - Making Mirrors_no such field media_
```

Which should (and used to) create two separate folders:
```
2011 - Making Mirrors [CD]
2011 - Making Mirrors [Digital]
```

Here's path spec (with the non-relevant sections truncated for readability):
```
paths:
    default: $original_year - $album%aunique{albumartist album, albumdisambig media catalognum}/$track - $title
```

So it looks like there may be two issues here:
- The 'media' field does not work as a disambiguation field, leading to "no such field" errors.
- Errors raised during disambiguation get embedded in the file name instead of causing a runtime exception (which is why I didn't catch this sooner).

**Comment by sampsyo** [comment]
Sorry for the abrupt change. We demoted `media` to a track-level field from an album-level field starting in 1.3.9 (I think—see the changelog for the specifics). This was necessary for surprisingly-common situations where releases have multiple media. To work around this, you might consider using the `inline` plugin to define an album-level `media` field, along the same lines as the album-level bitrate field example in the docs.

Surfacing these errors better is also a good idea. I decided a long time ago that not crashing when, e.g., there's a programming error in an `inline` definition, would be friendlier, but I don't think that's true anymore. If you'd like to brainstorm more about cleaning this situation up, could you please open another issue?

**Comment by asayler** [comment]
Thanks for the update. Must have missed that in the change log. Here's the inline code I'm using instead in case others run into the same issue:

```
    media: |
        types = set([])
        for item in items:
            types.add(item.media)
        if (len(types) == 0):
            media = u'NONE'
        elif (len(types) == 1):
            media = types.pop()
        else:
            media = u'MIXED'
        return media
```

I'll consider opening another issue for the error output methodology.
