### ISSUE TITLE
Typo in error when no EDITOR variable is set (or not valid)

### ISSUE THREAD

**Issue by jeroentbt** [sampsyo/beets#1199]
[this part: ](https://github.com/sampsyo/beets/blob/a8921289961e630382187e8769ed7a476f6e02f9/beets/ui/commands.py#L1520#L1520-1521)

     raise ui.UserError("Could not edit configuration. Please"
       "set the EDITOR environment variable.")

prints:

    error: Could not edit configuration. Pleaseset the EDITOR environment variable.

But I don't know whether a space in one of the strings or a comma between them would be the best solution.

**Comment by sampsyo** [comment]
Thank you! Fixed.
