### ISSUE TITLE
emacsclient not recognised as valid EDITOR

### ISSUE THREAD

**Issue by jeroentbt** [sampsyo/beets#1200]
Other apps know how to deal with my EDITOR var.

    $ beet config -e
    error: Could not edit configuration. Pleaseset the EDITOR environment variable.
    $ echo $EDITOR
    emacsclient -c -a ""

Let me know if there is something I can do or try to help you fix this.

**Comment by sampsyo** [comment]
Thanks for pointing this out. FWIW, the trouble was that we weren't parsing arguments in $EDITOR, so we were treating the entire string as one command name. Fixed now.
