### ISSUE TITLE
NumericQuery is useless when there's a typo in the value

### ISSUE THREAD

**Issue by brunal** [sampsyo/beets#1219]
Say I do `beets ls original_year:196*`. There's a mistake: to trigger a regex match I need `::`. This will be a simple `beets.dbcore.query.NumericQuery`. However instead of failing it will match *everything*, equivalent to `beets ls`.

I think that this should raise an error (e.g. `InvalidQuery` that later turns into an `UserError`).

**Comment by sampsyo** [comment]
Seems like a reasonable failure mode for parse errors, yes. We should think very carefully, though, about where these exceptions are bounded—for example, I think that you're right that we need a special InvalidQuery exception raised from the various parsing functions, but I'm not sure where to handle that and transform it into a UserError.

**Comment by brunal** [comment]
I have a patch ready but I didn't submit it yet for that exact reason.
I define and raise `InvalidQuery` in `beets.dbcore.query`. It could then be caught in `beets.library` but that module cannot raise an `ui.UserError`. Otherwise the role is delegated to the module calling e.g `Library.items()`, so `beets.ui.commands` in our case: it will catch `InvalidQuery` and raise a `UserError`.

Downside: every command which can use a query (and therefore most commands...) will have to this. Which isn't nice. Therefore I see the 3 options:
- let the InvalidQuery bubble up to the user and crash beets
- let every command catch & raise
- add another error in `beets.library`, and *there* catch InvalidQuery and raise that error.

**Comment by brunal** [comment]
Third point: we could add a `QueryError` which extends `HumanReadableError` and is raised when an `InvalidQuery` is caught. The `reason` would be the part that's wrong (e.g. "196* is not an int or a float") and `verb` would be the query itself (e.g. "The Beatles original_year:196*") (yeah that's not really a verb but it's akin to an action which is what's "semantically" expected).

The resulting message would be something like (copied from my clipboard) `Error: In query u'Beatles All Together Now original_year:196*': u'196*' is not an int or a float`

**Comment by sampsyo** [comment]
Yeah, this is tricky.

I think the path of least resistance is to just catch InvalidQueryError at the top level—i.e., let it bubble all the way up to main by default. Commands can still catch it themselves if they want to provide special handling.

**Comment by brunal** [comment]
But then in most cases you'd get the stacktrace which IMHO is a bit ugly. Unless it gets caught by `beets.ui.main` (like numerous other exceptions), and a simple "Invalid query: u'196* is not an int or a float" would be printed. Providing more context might be nice (though I'd personally think this is sufficient)

**Comment by sampsyo** [comment]
Yes, we'd add another top-level handler. With a little work the exception could even include more detailed context, such as the full query component.
