### ISSUE TITLE
import -L "<query>" --pretend fails to find items

### ISSUE THREAD

**Issue by groundnuty** [sampsyo/beets#1227]
In order to try beets I decided to use it without touching my files.
I imported my whole collection using:
import -AC 
My config states:
import:
 move: no
 copy: no
 write: no

I later tried to work on subsets of files by using import -L
I used beet ls -f '$artist' to see what artists I have in liblary and then tried to retag files of this artist:

 import -L 'artist:<artist_name>' --pretend

above command returned 0 files. I tried also with regexp (lets say that artist is "Leny")
beet import -L 'artist::Le.*' --pretend
also returned no files.

The corresponding command:
beet list  'artist:Leny'
return expected items.

Am I doing something wrong or is the query option here failing?

**Comment by sampsyo** [comment]
Thanks for reporting. Does this work with a real import (i.e., could this be an issue with `--pretend`)?

    beet import -L artist:Leny

**Comment by groundnuty** [comment]
Actually it turns out it works - just the behaviour is either not expected or not documented. Was missing -s option. 

beet import -s -L artist:Leny --pending

works exactly like
beet list 'artist:Leny'

**Comment by sampsyo** [comment]
Aha, got it. Yes, `import` is in album mode by default but `list` is in track mode by default.
