### ISSUE TITLE
AttributeError: 'MPDStats' object has no attribute 'config'

### ISSUE THREAD

**Issue by pjones** [sampsyo/beets#1228]
From master:

~~~
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.11-py2.7.egg/beetsplug/mpdstats.py", line 147, in __init__
    self.do_rating = self.config['rating'].get(bool)
AttributeError: 'MPDStats' object has no attribute 'config'
~~~

**Comment by sampsyo** [comment]
Hey, @brunal—this looks similar to #1226. It looks like there may be a few stray `self.config`s in both `MPDStats.__init__` and `MPDClientWrapper.__init__`.

**Comment by brunal** [comment]
You're right! I removed them. I also merged `config.add` statements in MPDStatsPlugin: it now always uses `config['mpd']` in accordance with the docs.
