### ISSUE TITLE
DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

### ISSUE THREAD

**Issue by arogl** [sampsyo/beets#1229]
When I have threaded set to yes I get the above warning, with threaded set yo no there is no warning:

python27\lib\site-packages\beetsplug\beatport.py:57: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  .format(e.message))

Looking at line 57 I note that the formatting has {} rather than {0}, I'm not sure that is the source of the error, but a starting point.

**Comment by sampsyo** [comment]
You can disable the Beatport plugin; the company has shut off our access to the API. We should probably remove it altogether.
