### ISSUE TITLE
hang/freeze | Cygwin-Windows

### ISSUE THREAD

**Issue by fohrums** [sampsyo/beets#1230]
<code>Windows 8.1 x64 / Cygwin 1.7.33 x64 / Python 2.7.9
</code>

Cygwin hangs only on some beets commands that involve moving or modifying the file (import, remove) NOT query commands (ls). 

canceling the command CTRL+C initiates the hang/freeze.

FILES:
-
user@ROOM /cygdrive/e/download/albumimport
$ ls
01. Blaq Poet - Gittin.flac
02. Blaq Poet - U Phucc'd Up ft. KL.flac
03. Blaq Poet - Ain't Nuttin Changed.flac
04. Blaq Poet - What's The Deal .flac
05. Blaq Poet - Legendary Pt. 1 feat. Nick Javas and NYGz.flac
06. Blaq Poet - Hood Crazy.flac
07. Blaq Poet - Voices.flac
08. Blaq Poet - Hate ft. N.O.R.E..flac
09. Blaq Poet - Sichuwayshunz.flac
10. Blaq Poet - Stretch Marks And Cigarette Burns ft. Panchi of NYGz and Imani Montana.flac
11. Blaq Poet - S.O.S..flac
12. Blaq Poet - Let The Guns Blow.flac
13. Blaq Poet - Don't Give A Fuccc.flac
14. Blaq Poet - Rap Addiction feat. Shabeend of NYGz and Lil Fame of M.O.P..flac
15. Blaq Poet - Never Goodbye.flac

IMPORT-COMMAND:
-
user@user-ROOM /cygdrive/e/download/albumimport
$ beet -v import ./
user configuration: C:\Users\user\AppData\Roaming\beets\config.yaml
data directory: C:\Users\user\AppData\Roaming\beets
Sending event: pluginload
artresizer: method is (2, (6, 9, 0))
library database: C:\Users\user\AppData\Roaming\beets\library.db
library directory: E:\music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_start
Looking up: E:\download\albumimport
Tagging Blaq Poet - Tha Blaqprint
Searching for discovered album ID: 1897502
Invalid MBID (1897502).
Search terms: Blaq Poet - Tha Blaqprint
Album might be VA: False
Evaluating 8 candidates.
Candidate: Blaq Poet - Tha Blaqprint
Success. Distance: <beets.autotag.hooks.Distance object at 0x02E3AC90>
Candidate: Blaq Poet - Blaq Death
Success. Distance: <beets.autotag.hooks.Distance object at 0x02E56ED0>
Candidate: Blaq Poet - Blaq Poet Society (QB Slasher Remixes)
Success. Distance: <beets.autotag.hooks.Distance object at 0x02F50A10>
Candidate: Blaq Poet - Blaq Poet Society
Success. Distance: <beets.autotag.hooks.Distance object at 0x02EFD9D0>
Candidate: Blaq Poet - Blaq Out
Success. Distance: <beets.autotag.hooks.Distance object at 0x02E56290>
Candidate: Blaq Poet - Tha Blaqprint
Success. Distance: <beets.autotag.hooks.Distance object at 0x02EFD270>
Candidate: Blaq Poet - Tha Blaqprint
Success. Distance: <beets.autotag.hooks.Distance object at 0x02F503B0>
Candidate: Blaq Poet - Tha Blaqprint (Instrumental Album)
Success. Distance: <beets.autotag.hooks.Distance object at 0x02F0F390>

***at this point it freezes/hangs

NOTE
-
works properly in Windows-CMD though, but it's so hard to work with anything outside the *nix commands as they're superior.

funny thing is that it worked before I just don't know what caused this to happen.

**Comment by sampsyo** [comment]
Pretty bizarre. This is going to be very hard to reproduce, since I don't have access to a Cygwin machine. So any digging you can do to get to the bottom of this would be incredibly valuable.

You mentioned you can get hangs on `remove` too. Do you have an example of that?

**Comment by fohrums** [comment]
@sampsyo 

user@user-ROOM /cygdrive/e/download
$ beet ls STiM
STiM - _unofficial - 1
STiM - _unofficial - Out Here

user@user-ROOM /cygdrive/e/download
$ beet -v remove STiM
user configuration: C:\Users\user\AppData\Roaming\beets\config.yaml
data directory: C:\Users\user\AppData\Roaming\beets
Sending event: pluginload
artresizer: method is (2, (6, 9, 0))
library database: C:\Users\user\AppData\Roaming\beets\library.db
library directory: E:\music
Sending event: library_opened

***at this point it freezes/hangs

you'd think 20 min wait would be more than enough time for removing 2-tracks right?

**Comment by sampsyo** [comment]
Yes.

If you have any programming knowledge, is there any chance you can do some more investigation to see exactly where it's hanging? Specifically, it might be useful to put a bunch of `print` calls in around suspicious code to pinpoint the exact problem area. You might look, for example, in `beets.ui.commands` for the remove command code and `beets.util` for the actual file-deletion call.

Does ctrl-C give you a traceback?

**Comment by fohrums** [comment]
<i>Does ctrl-C give you a traceback?</i>

No. That is the beginning of the hang/freeze. Once I cancel the command my cursor no longer blinks and i'm forced to terminate cygwin.

**Comment by sampsyo** [comment]
OK—can you try print-debugging?

**Comment by fohrums** [comment]
@sampsyo i'm afraid I don't know how :(

**Comment by sampsyo** [comment]
Alright. We'll need to leave it here for now then. If anyone with Cygwin can shed more light on the issue, please do pitch in. (But for now, I have no way to investigate this further.)

**Comment by sampsyo** [comment]
This issue is timing out. I'm sorry this issue is so hard to reproduce -- please reopen it if there's any more evidence we can use.
