### ISSUE TITLE
[sqlite3] sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

### ISSUE THREAD

**Issue by k-f-** [sampsyo/beets#1242]
Getting this at seemingly random times as I'm testing out different config options while doing an import.

error.log https://gist.github.com/k-f-/183218bf7fddfa714f8e
config     https://gist.github.com/k-f-/6cb053f622a0bc52f9ce

I have many more error logs and am totally willing to help out however I can.

**Comment by sampsyo** [comment]
This looks like a bug in the `beets-check` plugin. Can you please report it there?

**Comment by k-f-** [comment]
Initially I suspected that to be the case as well but with the beets-check disabled the error still occurs.
I disabled fetchart instead and re-ran... completed with success.

**Comment by sampsyo** [comment]
That's odd. Something must have been keeping the plugin enabled, because the crash definitely shows a call from the `check.py` file that you've dropped into `beetsplug`.
