### ISSUE TITLE
FAIL: test_read_audio_properties (test_mediafile.AlacTest)

### ISSUE THREAD

**Issue by dfc** [sampsyo/beets#1243]
When I try and build/test the latest version of beets on Debian I get the following error when I run the tests:

```
======================================================================
FAIL: test_read_audio_properties (test_mediafile.AlacTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dfc/0xRepos/Sound/beets/test/test_mediafile.py", line 447, in test_read_audio_properties
    self.assertEqual(getattr(mediafile, key), value)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1398 tests in 114.315s

FAILED (failures=1, skipped=10)
(master):dfc@bushido:~/0xRepos/Sound/beets$ 
```

I built beets with `python setup.py build` and then ran `python setup.py test` Beets did not give any warnings or errors during the build process.

**Comment by sampsyo** [comment]
Thank you for reporting. By "latest version", do you mean the version from the Debian repositories, or the latest source from git? If the former, can you try a fresh checkout to check whether this is still going on?

**Comment by dfc** [comment]
Oops sorry about the ambiguity. I was using latest checkout from git. I just did a fresh check out and still get the error. 

```
test_logging_management (test_logging.LoggingTest) ... ok
test_str_format_logging (test_logging.LoggingTest) ... ok

======================================================================
FAIL: test_read_audio_properties (test_mediafile.AlacTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dfc/0xRepos/Sound/beets/test/test_mediafile.py", line 447, in test_read_audio_properties
    self.assertEqual(getattr(mediafile, key), value)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1398 tests in 80.624s

FAILED (failures=1, skipped=10)
(master):dfc@bushido:~/0xRepos/Sound/beets$ git branch -v
* master f346853 embedart: Do not use shell for subprocess
(master):dfc@bushido:~/0xRepos/Sound/beets$

```

If it will be helpful I have the full output of the build/test here: https://gist.githubusercontent.com/dfc/8500ba939355f97ab02c/raw/a2342d6cd0be0c892a8a296e678e56008bba6dac/error

**Comment by sampsyo** [comment]
Okay, thanks! One more detail to ask: which version of the mutagen library do you have installed? (Bonus points: if you upgrade to the latest available from pip, does this change?) I believe this may be related to some recent changes in that library.

**Comment by dfc** [comment]
Upgrading to 1.27 fixed the test problem. I am closing the issue but maybe it is worth mentioning in the changelog that python-mutagen needs to be updated to 1.27?

**Comment by sampsyo** [comment]
Great, thanks for following up. Yes, we should probably bump the required version in setup.py.
