### ISSUE TITLE
embedart: Logging is too verbose in new infrastructure

### ISSUE THREAD

**Issue by sampsyo** [sampsyo/beets#1244]
The recent plugin log refactoring has made the `embedart` plugin too noisy. Since it uses an event handler rather than an import stage, its `self._log.info` calls (e.g., "compare PHASH score…") are printed during the import process. We need a way to quiet this down, either special-purpose for this plugin on its own.

A quick grep reveals that the plugins using `album_imported` and `item_imported` are: `embedart`, `freedesktop`, `importadded`, `importfeeds`, and `permissions`. All of them could use a second look to make sure they don't have the same problem.

I don't have any bright ideas at the moment, but I'll keep thinking. @brunal, any thoughts?

**Comment by sampsyo** [comment]
Other relevant events include the `import_task_*` family. In each case, we should probably audit the plugins for anything that needs to share code with non-import functionality—if it happens a lot, we may want to consider providing the same level-shifting as we do for import stages.

**Comment by brunal** [comment]
I note another bug: multiple instantiation of the same plugin will prefix its log messages with its name multiple times. This is visible when running tests, e.g. `python test/test_embedart.py`.

**Comment by sampsyo** [comment]
Good catch. I guess we should clear out the filters on plugin construction.

**Comment by brunal** [comment]
I guess import_stages should somehow just be an alias for `item_imported` and `album_imported`, around which the log levels should be managed.

Moreover `embedart` logging levels seem widely incorrect, with unexpected errors being logged at level `debug` and "normal" fails (e.g. the image is not similar) being logged as `warn`.

**Comment by sampsyo** [comment]
Yeah, there's definitely some weirdness in how the levels were selected.

I'm not totally sure if I get your proposal for import_stages and the events. The embedart plugin in particular cannot use the ordinary import stage hooks because it needs to run later in the process—after files have been moved/copied. (Other stages run after applying metadata but before manipulating files.)

**Comment by brunal** [comment]
I just pushed a commit fixing the multiple prefixes (bug forgot referencing the issue in the commit message).

**Comment by sampsyo** [comment]
Thanks! For future reference, that was d6a4046245420dc4725a513ebb221de4880bce76.

**Comment by sampsyo** [comment]
Status update: This is the last blocker before we release 1.3.11 in my view. I'll start with an audit of all plugins that might log messages during import outside of a plugin stage (sometime soon).

**Comment by brunal** [comment]
Currently (if I'm not mistaken) the logging policy is the following

what | normal  | verbose
------ |-----------|-----------
core | info | debug
plugin\* directly called | info | debug
plugin called by event | info | debug

\* or core command

The following could be better

what | normal | verbose | very verbose
------|----------|------------|-----------------
core | warning | info | debug
plugin directly called | info | debug | debug
plugin called by event | warning | info | debug

About 1.3.11: don't you think the recent inclusion of `unicode_literals` warrants a bit more testing? Several bugs have been reported consequently to its merge

**Comment by sampsyo** [comment]
I would add one row to the "status quo" table:

what | normal  | verbose
------ |-----------|-----------
core | info | debug
plugin\* directly called | info | debug
plugin called by event | info | debug
plugin called by import stage | warning | debug

I'm concretely proposing just to make row 3 equal to row 4, at least for importer events—or to change those plugins to use import stages instead of events, sidestepping the issue. More user-exposed levels would be fine too, but the regression here just surrounds keeping quiet during import.

And yes, you're absolutely right that more testing is in order for unicode_literals—this is just the only *known* bug blocking release. :smiley:

**Comment by brunal** [comment]
Here it is!
In the end, the verbosity is as follows:

what | normal | verbose | very verbose
------|----------|------------|-----------------
core (`beets` logger) | info | debug | debug
plugin directly called | info | debug | debug
plugin called by event | warning | info | debug
import stage | warning | info | debug

**Comment by sampsyo** [comment]
Great! I think #1320 fixes this. Woohoo! :tada:
