### ISSUE TITLE
[Suggestion] Don't use same letter for options with different use

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1251]
I think is a very bad idea use same letter in different commands with different use.
> Usage: beet embedart [options]
 Options:
 **-f** PATH, --file=PATH  the image file to embed

-----      

> Usage: beet fetchart [options]
 Options:
  **-f**, --force  re-download art when already present

It could cause problems by confusion.

**Comment by sampsyo** [comment]
Thanks for the feedback. This particular ship has sailed, but we'll keep it in mind for the future.
