### ISSUE TITLE
capture_log fails on special characters

### ISSUE THREAD

**Issue by mried** [sampsyo/beets#1253]
Test cases using `capture_log` to - well - capture the log output. If there are special characters like the German umlauts (ä or so), we get the following error:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 65: ordinal not in range(128)
```

Reproducing this is simple: add `album = self.add_album_fixture()` after line 1564 and `,album.path` after line 1568 in `test_importer` and run the importer tests.

Is this a bug within the log capturing or did I used it the wrong way?

**Comment by sampsyo** [comment]
Yep, sounds like a legitimate issue. Would you mind investigating to see whether it's as simple as expecting `str` where we should use `unicode` somewhere in the `capture_log` implementation?
