### ISSUE TITLE
Support albums of a single track with a .cue file

### ISSUE THREAD

**Issue by brunal** [sampsyo/beets#1257]
I have several albums (especially in flac) that are a single long fine with a .cue file that says when a track starts and when a track ends. It'd be neat it beets knew how to look for it and split the big song file.

I've tried extending the autotagger for that goal but without success: `candidates` and `item_candidates` don't work at that level — and the default candidate (from `beets.autotag.mb.match_album`) is actually the right one. But in the propositions, it has a low match rate for there are missing tracks, the track length is not the right one, etc.
Should splitting automatically happen earlier? But then what if the user wants to skip that folder, since we shouldn't have touched it? Maybe the plugin should look for folders with a .cue file at `import_started` time, split in a temp folder and replace the task with that temp folder? Then we have to hook again when we take a decision...

So overall I'm mostly looking for tips & pointers on how to write a plugin that realize well the aforementioned task :-)

**Comment by sampsyo** [comment]
Hello! We have an old issue for this: #136. I'll put a few thoughts there.
