### ISSUE TITLE
Improve extractart to extract cover art of all albums for a query

### ISSUE THREAD

**Issue by mried** [sampsyo/beets#1261]
The current `extractart` command of the `embedart` plugin is only able to extract the cover art of a single file. If the query the user specifies results in more than one item, only the art of the first one is extracted.

I would like to improve the command such the user queries for albums (like `ls -a` command) and one cover art is extracted per album and placed inside the album folder. The command should try all files of an album until an art is found. The command could be executed like `beet extractart -a <query>`.

**Comment by brunal** [comment]
Since I was working on embedart, here is a solution. I probably should add a test for it though...

**Comment by mried** [comment]
I don't think the change you made does what I wanted to do: It wont extract the art of all albums specified by a query. It'll still only extract one art file.

**Comment by brunal** [comment]
Right... I read the issue too fast, sorry
