### ISSUE TITLE
Bad genres field can break the writing of genre/genres tags

### ISSUE THREAD

**Issue by randybias** [sampsyo/beets#1279]
Steps to reproduce:

[recommend starting with an empty database and single file to import; you will need the 'info' plugin]

1. beet import
2. beet modify genres=Electronica
3. beet info | grep genre
  * You will see something like:

>              genre: E
>              genres: E; l; e; c; t; r; o; n; i; c; a

4. beet modify genre="Foo"
5. beet info | grep genre

At this point modifying either genre or genres will not work for these files.  The SQLite database will have the correct information, but "beet write" will always fail to write out the tag.

**Comment by sampsyo** [comment]
The plural `genres` is experimental; we should probably remove it, actually. Does everything work if you use the singular `genre`?

**Comment by randybias** [comment]
Yes.  It only breaks when genres get modified in that specific manner, which then somehow seems to break genre itself.

**Comment by sampsyo** [comment]
Could we possibly just avoid using the `genres` field? That represents the progress we're making on #119 but isn't quite ready for use.

**Comment by randybias** [comment]
I don't have any use for it but maybe someone else does?

**Comment by sampsyo** [comment]
Let's leave this where it is for now—the feature can be considered "in progress".
