### ISSUE TITLE
Utilise transl(iter)ation relationships for using in alternative tracklists

### ISSUE THREAD

**Issue by Freso** [sampsyo/beets#1280]
Currently it is possible to get beets to normalise artist names to a given language based on that artist's aliases. MusicBrainz also contains information for transl(iter)ation of release track lists, it would be great if beets could support this. Possibly as a plugin, as most people would probably not care, and it would require doing some more look-ups that will slow importing and mbsync'ing.

See:
http://tickets.musicbrainz.org/browse/PICARD-145
http://tickets.musicbrainz.org/browse/STYLE-342
https://musicbrainz.org/doc/Style/Specific_types_of_releases/Pseudo-Releases
https://musicbrainz.org/relationship/fc399d47-23a7-4c28-bfcf-0607a562b644

**Comment by sampsyo** [comment]
Yes, sounds useful. We have an earlier issue about pseudo-releases in #654; perhaps we should merge on that one?

**Comment by Freso** [comment]
Ah, you're right. I don't know why I didn't see that. Ah well. :)
