### ISSUE TITLE
fingerprinting ... failed: audio could not be decoded

### ISSUE THREAD

**Issue by rigelhope** [sampsyo/beets#1282]
i kept getting this error on Mint 17 (an ubuntu derivative) for every file i wanted to fingerprint using pyacoustid. i had a hunch it was because of the avconv/ffmpeg fork issue. i had all the dependencies installed and kept scratching my head.

'sudo ln -s /usr/bin/avconv /usr/bin/ffmpeg' to create a symbolic link to the avconv binary with the name "ffmpeg" did the trick so far. (i hope it's a truly drop-in replacement)

in the meantime, beets might want to check for which one is installed or something. i do a bit of python and might be willing to cobble together a pull request but right now i'm tired.

**Comment by sampsyo** [comment]
Good call. The ffmpeg/avconv distinction should be fixed in audioread—in fact, there's an issue about it here: https://github.com/sampsyo/audioread/issues/17

Help would be greatly appreciated if you have time!
