### ISSUE TITLE
aunique{} not working

### ISSUE THREAD

**Issue by tarrasque73** [sampsyo/beets#1284]
i set my path as follows in conf:

```
paths:
    default: $albumartist/$original_year - $album%aunique{}/%if{$multidisc,$disc - ,}$track $title
```

multidisc is an inline custom field

```
item_fields:
    multidisc: 1 if disctotal > 1 else 0
```

Everything worked as intended for some time, with %aunique{} outputting discriminators as intended

Then with no reason %aunique{} seems always to output an empty string, which makes sometimes albums to be "merged" together, with duplicate tracks having ".1" appended to the file name.

**Comment by sampsyo** [comment]
Hi there—which version (or git revision) of beets are you running?

Also, is there any chance you can share your full configuration (with sensitive date removed, of course)?

**Comment by brunal** [comment]
@tarrasque73 Could you provide an update on the problem? Or can we close the issue?

**Comment by tarrasque73** [comment]
Here I am. Escuse me, I haven't been using beets for a while and I forgot.

Anyway I just tried today with a couple of albums (regular version and 2CD version of the same LP, both present on MusicBrainz DB) and the problem happened again.

The tracks were all added to the same folder, with different names depending on the name rules depending on per_disc_numbering I put in my config files.

Beet version is 1.3.10, on MS Windows 7 64 bit, with Python 2.7.8

Here's my full config:

directory: "E:/Beets/Music"
library: "E:/Beets/Library/musiclibrary.blb"
plugins: inline embedart lyrics missing duplicates fetchart mbsync
item_fields:
    multidisc: 1 if disctotal > 1 else 0
    albumsoundtracks: 1 if comments == "soundtrack" else 0
per_disc_numbering: yes
original_date: yes
fetchart:
    auto: no
embedart:
    auto: no
    ifempty: yes
list_format_item:
    $albumartist - $year $album - $track $title
list_format_album:
    $albumartist - $year $album %aunique{}
paths:
    albumsoundtracks:1: Soundtracks/$original_year - $album%aunique{}/%if{$multidisc,$disc - ,}$track $title
    comp: Various Artists/$original_year - $album%aunique{}/%if{$multidisc,$disc - ,}$track $title
    singleton: Non-Album Tracks/$artist/$title
    default: $albumartist/$original_year - $album%aunique{}/%if{$multidisc,$disc - ,}$track $title

**Comment by sampsyo** [comment]
Can you please give an example? Which albums did you import, and what does `beet ls` and `beet ls -a` show for the two albums that seem to conflict?

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you have more background on the problem.
