### ISSUE TITLE
One-sided range queries are broken

### ISSUE THREAD

**Issue by randybias** [sampsyo/beets#1288]
Configuration:

> smartplaylist:
>   playlist_dir: /Volumes/djmusic/crates
>   playlists:
>     - name: traktor_collection.m3u
>       query: 'traktor:yes'
>     - name: genre-house.m3u
>       query: 'genre:house'
>     - name: genre-disco.m3u
>       query: 'genre:disco'
>     - name: genre-funk.m3u
>       query: 'genre:funk'
>     - name: bpm-hiphopreggae.m3u
>       query: 'bpm:75..104'
>     - name: bpm-funkybreaks.m3u
>       query: 'bpm:103..'

Command line output:

> $ beet -v splupdate
> user configuration: /Users/djrandyb/.config/beets/config.yaml
> data directory: /Users/djrandyb/.config/beets
> Sending event: pluginload
> library database: /Volumes/djmusic/beets/data/musiclibrary.blb
> library directory: /Volumes/djmusic/beets/music
> Sending event: library_opened
> smartplaylist: Updating smart playlists...
> smartplaylist: Creating playlist traktor_collection.m3u
> smartplaylist: Creating playlist genre-house.m3u
> smartplaylist: Creating playlist genre-disco.m3u
> smartplaylist: Creating playlist genre-funk.m3u
> smartplaylist: Creating playlist bpm-hiphopreggae.m3u
> smartplaylist: Creating playlist bpm-funkybreaks.m3u
> invalid query: u'' is not an int or a float

And the smart playlist is NOT updated.  It bails out at this point (there are more playlists after funkybreaks).

**Comment by sampsyo** [comment]
Thanks for reporting. This is not just about `smartplaylist`; one-sided range queries were broken by #1221:

    $ beet ls bpm:10..
    invalid query: u'' is not an int or a float

@brunal, it looks like the changes to `NumericQuery._convert` were a little too aggressive. I believe that function needs to return `None` if the value is the empty string.

Two other observations from looking into this:
* I also notice that the docstring also needs updating.
* It would be awesome if the error didn't have the Python `u` artifact, which users likely don't care about.

**Comment by sampsyo** [comment]
Thank you, @brunal!
