### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by randybias** [sampsyo/beets#1289]
This is low priority I guess, but I would very much like to see offline documentation. If you are on a plane or remote, but want to work on your library, it would be nice to be able to see the docs. Yes, if you've got the git repo checked out you can read them, but I think since we have a webserver and the docs are part of the repo already something like:

> $ beet docserver
> Starting documentation server at http://127.0.0.1:3845/beets

Should startup a simple web interface to the docs.

**Comment by sampsyo** [comment]
Hmm… I'm not sure about a built-in web server, but we could consider generating more man pages. Did you know you can already [download offline documentation](https://readthedocs.org/projects/beets/downloads/) in many formats, including epub and a zip file of HTML files?

**Comment by randybias** [comment]
there already is a web server, though, right?  can't you just point it at the docs?

I did not know about the offline docs.  I'll check that out.  It's good enough for me at the moment if you want to close this.

**Comment by sampsyo** [comment]
Okay, I think I will for now.

That would be a little more complicated than just pointing `beet web` at the docs—we'd need Sphinx as a run-time dependency or a clever way to package up all the HTML during the build process.
