### ISSUE TITLE
Print old/new album size when prompting to replace

### ISSUE THREAD

**Issue by dfc** [sampsyo/beets#1291]
Currently when beets is asked to import an album that is already in the library it prints the # of tracks, bitrate, etc of the old and the new album:

    Old: 13 items, MP3, 256kbps, 44:32
    New: 13 items, MP3, 320kbps, 44:31

It would be nice if beets could also print the total file size along with this information e.g:

    Old: 13 items, MP3, 256kbps, 44:32, 101MB
    New: 13 items, MP3, 320kbps, 44:31, 128MB

**Comment by sampsyo** [comment]
OK!
