### ISSUE TITLE
incremental import confused by conversion process

### ISSUE THREAD

**Issue by randybias** [sampsyo/beets#1296]
If I am doing an incremental import from dir A to dir B, then on the second pass on dir A, it will be confused by the "difference" in the file formats if on the first pass I used "convert".  For example:

```bash
/Users/djrandyb/djmusic/ForImport/FLAC/Dadamnphreaknoizphunk/Electric Crate Digger (9 items)
Tagging:
    Dadamnphreaknoizphunk - Electric Crate Digger
URL:
    http://musicbrainz.org/release/15133303-fbdb-4ae3-a43a-ca02886f4502
(Similarity: 100.0%) (CD, 1999, DE, !K7)
This album is already in the library!
Old: 9 items, ALAC, 1411kbps, 57:02
New: 9 items, FLAC, 919kbps, 57:02
[S]kip new, Keep both, Remove old? S
```

This should probably silently skip and it should handle that the "new" and the "old" are basically the same, but in different music formats.

What I want is that dir A (ForImport) can grow over time as my system of truth / system of record, and the beets directory has the converted, sorted, tagged and bagged, tracks.

**Comment by sampsyo** [comment]
Hmm… I'm not sure whether this is related to conversion. Incremental import should skip all album directories that have been imported before, *regardless of the contents of the library*. Can you check whether you can reproduce this even without conversion?

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you want to investigate the problem more.
