### ISSUE TITLE
Automatic path query detection doesn't work for album queries

### ISSUE THREAD

**Issue by tlc** [sampsyo/beets#1302]
1.3.10
'beet mbsync -WM /some/path' 
doesn't work

'beet mbsync -WM path:/some/path' 
does

**Comment by sampsyo** [comment]
The `mbsync` command uses album queries. Path queries only work on items for now.

**Comment by tlc** [comment]
Weren't both of my examples path queries?

**Comment by sampsyo** [comment]
Oops! Sorry for the lapse. :flushed: It looks like the problem is that we're not automatically detecting path queries in album queries at all. That is, you can see the same issue in:

    beet ls -a /some/path

vs.:

    beet ls -a path:/some/path

or:

    beet ls /some/path

**Comment by tomjaspers** [comment]
For anyone interested: see `parse_query_parts` in library.py, where automatic path detection only occurs if the model_cls (i.e., Item or Album) has 'path' as a *real* field (i.e., defined in `_fields`).

**Comment by sampsyo** [comment]
Looks like a good solution; thanks, @tomjaspers!
