### ISSUE TITLE
Add tags during import?

### ISSUE THREAD

**Issue by willgrnr** [sampsyo/beets#1304]
This would be a feature request unless something is hiding in plain sight. Apologies if this is not the right place to do it.

Normally if there is no MusicBrainz or Discogs listing for the song/album, I would `[U]se as is` and then `beet modify` after the import. If I'm doing a bulk import of single tracks, I think it would be easier to just have an option like `[N]ew tags` and then be prompted with just some basic metadata for the song:

```
Title:
Artist:
Album:
Length: (detect length?)
```

Looking at the wiki, it seems doable by plugin. Never dabbled in python however I think I'll give it a shot.

**Comment by sampsyo** [comment]
Please see #396.
