### ISSUE TITLE
Hanging after entering release ID, cannot Ctrl+C

### ISSUE THREAD

**Issue by willgrnr** [sampsyo/beets#1306]
In case you aren't fed up with me yet: beets is hanging after I entered a release ID to be searched. I'm assuming it has something to do with #1305 however I can't Ctrl+C out.

**Comment by sampsyo** [comment]
Since I can't reproduce this, can you please do some more investigation? The verbose log (and your system setup details) is critical, and anything else you can do to shed light would be helpful.

**Comment by willgrnr** [comment]
I haven't been able to replicate the problem, it may have been because of a laggy internet connection at the time, who knows. Is there not a general way to add Ctrl-C as a way to exit the operation/program?

**Comment by sampsyo** [comment]
There's some more info about ^C on the FAQ. http://docs.beets.io/en/v1.3.10/faq.html#ignore-control-c-during-an-import
