### ISSUE TITLE
Album queries using `path:` prefix don't work with non-normalized path

### ISSUE THREAD

**Issue by tomjaspers** [sampsyo/beets#1307]
Noticed this while working on #1302 
```
$ ./beet ls -a path:/Users/tjs/Music/Music/
# works

$ ./beet ls -a ~/Music/Music/
# works

$ ./beet ls path:~/Music/Music/
# works

$ ./beet ls -a path:~/Music/Music/
# does not work
```

Seeing as `Album` does not have the `path` field, the queryparse's `construct_query_part` will assign it as a `SubstringQuery`, which does not normalize the path as `PathQuery` does.

Not sure what the cleanest solution would be; maybe adding a check in `SubstringQuery` constructor?

**Comment by sampsyo** [comment]
Good point. We should add `path` to the `_types` member of `Album`, which should automatically make queries work correctly.

This seems like a good time to add some tests first, though, to make sure we've covered all the cases!
