### ISSUE TITLE
lowercase tags

### ISSUE THREAD

**Issue by fabsmusicjunkie** [sampsyo/beets#1310]
is there a possibility to produce only lowercase tags?

**Comment by sampsyo** [comment]
You can produce lower-case filenames with `%lower{}`, but I can't think of an easy way to automatically lower-case the tags themselves at the moment. Is that what you meant? This could be covered by #488.

**Comment by fabsmusicjunkie** [comment]
Yes, i was thinking about lower-case the tabs themselves.

**Comment by sampsyo** [comment]
OK! I'm going to leave some notes on #488. Can you follow up there if you have any feedback about how this should work?
