### ISSUE TITLE
Configure default metadata in case of 'Unknown' value

### ISSUE THREAD

**Issue by Bercio** [sampsyo/beets#1313]
I was wondering if it's possible to configure the field 'Composer' (which is often Unknown) to be equal to album artist if it otherwise would be Unknown. I know you can create new fields with the item_fields extension but I would like to configure an existing one, is it possible? I ask 'cause I find it mildly annoying to have a column full  of 'unkown' in my music player but I don't want to hide that field 'cause it often has useful information for classical music albums.

**Comment by sampsyo** [comment]
Can you perhaps leave a note in #488, which would let you do something like `beet modify composer::^$ composer=$albumartist`?

**Comment by Bercio** [comment]
sure, although I don't understand the syntax you are proposing.
