### ISSUE TITLE
Track with multiple artists is reported as missing

### ISSUE THREAD

**Issue by nguillaumin** [sampsyo/beets#1315]
Hi,

First of all, thanks for this wonderful program! Absolutely essential!

I'm having a problem with beets reporting a missing track. I'm trying to import [this album](https://musicbrainz.org/release/ffb9ce40-4b08-4652-a0ac-13238c752fca) and track 3 is reported as missing.

I have all the files, MP3 properly tagged, in a single folder. When I run `beet import`, I get the following output:

```
/media/nas/music/Divers/La Musique de Paris Dernière Vol. 3 (15 items)
Tagging:
    Various Artists - La Musique de Paris Dernière 3
URL:
    http://musicbrainz.org/release/ffb9ce40-4b08-4652-a0ac-13238c752fca
(Similarity: 97.9%) (missing tracks) (CD, 2002, FR, naïve)
Missing tracks:
 ! Baby One More Time (#3) (3:55)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 
```

File list is:

```
01 - Joey Ramone - What A Wonderful World.mp3        10 - My Ruin - Tainted Love.mp3
02 - Muse - Can't Take My Eyes Off Of You.mp3        11 - Treponem Pal - Funky Town.mp3
03 - Ahmet & Dweezil Zappa - Baby One More Time.mp3  12 - Atrocity - Let's Dance.mp3
04 - Devo - I Can't Get No (Satisfaction).mp3        13 - IML - Da Ya Think I'm Sexy.mp3
05 - Alabama 3 - Hotel California.mp3                14 - Sid Vicious - My Way.mp3
06 - The Bates - Billie Jean.mp3                     15 - Wizo - Poupée De Cire.mp3
07 - Lino - Boys.mp3                                 16 - The Langley Schools Music Project - Space Oddity.mp3
08 - Ripley - Light My Fire.mp3                      La Musique de Paris Dernière Vol. 3.jpg
09 - Lords Of Acid - Lady Marmelade.mp3
```

And tags on track 3 (Using `mp3info2`):

```
File: /media/nas/music/Divers/La Musique de Paris Dernière Vol. 3/03 - Ahmet & Dweezil Zappa - Baby One More Time.mp3
Title:   Baby One More Time                                 Track: 03/16
Performer: Ahmet & Dweezil Zappa
Orchestra (etc): Various Artists
Album:   La Musique de Paris Dernie 3                 Year:  2002  Disk: 1/1
Comment:                                                    Genre: Soundtrack
```

Am I missing something? Would that be related to the fact that 2 artists are credited on this track? Is there a workaround?

Cheers,

Nico

**Comment by sampsyo** [comment]
That is indeed very strange. I note that the auto-tagger says "15 items," as if it can't even read one of the files.

Can you try enabling the `info` plugin and running:

    beet -v info "/media/nas/music/Divers/La Musique de Paris Dernière Vol. 3/03 - Ahmet & Dweezil Zappa - Baby One More Time.mp3"

to check whether beets is having trouble reading the file?

Also, can you include your configuration in case there's something up there?

**Comment by nguillaumin** [comment]
Ah, found it. I had actually an ignore pattern that matched the artist in my config: 

```
$ beet config
ignore:
- '*Zappa*'
...
```

Sorry to have waisted your time...

**Comment by nguillaumin** [comment]
Having thought about it, a possible improvement would be to indicate that the track was not matched because a of configured ignore pattern. Something like:

```
Missing tracks:
 ! Baby One More Time (#3) (3:55)         (Ignored because of ignore pattern "*Zappa*")
```
