### ISSUE TITLE
[question] 'beet upd' updates date?

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1319]
When execute `beets upd` sometimes shows messages like this:
```
Soraya Arnelas - Corazón de fuego - Tu piel
  month: 12 -> 00
  day: 05 -> 00
  original_day: 05 -> 00
```

What's the meaning of this?

**Comment by sampsyo** [comment]
As with other update actions, this just means that the tags on disk are different from the database metadata.
