### ISSUE TITLE
command (upd) | automatically removing 'month, day, & original_day'

### ISSUE THREAD

**Issue by fohrums** [sampsyo/beets#1334]
After importing an album that was successfully matched with the musicbrainz database I arbitrarily decided to run a

<code>$ beet upd</code>

e:\download>beet upd
Dominick Martin - Shine a Light - The Truth
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Change
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - The Marches
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Last Kiss
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Footprints
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Beyond
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Something I Said
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - The Tide
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Man on the Road
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00
Dominick Martin - Shine a Light - Devise
  month: 11 -> 00
  day: 23 -> 00
  original_day: 23 -> 00

So, for some reason I'm seeing that <b>month, day, & original_day</b> are replaced for 'none'.

As far as i'm aware, there aren't any dedicated tag-fields for these values so why/how are they even here?

NOTE
=
Beets Documentation > Path Formats > Available Values
https://beets.readthedocs.org/en/v1.3.10/reference/pathformat.html?highlight=month%20day%20original_day#available-values

**Comment by sampsyo** [comment]
Can you please provide a way to reproduce this (soup to nuts)? Also, which version are you on? Can you try doing this on the latest git version to see if the problem still exists?

All tag formats store those values, most by packing the year, month, and day into a single string.

**Comment by jrobeson** [comment]
i'm seeing the same thing when using beet write -p, it shows those same values, but never writes them. I'll test it on git HEAD later on today.

**Comment by jrobeson** [comment]
obviously write is the exact opposite, where it's trying to add month, day, and original_day, but never writes them. I'm still seeing this behaviour on current HEAD.

**Comment by sampsyo** [comment]
@jrobeson This is because most tag format's can't store month and day if there's no year. So beets tries to write the values but nothing actually changes.

**Comment by Slewan** [comment]
Same:

Atreyu - A Death-Grip on Yesterday - Our Sick Story (Thus Far)
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - The Theft
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - We Stand Up
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - Ex's and Oh's
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - Your Private War
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - My Fork in the Road (Your Knife in My Back)
  original_day: 28 -> 00
Atreyu - A Death-Grip on Yesterday - Untitled Finale
  original_day: 28 -> 00
Atreyu - AMP Magazine Presents, Volume 1: Hardcore - Ain't Love Grand
  original_day: 04 -> 00
Atreyu - MTV 2 Headbangers Ball, Volume 2 (disc 1) - Right Side of the Bed
  original_day: 24 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - A Song for the Optimists
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Dilated
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Ain't Love Grand
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Living Each Day Like You're Already Dead
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Deanne the Arsonist
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Someone's Standing on My Chest
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - At Least I Know I'm a Sinner
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Tulips Are Better
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - A Vampire's Lament
  original_day: 04 -> 00
Atreyu - Suicide Notes and Butterfly Kisses - Lip Gloss and Black
  original_day: 04 -> 00
Atreyu - The Best of Atreyu - Lip Gloss and Black
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Ain't Love Grand
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Living Each Day Like You're Already Dead
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - A Song for the Optimists
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Deanne the Arsonist
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Tulips Are Better
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Someone's Standing on My Chest
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Bleeding Mascara
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - Right Side of the Bed
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - You Eclipsed by Me
  original_day: 23 -> 00
Atreyu - The Best of Atreyu - The Crimson

etc.

**Comment by DjSlash** [comment]
I'm also having similar behaviour. I regularly do a `beet mbsync` and have `import.write: yes` in my current config. But still when I do `beet write` it does loads of tag-writing with dates, which seems not to be saved in the file.

Output from `beet write`:
> 2 Unlimited - The Complete History - Desire (album version)
>  month: 00 -> 01
>  day: 00 -> 19
>  original_day: 00 -> 19

Checking with beet info:

`beet info 2\ Unlimited/2004\ -\ The\ Complete\ History\ \[compilation\]/11\ -\ 2\ Unlimited\ -\ Desire\ \(album\ version\).mp3 | egrep 'day|month|year|date'`

>  date: 2004-01-01
>  original_date: 2004-01-01
>  original_month: 1
>  original_year: 2004
>  year: 2004

**Comment by adkow** [comment]
It was fixed few commits ago. See #1303 and #1589.

**Comment by DjSlash** [comment]
Ah, nice. :+1: Guess we need to wait for 1.3.15. \*hint\* \*hint\* ;-)

**Comment by sampsyo** [comment]
Cool. Yes, new version out very soon!
