### ISSUE TITLE
proposal: confidence measures

### ISSUE THREAD

**Issue by rigelhope** [sampsyo/beets#1335]
hi,

so as someone with a very big collection of albums, some of which are in storage and not immediately accessible, i've noticed in going through my audio files and audio tagging that i have had a number of different procedures for ripping and metadata. sometimes i included full artwork scans. sometimes i just left the metadata out entirely, and everything in between.

i would like, perhaps as an add-on, to be asked how confident i am about my metadata choice, so that in addition to having a nicely tagged collection, i can generate a list of priorities to verify metadata for when i access my physical collection. MusicBrainz is great, but when there are 12 different masterings of an album and i'm not entirely certain which version i ripped it from, i'd like some pointer to mark that as potentially questionable.

i dont know how i would go about this. it appears to my n00bily self that the plugin architecture is intended to perform additional procedures on a file or set of files, rather than get all up in the UI, but i could be wrong about that.

**Comment by sampsyo** [comment]
Have you considered just using a flexible attribute in beets? Something like: `beet mod -a some album confidence=0.75`. You can even make the attribute numerically query-able with the types plugin. An idea like #396 could then let you provide this score at import time if you want.

**Comment by rigelhope** [comment]
yes, #396 seems similar/generalizable enough to my use case

**Comment by sampsyo** [comment]
Cool! Would you mind leaving a note on that ticket about the usefulness of adding flexattrs like `confidence`? I'll then close this issue.
