### ISSUE TITLE
importing issue

### ISSUE THREAD

**Issue by agentandroid** [sampsyo/beets#1338]
http://pastebin.com/VR2yLGAS

**Comment by sampsyo** [comment]
What version of beets are you using? Can you paste your configuration? Any third-party plugins?

**Comment by agentandroid** [comment]
using the latest beets, sudo pip2 install -U https://github.com/sampsyo/beets/tarball/master

config : http://pastebin.com/7rZTi3gW

besides the plugins in the config, no other plugins

**Comment by brunal** [comment]
One more issue of a listener that's not expecting all parameters sent. Patch incoming.
