### ISSUE TITLE
Can't recognise deluxe edition (two disks)

### ISSUE THREAD

**Issue by kooimens** [sampsyo/beets#1339]
This release:
http://musicbrainz.org/release-group/ce4f07c7-2367-4374-9417-e2febd1ed129 have two versions. I tried to import the deluxe edition, where each disk have it's own sub-folder named like this:
`(CD1)The Truth & Soul Sessions`
`CD2`

Beet tags disk one as the original album (not the deluxe version) and then (of course) can't recognise the second disk.

**Comment by sampsyo** [comment]
The FAQ has ideas on how to force beets to import multiple folders as one album. http://docs.beets.io/en/v1.3.10/faq.html#import-a-multi-disc-album

**Comment by kooimens** [comment]
I think I didn't make myself clear. I know how beets handles multiple disks, but my point here is that recognising a multi disk album should be more flexible/extended.

In the example that I provided it's pretty clear that it's a two-disk release. In my opinion beets should recognise the `CD1` and `CD2` here.

**Comment by sampsyo** [comment]
Aha, thanks for clarifying. I'm somewhat less certain that we should be supporting this pattern—the requirement all subdirectories currently start with the same prefix (i.e., "Something Something CD1" and "Something Something CD2") helps avoid false positives. If you think this is worth supporting, though, can you come up with a set of unambiguous and easy-to-implement rules and argue that they won't cause problems by "accidental" matching?
