### ISSUE TITLE
Replaygain backend for audiotools faulty

### ISSUE THREAD

**Issue by oscarcarlsson** [sampsyo/beets#1342]
When I try to use the audiotools backend for beets this is what I'm greeted by, everytime I try to execute any command in beets:

    user configuration: /home/foo/.config/beets/config.yaml
    data directory: /home/foo/.config/beets
    Sending event: pluginload
    Traceback (most recent call last):
      File "/home/foo/env/python-beets/bin/beet", line 9, in <module>
	load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
      File "/home/foo/git/beets/beets/ui/__init__.py", line 953, in main
	_raw_main(args)
      File "/home/foo/git/beets/beets/ui/__init__.py", line 939, in _raw_main
	subcommands, plugins, lib = _setup(options, lib)
      File "/home/foo/git/beets/beets/ui/__init__.py", line 831, in _setup
	plugins = _load_plugins(config)
      File "/home/foo/git/beets/beets/ui/__init__.py", line 817, in _load_plugins
	plugins.send("pluginload")
      File "/home/foo/git/beets/beets/plugins.py", line 445, in send
	for handler in event_handlers()[event]:
      File "/home/foo/git/beets/beets/plugins.py", line 428, in event_handlers
	for plugin in find_plugins():
      File "/home/foo/git/beets/beets/plugins.py", line 276, in find_plugins
	_instances[cls] = cls()
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 632, in __init__
	self.config, self._log
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 474, in __init__
	super(CommandBackend, self).__init__(config, log)
    TypeError: super(type, obj): obj must be an instance or subtype of type

As soon as I uncomment the replaygain options (below) I can start beets without issue.

    # Relevant part concerning replaygain
    replaygain:
      backend: audiotools

I've checked out the latest code from git, both for beets and audiotools and installed in a new virtual environment just to be sure. 

    # Version numbers
    beets version 1.3.11 (from git)
    plugins: replaygain, embedart, convert

    Python Audio Tools 3.1alpha1 (from git)

**Comment by sampsyo** [comment]
Thanks! That should fix it. Can you check if this works now?

**Comment by oscarcarlsson** [comment]
Yes, but it throws this new fancy error :)

    (python-beets)foo@heisler ~> beet -v replaygain format:alac Haken
    user configuration: /home/foo/.config/beets/config.yaml
    data directory: /home/foo/.config/beets
    Sending event: pluginload
    library database: /home/foo/.config/beets/library.db
    library directory: /home/foo/Music
    Sending event: library_opened
    replaygain: analyzing Haken - Aquarius - The Point of No Return
    Traceback (most recent call last):
      File "/home/foo/env/python-beets/bin/beet", line 9, in <module>
	load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
      File "/home/foo/git/beets/beets/ui/__init__.py", line 953, in main
	_raw_main(args)
      File "/home/foo/git/beets/beets/ui/__init__.py", line 943, in _raw_main
	subcommand.func(lib, suboptions, subargs)
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 760, in func
	self.handle_track(item, write)
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 717, in handle_track
	track_gains = self.backend_instance.compute_track_gain([item])
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 539, in compute_track_gain
	return [self._compute_track_gain(item) for item in items]
      File "/home/foo/git/beets/beetsplug/replaygain.py", line 552, in _compute_track_gain
	rg_track_gain, rg_track_peak = rg.title_gain(audiofile.to_pcm())
    TypeError: title_gain() takes no arguments (1 given)

Trying it on other formats:

    (python-beets)foo@heisler ~> beet -v replaygain format:aac Frank
    user configuration: /home/foo/.config/beets/config.yaml
    data directory: /home/foo/.config/beets
    Sending event: pluginload
    library database: /home/foo/.config/beets/library.db
    library directory: /home/foo/Music
    Sending event: library_opened
    replaygain: Skipping track Frank Zappa - Strictly Commercial: The Best of Frank Zappa - Peaches en Regalia

The error on AAC files is most likely related to my audiotools installation, but I think that the first error is beets related.

**Comment by brunal** [comment]
> TypeError: title_gain() takes no arguments (1 given)

Well... That's a lie! `audiotools.replaygain.ReplayGain.title_gain()` does take an argument, as can be seen in `src/replaygain.c:186`. I tried to reproduce your error here and couldn't, how did you install audiotools? Was it working before?

**Comment by aszlig** [comment]
@brunal: It's **not** a lie with version 3.0 of audiotools, see here: https://github.com/tuffy/python-audio-tools/blob/v3.0/src/replaygain.c#L351

**Comment by sampsyo** [comment]
Oh no, DLL hell: what a drag.

Could one of you with the affected version of audiotools (@aszlig or @oscarcarlsson) try concocting a patch that inspects what the function expects and provides it?

Other alternatives:
* Check the package version and exit with an error if it's too old.
* Remove the audiotools backend; it seems like our other options are mostly easier to install these days anyway.

**Comment by aszlig** [comment]
I don't have time for this at the moment, but for everyone else: If you have [Nix](https://nixos.org/nix) installed, it's a one-liner to reproduce (without polluting your system with crap you don't want):

```shell
nix-build -E 'with import <nixpkgs> {}; beets.override (drv: { pythonPackages = drv.pythonPackages // { audiotools = drv.pythonPackages.audiotools.overrideDerivation (lib.const (rec { name = "audiotools-3.0"; src = fetchurl { url = "mirror://sourceforge/audiotools/${name}.tar.gz"; sha256 = "1fsn4fisik0k3xmrbqdavlzb5161vs79q8b8jgsbgzrhhqk89m5j"; }; })); }; })'
```

So maybe later this night or later this week.
