### ISSUE TITLE
beets deletes all tracks during an import

### ISSUE THREAD

**Issue by velvet-jones** [sampsyo/beets#1348]
1. Album has been previously imported into my library, i.e. it exists already in the library
2. I am running 'beet import MyAlbum' from within my library directory, meaning source and destination are the *same* directory
3. During import there is an unmatched track (re-create by copying any track and changing something about the track name such that there are duplicates of this track)
4. Run 'beet import MyAlbum': When beets notifies of an unmatched track and waits for instructions to proceed, open another terminal and delete the offending track
5. Now tell beets to [A]pply
6. It says album is already in the library. Tell it to [R]emove Old.
7. All tracks are deleted.

**Comment by sampsyo** [comment]
Thanks for reporting. We're tracking this in #702.
