### ISSUE TITLE
Inverted/negative query strings not supported?

### ISSUE THREAD

**Issue by iamcakewizard** [sampsyo/beets#1349]
I can't seem to figure out how to create a negative/inverted query
string in Beets.
I have a flexible attribute called `itunes`. It's set to `true` for every song which has already been converted and exported into iTunes.
I'd like to create a query string which returns all the tracks where `itunes` is not set to `true` so that I can write a shell script which automatically converts any un-converted tracks and drops them into iTunes'
auto-scraper folder. 

While I could technically achieve it with regex (`itunes:^((?!true).)*$`, if my knowledge of regex is sound), it seems like this should be easier so either I'm being dumb and overlooking something, the functionality simply isn't documented, or this
actually isn't implemented in beets.

**Comment by sampsyo** [comment]
I totally agree; negative query terms would be great. The feature request ticket for this is #819.
