### ISSUE TITLE
Is there an option to automatically keep duplicates?

### ISSUE THREAD

**Issue by dprus** [sampsyo/beets#1363]
I currently keep FLAC versions of all my albums but in order to play my albums in my car I have to re-encode them to AAC. Obviously I don't want to throw away my lossless files so I like to keep two copies of each album (one FLAC and one AAC).

The issue is that when I go through and import with beets it keeps telling me that an item is already in the library and the default option is to "Skip new" where I really want to "Keep both". With a very large library this is an extremely tedious process.

I can't seem to find a way by looking through the documentation but is there any way to tell beets to allow duplicate copies of songs if they are in different formats? I'm sure I'm not the only person that does this?

**Comment by sampsyo** [comment]
Please see #185.
