### ISSUE TITLE
Simple YAML problems should be fixed (or at least reported)

### ISSUE THREAD

**Issue by alphapapa** [sampsyo/beets#1369]
I just ran into https://github.com/sampsyo/beets/issues/1125.  I was following the "Getting Started" guide, and I opened the config file in Emacs, and I used the tab key to indent the `import:` section, and it caused that unintuitive error.

I tried unindenting that section completely, but that caused another unhelpful error:

`configuration error: import must be a collection, not NoneType`

So I tried spaces, and then it worked.  Then I came here and looked up that bug report.  If I didn't know anything about Python, I don't know if I would have figured it out so quickly.

Beets sounds awesome, but it's sad that its introductory experience is marred by this silly problem.

1.  When `beet config` is run, it should report simple problems like sections indented with tabs instead of spaces.  Or even better, just fix them outright.  A simple regexp could replace leading tabs with spaces.
2.  This should be documented in the "Getting Started" guide in a prominent font.  (https://github.com/sampsyo/beets/pull/1370)

**Comment by tomjaspers** [comment]
Good find. I'll take a look at this.

**Comment by brunal** [comment]
I think that this is a problem on pyyaml parser side more than beets side though.

**Comment by tomjaspers** [comment]
Well yeah, the problem is indeed on pyyaml's side. I found the errors not very unintuitive at all, either.

The increased documentation in the getting started guide is a good idea though. Think this can be closed with your PR (after my comment there).

**Comment by sampsyo** [comment]
Thanks for suggesting the expanded documentation!

I don't think we're going to automatically replace tabs with spaces to create a kind of pseudo-YAML syntax. That seems like a troublesome tarpit of incompatible heuristics.

**Comment by alphapapa** [comment]
According to the [YAML FAQ](http://www.yaml.org/faq.html), tabs are explicitly forbidden in YAML files.  So there should be nothing but positive effects from automatically doing, e.g. `sed -i 's/\t/ /g' config.yaml`.  It will prevent this error from ever happening to a Beets user again.  ;)

**Comment by sampsyo** [comment]
Unless tabs occur in string literals, even multi-line string literals, or have some other meaning. I'm not sure if it will productive to go down that road.

**Comment by alphapapa** [comment]
Well, at least this regexp should be safe and prevent most people from encountering this problem on initial setup:

```
s/^\t+/    /g
````
It just seems obvious to me that 99% of new users will run into this problem as soon as they create a configuration file, getting a useless error message and thinking that Beets is simply broken.  It's a shame.
