### ISSUE TITLE
import options -g and -s are unclear

### ISSUE THREAD

**Issue by alphapapa** [sampsyo/beets#1372]
I've read the docs, but I can't figure out what the difference is between `import -g` and `import -s` and `import -gs` if I run them on a directory containing tracks from multiple albums.  I think this should be clarified.  :)

**Comment by brunal** [comment]
Hi,
```
$ beet import --help
[...]
  -s, --singletons     import individual tracks instead of full albums
[...]
  -g, --group-albums   group tracks in a folder into separate albums
[...]
```

I'm not sure what's unclear about that:
* `s` will consider each file separately
* `g` will try to split tracks in a folder into multiple albums
* `gs` will... well it does not make a lot of sense. Indeed when I look at the code ([beets/importer.py:292](https://github.com/sampsyo/beets/blob/d09c8c66b343fcd50b70b9cc7c419f343bbc493d/beets/importer.py#L292)) `-s` will override `-g`, so `-gs` is equivalent to `-s`.

**Comment by guibog** [comment]
If I may, the phrasing is not crystal clear and may be improved. "import
individual tracks instead of full albums": as a dumb user, I'll think: "but
when I'm importing full albums I'm also importing individual tracks, no?".
So maybe something like "do not assume tracks in the same folder belong to
the same albums", but is it the real meaning of it? Does it mean "Do no try
to regroup tracks by album, use directly their album tag if any"?

For "group tracks in a folder into separate albums", maybe it would be more
clear to say "When atempting to regroup tracks by album, allow mutliple
track from a folder to belong to different albums"

And last: if -gs do not make any sense, better disallow it, I guess.


On Mon, Mar 23, 2015 at 5:36 PM, Bruno <notifications@github.com> wrote:
>
> Hi,
>
> $ beet import --help
> [...]
>   -s, --singletons     import individual tracks instead of full albums
> [...]
>   -g, --group-albums   group tracks in a folder into separate albums
> [...]
>
> I'm not sure what's unclear about that:
>
> s will consider each file separately
> g will try to split tracks in a folder into multiple albums
> gs will... well it does not make a lot of sense. Indeed when I look at
the code (beets/importer.py:292) -s will override -g, so -gs is equivalent
to -s.

**Comment by alphapapa** [comment]
Well, maybe I haven't drunk enough beet juice to understand (ha), but this still seems very ambiguous to me.

For one thing, what if I'm using `copy: no` and `write: no`?  Do these options do anything then?

Besides that, the whole idea of importing tracks in a directory as a single album doesn't make sense to me in the first place, because the directory the tracks are in ought to be irrelevant when importing, because the album should be determined by the track's album tag.

For example, in my music collection, I have some tracks that are well organized in a defined structure like `artist/album/title`.  But for some tracks, depending on when and how I acquired them, and whether I've taken the time to retag and organize them, and whether I have an entire album's tracks, there might simply be a directory for the artist with several tracks in it from mixed albums.

So if I decide to import some music into beets, it might be from one of the `artist/album/title` directory structures, or it might be from an `artist/track` structure.

Now if it's from the former, it seems straightforward to import them in a `directory = album` kind of way. 

But if it's from the latter, then it is confusing: if I don't specify `-s`, will Beets determine that all the tracks in the directory are from the same album, regardless of their metadata?  Or will it import them without any album tag at all, since it's "importing tracks instead of albums"?  What if I use `-g`?  Does that mean that it _will_ use the track's album tag to determine its...album tag?

What does it even mean to "group tracks into an album"?  How would one import tracks without "grouping them into an album"?  I thought one of the major ideas of Beets was to canonicalize the metadata.  So would that mean that `-s` would ignore the album tag completely?

I don't understand the idea of importing all the tracks in a directory "as an album" or "into an album", because a track's album should be determined by its album tag, not by its directory.  My music manager shouldn't care about a track's file path, and when I'm browsing or searching my music collection, I shouldn't have to care about that either.  If I choose to reorganize my tracks into a certain path/filename structure (like I do with Clementine), that's nice, but it shouldn't ultimately matter.

Do you see what I mean?  I'm used to the Amarok/Clementine style, in which you have a root directory for your music collection, it scans everything in it, and then you browse by metadata.  If you choose, you can have it reorganize the file structure for you, but that's optional.  To "import" music, you simply copy the files anywhere in `~/Music` or whatever, and it picks up the file, adds it to the database, and then you can see it in the library.  If you choose, you can have it "Organize" the files for you and put them at certain paths in your library, but that's orthogonal to "importing" the files into the collection, which really amounts to detecting the tracks and adding them to the database.

I hope I've explained better this time.  :)  Thanks.

**Comment by guibog** [comment]
Hi, did you use Picard tagger for MusicBrainz? I used it a lot and to me beets is primarly a "Picard on the command line". It can also do much more than Picard, but it's basic task is to get some tracks, and try hard to find its canonical metadata on MusicBrainz.

To do that, it can be very helpful to temporaily regroup tracks by whatever hint is available. In Picard it is called clustering I think. Why is it useful? Because, for example, you could have an album which has 12 tracks, and another release of the same album which have 13 (includes a bonus track). Then you cannot consider tracks individually, you have to know/guess how many tracks are in the "cluster" so you can increase the likeliness of a good match on MusicBrainz.

I still agree that the wording of `-s` and `-g` could be improved, but I guess both are useful for some cases.

**Comment by alphapapa** [comment]
Hi, yes I often use Picard to fix up tags.  I see what you mean about having multiple, similar tracks from slightly different albums.

If all Beets does is use the grouping as a hint, that's simple enough.  From the docs, I couldn't tell if it was doing that or using it as a hard rule.

**Comment by sampsyo** [comment]
Directory grouping is a hard rule, except for multi-disc albums (for which the heuristic is also documented) or unless you specify `-g`. It looks like the behavior you're expecting is `-g`, so I'd recommend turning that on in your config file.

More documentation is always welcome. There's not much more we can explain in a single line of text in the `beet help` output, but sentences in the "getting started" guide or the CLI reference page could indeed be helpful.

**Comment by alphapapa** [comment]
Respectfully, I still think the `help` output needs to be changed.  If a user (i.e. not a Beets developer ;) has to consult the reference manual to figure out which option to use for basic functionality (importing is about as basic as it gets), then I think that's a problem.

The help for `-s` and `-g` is still ambiguous.  For a very common use case (a directory containing tracks from different albums), a new user would have no idea which option to use.  Contrast with other solutions like Picard, Clementine, etc, which seem to just do the right thing without having to read a reference manual.  ;)

**Comment by sampsyo** [comment]
Sure, we can always do better—do you have ideas for short, one-line summaries that would be clearer for those two options?

**Comment by alphapapa** [comment]
I would be glad to give some ideas, but short of reading the Beets code myself, I still don't know what the difference in outcome is between `-g` and -`s`.  From what I've gathered, both options allow tracks in a single directory to be assigned album tags independently, rather than being forcibly considered part of a single album (the default behavior?).  So what is the difference between them?  When would I want to use one and not the other?

And I still wonder, what if two totally different tracks were in a single directory--say, a classical track and a heavy metal track--and neither `-g` nor `-s` were used on import.  What would happen?  Would Beets pick one track, get its album, and then assign the other track to be from the same album, even if the match was something like 0% (which would effectively lose data, erasing that track's original metadata, which may or may not be available from MusicBrainz)?

I'm sure this seems obvious to those who've written the code, but to a new user, the intended behavior is not at all clear, and I don't even know how to explain it yet myself.

I wonder if the two options should be refactored into a single option, or somehow reorganized in a way that seems more distinctive.

**Comment by sampsyo** [comment]
Take a look at the parts of the docs that describe "singletons" in general. -s adds music to your library in that mode, and metadata for individual tracks is looked up separately, per-track. In -g mode, as in the default, albums are tagged together, an album at a time, and the database keeps them grouped together.

**Comment by alphapapa** [comment]
Ok, I searched the docs for "singleton" and probably the most helpful part was a changelog entry that mentioned it.

I think maybe there are a few separate yet related issues that are confusing me.

1.  The database model.  When you say "the database keeps them grouped together," do you mean that, to Beets, an album is more than simply tracks with the same album tag?  I saw mention of an "album object" in the API docs.

  This seems confusing to me, because in all the other music library software I've used, an "album" is simply a set of tracks sharing the same album tag, e.g. `SELECT FROM tracks WHERE album LIKE "Album Name"`.  I'm getting the impression that Beets somehow layers another album-gropuing abstraction on top of this, independent of tracks' metadata.

  If this is correct, well, I understand that it's probably pretty fundamental to how Beets works, so it's probably not something you'd want to change.  But it seems to me that it may not be a good idea, for a few reasons: 

  a) it's confusing to new users (at least, to this one ;)
  b) it's unlike just about any other music library software
  c) it seems to restrict flexibility
  d) it increases the risk of matching tracks to the wrong album and therefore setting their metadata incorrectly (and possibly losing existing, accurate metadata)

2.  Importing.  I have the impression now that if I do not use `-s`, Beets may attempt to "force" a track into an album which it is not a part of, regardless of its match probability score, and so it risks overwriting accurate metadata with completely inaccurate metadata.  (I realize that it's set by default to prompt before doing this, but it's easy to make a mistake when going through many prompts requiring manual confirmation.)

  This just doesn't seem like a good idea to me.  To use a poor analogy, it seems like the "gun" is, by default, "aimed near the user's foot," and depending on `-s` and a track's match probability, it may or may not become "aimed at the foot" when a prompt appears...and if the user chooses the wrong answer, it may be "fired at the foot" instead of being aimed away.

  I know that when I was doing some test importing, there were many tracks which had low match scores (even quite a few at 0%), and it felt laborious and error-prone to read through all the incorrect, potential-match choices, look at the score, look at the list of actions, figure out which one was correct (or least risky), and then make sure I pressed the right key.  Doing this for tens, hundreds, or thousands of tracks, it seems nearly guaranteed that most people will make some mistakes, potentially replacing existing metadata with incorrect metadata.

  It seems to me that Beets should consider tracks independently by default so that this is not a risk.  A potential "force-square-tracks-into-round-album-holes" mode should not be the default.  Ideally it shouldn't even be necessary, because each track should be independently identifiable.  Of course, I recognize that a process like this is full of non-ideals, so a kind of advanced mode that would take less-identifiable tracks and use more-identifiable tracks to help identify them makes sense to have available.

  I suppose that, for me, the bottom line is that when importing, Beets should always default to the safe option unless a more advanced, potentially dangerous mode is manually enabled.  I want to feel confident that Beets will never overwrite metadata with low-probability matches unless I manually force it to.

To try to sum up:

1.  I think album grouping might be better served by simply matching on the album tag rather than having an extra album-grouping layer.
2.  Perhaps importing should default to singleton mode to avoid the "square-track-in-round-album-hole problem."  It would be the safer option.  Users could always manually use the album-grouping mode and reimport tracks that are difficult to identify as singletons.

**Comment by sampsyo** [comment]
Album structures in the database are essential for (a) disambiguating between different albums with the same name, which is important to a surprising number of people, and (b) keeping track of per-album metadata, such as album art.

Per-album importing is essential for getting certain metadata, like track numbers, consistent. I totally understand that it doesn't fit everybody, though, which is why you can put "singletons: yes" in your config file.

To be clear: I really appreciate your input and perspectives, so please keep them coming, but neither of these fundamental assumptions is going to change without a tremendous amount of effort.

**Comment by alphapapa** [comment]
I understand.  You're right about albums with the same name, which I'm sure is not uncommon.

I guess to sum it all up, I was expecting importing in Beets to work like tagging in Picard when you simply pass it a list of files or a directory containing random tracks.

Maybe it would be good to add a paragraph in the getting started guide explaining that most users might prefer to use singleton mode at first, since it would probably be more familiar and less likely to cause tagging mistakes.

Thanks for your patience reading my ideas.  I hope I can figure out a way to make Beets "work for me,"  because it seems really nice.
