### ISSUE TITLE
How to match album name as key in path configuration?

### ISSUE THREAD

**Issue by dramaturg** [sampsyo/beets#1380]
Hello everyone,

I imported mixtapes as singletons so far but seeing that I have a few that are a series of mixtapes I now want to move those into a compilations subfolder. I thought of trying it like this:

```
paths:
    default: $albumartist/$year - $album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
    album::'^Foobar': Compilations/Foobar/$title ($artist)
```

Where _Foobar_ is the series I want to be sorted differently. Unfortunately it seems I can not match like this in the path configuration? At least everything is still sorted into _Non-Albums_

Any idea how I might be able to do this? Should I look into the inline plugin instead?

**Comment by sampsyo** [comment]
I see a couple of issues here:

* First, paths are searched in order. So place your new rule above the "singleton:" line for it to take precedence.
* You'll want to follow YAML syntax and quote the entire query (i.e., the dictionary key). Do something like `'album::^Foobar': Compilations/Foobar/...`.

Let us know if those make this work.

**Comment by dramaturg** [comment]
It works wonderfully and I was able to re-import/move the tracks like this:

```
beet ls -p album:'Foobar'  | perl -p -e "s/\n/\0/;" | xargs -0 -n1 beet im -A
```

(Would be nice if this could be done directly with something like _beet im -A -L QUERY_ but this works for me)

Thank you for your help!

**Comment by sampsyo** [comment]
The `beet move` command may be what you want. :smiley:
