### ISSUE TITLE
Bad AC/DC support

### ISSUE THREAD

**Issue by brunal** [sampsyo/beets#1385]
Hi,
Queries with A/CDC suck, probably because of a path is detected.
```
$ time ./beet ls -a "albumartist:AC/DC"
real	0m0.550s
user	0m0.450s
sys	0m0.083s
```

```
$ time ./beet ls -a "AC/DC"
Traceback (most recent call last):
  File "./beet", line 20, in <module>
    beets.ui.main()
  File "/home/bru/code/beets/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/home/bru/code/beets/beets/ui/__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/bru/code/beets/beets/ui/commands.py", line 989, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/home/bru/code/beets/beets/ui/commands.py", line 981, in list_items
    for album in lib.albums(query):
  File "/home/bru/code/beets/beets/dbcore/db.py", line 525, in _get_objects
    if not self.query or self.query.match(obj):
  File "/home/bru/code/beets/beets/dbcore/query.py", line 429, in match
    return all([q.match(item) for q in self.subqueries])
  File "/home/bru/code/beets/beets/library.py", line 79, in match
    path = item.path if self.case_sensitive else item.path.lower()
  File "/home/bru/code/beets/beets/dbcore/db.py", line 316, in __getattr__
    return self[key]
  File "/home/bru/code/beets/beets/dbcore/db.py", line 224, in __getitem__
    return getters[key](self)
  File "/home/bru/code/beets/beets/library.py", line 973, in item_dir
    raise ValueError('empty album')
ValueError: empty album

real	0m20.293s
user	0m8.410s
sys	0m11.097s
```

Subsequent times are < 1 sec.

```
$ ./beet ls "AC/DC"
$ ./beet ls Jailbreak
AC/DC - Gold Album 1974-2000 - Jailbreak
$ ./beet ls -p Jailbreak
/home/bru/Musique/AC_DC/Gold Album 1974-2000/03 Jailbreak.mp3
```

**Comment by sampsyo** [comment]
Hmm… yes, this is getting detected as a path. But I think the crash you're seeing is another artifact of that aforementioned situation from #1357 where a prior crash led to an empty album (which should never exist) in your database. All the more reason to sort out that atomicity issue…

**Comment by brunal** [comment]
You're right. I had, for an unknown reason, multiple empty albums "Billy Breathes" by Phish.

The "beet ls -a" request is still really slow: 30 seconds!! I have 2 questions:
* do you think that matching "AC/DC" as a path is desirable? Shouldn't beets first test whether the path exists, it if does then path-match otherwise classic match?
* is that slowness expected? Seems like beets fetches all albums and for each fetches an item. What makes it so slow?

**Comment by sampsyo** [comment]
> do you think that matching "AC/DC" as a path is desirable? Shouldn't beets first test whether the path exists, it if does then path-match otherwise classic match?

Sure! Testing for existence first seems like a good policy. We'll need to clearly update that part of the docs, of course.

> is that slowness expected? Seems like beets fetches all albums and for each fetches an item. What makes it so slow?

Yeah, that does seem suspiciously slow. Beets has fast queries and slow queries, but I don't see what about this would make it a slow query. Or maybe there's something else unexpected going on—maybe profiling would be in order?

**Comment by brunal** [comment]
Here is the path detection improvement. I'm now looking at the speed issue with a command such as
```
$ beet ls -a ~/Musique/AC_DC/
```

**Comment by sampsyo** [comment]
Great. For paths like that, `beets.util.normpath` is usually the right answer.

I also think we may need a call to `syspath`, right? Since the query is coming from the user, it should be Unicode. So something like:

    os.path.exists(beets.util.syspath(beets.util.normpath(p)))

Ugh.

**Comment by brunal** [comment]
Since the path is given by the shell, shouldn't it be expanded?

On the slowness side, I think a slow query is normal: in `beets.library.parse_query_parts()` there is 
```
fast_path_query = 'path' in model_cls._fields
```
Since albums don't know their path (only its items do) the query is slow, and all albums are fetched and for each an item is fetched to determine whether it matches the path... Should it work differently?
Isn't there a way to make it faster? e.g. with a JOIN (currently not supported AFAIK)

**Comment by sampsyo** [comment]
Good point about shell expansion. It's true that `path:~/foo` isn't expanded, but we care about queries like a bare `~/foo`.

> On the slowness side, I think a slow query is normal

Oh! Indeed. Sorry I missed this—yes, path queries on albums are slow queries. We could conceivably write a fast version with a JOIN, but that sounds a little tricky to do cleanly.

**Comment by brunal** [comment]
Sooo.... I should still add `normpath` right? And `syspath` yes or no?

**Comment by sampsyo** [comment]
Let's say yes and yes. (`normpath` can't hurt, and `syspath` is necessary for Windows.)

**Comment by brunal** [comment]
Done and done!
