### ISSUE TITLE
discogs plugin throwing "invalid response from request token URL" error

### ISSUE THREAD

**Issue by jwyant** [sampsyo/beets#1417]
I'm doing this in a new virtualenv --no-site-packages.

```
Successfully installed beets discogs-client pyacoustid enum34 mutagen munkres unidecode musicbrainzngs pyyaml requests six oauthlib audioread
Cleaning up...
(env)jwyant@bigbox ~/code/beets $ ./env/bin/beet import ~/.music-incoming/flac
Traceback (most recent call last):
  File "./env/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/ui/__init__.py", line 1081, in main
    _raw_main(args)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/ui/__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/ui/commands.py", line 892, in import_func
    import_files(lib, paths, query)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/ui/commands.py", line 869, in import_files
    session.run()
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/importer.py", line 313, in run
    plugins.send('import_begin', session=self)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/plugins.py", line 455, in send
    result = handler(**arguments)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beetsplug/discogs.py", line 76, in setup
    token, secret = self.authenticate(c_key, c_secret)
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/beetsplug/discogs.py", line 98, in authenticate
    _, _, url = auth_client.get_authorize_url()
  File "/home/jwyant/code/beets/env/lib/python2.7/site-packages/discogs_client/client.py", line 61, in get_authorize_url
    raise HTTPError('Invalid response from request token URL.', status_code)
discogs_client.exceptions.HTTPError: 401: Invalid response from request token URL.
```

**Comment by sampsyo** [comment]
Thanks. We should catch and log this error.

**Comment by sampsyo** [comment]
This exception is now handled. Thanks again.

**Comment by skarekrow** [comment]
Same error, how does one resolve it? Discogs worked a couple weeks ago for me and I read it had some issues with beets that should be resolved with the latest version. 1.3.11 from pip. How do I get beets to reauthorize?

Thanks!

**Comment by sampsyo** [comment]
To manually force re-authorization, you can delete the discogs token file from `~/.config/beets` or equivalent. But I don't think that's the issue here—the error seems to arise when just getting the authentication URL from Discogs. Any chance the API key is being rejected?

**Comment by skarekrow** [comment]
I'm really not sure. I'm doing this in a docker container running from my Arch base. No discogs token file is being created. The config.yaml,library and state.pickle all do. This used to function but then stopped. I've tried putting in the default apikey and secret into the config and pointing it at where to save the tokenfile, but it still refuses too.

```
ui:
    color: yes

paths:
    user:brandon: Brandon/$albumartist/$album%aunique{}/$track $title
    user:mom: Mom/$albumartist/$album%aunique{}/$track $title
    user:dad: Dad/$albumartist/$album%aunique{}/$track $title
    user:tyler: Tyler/$albumartist/$album%aunique{}/$track $title
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
threaded: yes
fetchart:
    cautious: yes
    cover_names: front back
    sources: itunes *
    minwidth: 0
    maxwidth: 0
    google_search: no
    auto: yes
    remote_priority: no
    enforce_ratio: no
color: yes
library: /home/nas/.config/beets/library.blb

musicbrainz:
    host: localhost:9500
    ratelimit: 100
follow:
    email: brandonschneider89@gmail.com
    password: WxW4GsLEbdQxsVFu
    userid: cuecewljp4tr0h1sgssy3svtpd6enz
    auto: no

plugins: discogs duplicates fetchart follow
directory: /NAS/Music

import:
    move: yes
    copy: no
    write: no
discogs:
    apikey: rAzVUQYRaoFjeBjyWuWZ
    apisecret: plxtUTqoCzwxZpqdPysCwGuBSmZNdZVy
    tokenfile: /home/nas/.config/beets/discogs_token.json
    source_weight: 0.5
duplicates:
    album: no
    full: no
    format: ''
    keys: [mb_trackid, mb_albumid]
    move: no
    tag: no
    path: no
    copy: no
    count: no
    checksum:
    strict: no
    delete: no
```
So to recap, there has never existed a tokenfile for discogs on my system. So it must have been using the default one and maybe that's being rejected? I have an identical traceback as above.

**Comment by sampsyo** [comment]
Well, that's strange. Discogs is working fine here, and I see nothing suspicious in your configuration that would lead to anything different there.

Can you try upgrading your client library:

    $ pip install -U discogs_client

and trying again?

**Comment by skarekrow** [comment]
I have tried doing that. Running the latest versions from pip. I have even created a docker container for beets from Debian and still have the same issue. I can post the dockerfile so you can reproduce if you like.

**Comment by skarekrow** [comment]
Here's a dockerfile for my beets container with pyopenssl:
https://gist.github.com/skarekrow/1b0f9f06ecc4c637bdc0

and here is a version without:
https://gist.github.com/skarekrow/9a9eede9797175f57bb3

Neither version works with the discogs plugin.

**Comment by sampsyo** [comment]
Well, that took a **lot** of digging, but I was able to reproduce this on one of my machines. The problem there is likely the same problem you're seeing: Discogs isn't trusting your OAuth request because the system timestamp is too old. Your system clock is allowed to be at most 5 minutes off from theirs; otherwise, your request seems to be rejected.

Can you try fixing your system clock and trying again?

**Comment by jwyant** [comment]
Ha!  That is amazing.  ntp to the rescue.  I also updated pyopenssl with
"pip install --user -U pyopenssl" and it stopped throwing a different SSL
error.  No errors now.

**Comment by sampsyo** [comment]
Fantastic! :smiley:

**Comment by skarekrow** [comment]
Thanks so much for digging more into this @sampsyo. I checked and the clock is indeed off. I do use NTP, but it seems the system clock has still drifted. openntpd has been having an adjtime failure I just now noticed in the logs.

It does now work with the clock synchronized. That is amazing lol, what a weird error. You have some serious diagnosing skills.

**Comment by brunal** [comment]
I agree that finding that cause is impressive. Maybe the error message should be updated to offer that solution?

**Comment by sampsyo** [comment]
Indeed. There are multiple reasons this error could arise, but I'm guessing the only likely one is this timestamp issue. So it's at least worth guessing that in the error message.

**Comment by skarekrow** [comment]
Possibly. It certainly helped point me at a malfunctioning service on my system. Again, much appreciated you took the time out for this!

**Comment by brunal** [comment]
I actually doubt that this is the main issue that may trigger the exception: A generic HTTPError is generated with a `status_code` and a `message`. It can be raised any time `discogs_client` receives a non-200 status code for a request. Therefore I think that `discogs_client.exceptions.HTTPError` should simply be added to the list of CONNECTION_ERRORS.

Updating the discogs plugin doc with that solution should be enought.

**Comment by sampsyo** [comment]
Thanks, @brunal; I thought I had already added that exception but it looks like I missed it.

**Comment by skarekrow** [comment]
Looks good to me, that should help others. Thanks @brunal.
