### ISSUE TITLE
zsh completion

### ISSUE THREAD

**Issue by shanemikel** [sampsyo/beets#1420]
A good majority of the completion works with zsh if you put this into your .zshrc

```
autoload bashcompinit
bashcompinit
_get_comp_words_by_ref() { :; }
compopt() { :; }
_filedir() { :; }
eval "$(beet completion)"
```

Those dummy functions are AFAIK not yet implemented in zsh's bash completion wrapper; if you remove them from the .zshrc it will still work, but with annoying errors.

**Comment by sampsyo** [comment]
Interesting. Do you think we should detect whether we're running in bash and stub out those functions automatically? Or perhaps we should provide a `--zsh` flag that just drops those parts? Either way, contributions would be great.

**Comment by shanemikel** [comment]
I believe it's better to have one script if all you're doing is providing a dirty workaround like this (that way I only have to save one file in my home dir to source).  I think the best course of action is to leave the script as-is, and perhaps provide that code snippet in the documentation with a warning that it is a hack (until someone can provide native zsh commpletion, the zsh bash-completion support improves, or for all eternity).

**Comment by sampsyo** [comment]
Thank you! Instructions added.

**Comment by JesseWeinstein** [comment]
This does not appear to support plugin options, at least in my case (tested with the duplicates plugin).

**Comment by shanemikel** [comment]
I think there might be a better way than defining dummy functions for the ones that throw errors, but I'm not sure.  In setting up completion for mosh in bash, there is a variable COMPREPLY, and setting it to () seems to be their way of sending error messages away from the shell, check it out here: https://github.com/andersk/mosh/commit/c2ff878d48092792123fef5777e1520598346b87

So, maybe there is something similar in zsh...
