### ISSUE TITLE
method for relocating entire library

### ISSUE THREAD

**Issue by shanemikel** [sampsyo/beets#1421]
I was wondering if there's a way for the beets db to use relative paths?

I find myself moving to a new machine with a new username, and thus a new absolute path for my music library..
If there is no way to use relative paths in the db, how would you suggest updating the db?

(BTW) I contain ALL my beets-managed music in one directory per beets db, so this should be straightforward.  Perhaps, this should be in the docs?

**Comment by sampsyo** [comment]
For relative paths, please see #133.

If you want to move all your music to a new directory, you can configure the new base directory and then type `beet move` without a query to move everything to the new place.
