### ISSUE TITLE
fuzzy search plugin broken

### ISSUE THREAD

**Issue by EvilBit** [sampsyo/beets#1422]
invalid `self.config` reference in `FuzzyQuery` causes an exception.
See the following commit comment: https://github.com/sampsyo/beets/commit/4babc40fd8c48f07542542e266699b05cf0bf776#commitcomment-10747594

>   File "/usr/lib/python2.7/site-packages/beetsplug/fuzzy.py", line 33, in string_match
>     threshold = self.config['threshold'].as_number()
> AttributeError: type object 'FuzzyQuery' has no attribute 'config'

**Comment by sampsyo** [comment]
Thank you! Fixed.

**Comment by EvilBit** [comment]
Thank you!
