### ISSUE TITLE
import subfolders and other files

### ISSUE THREAD

**Issue by jakuzure** [sampsyo/beets#1424]
Most of my album folders also contain a cuesheet and some logs or some scans in a subfolder. I would really love a feature that would let me move everything at once using beets import command.

**Comment by brunal** [comment]
The copyartifacts plugin does exactly that: https://github.com/sbarakat/beets-copyartifacts

**Comment by jakuzure** [comment]
I searched and even ask on IRC if it's possible to somehow achieve this. Thanks for telling me! This prevented actually using beets for me
