### ISSUE TITLE
embedart plugin disregards "write: no" and "-W" config opts

### ISSUE THREAD

**Issue by reynhout** [sampsyo/beets#1427]
Any import action with `embedart` enabled causes a full write of tags and art, even when config file specifies `write: no`, or commandline includes `-W`.

CAUSE: `art.py` does not check config option `import/write` before calling `try_write`.

SUGGESTED FIX: check config option first! :) PR will be attached presently.

**Comment by reynhout** [comment]
It might be preferable to add the config check into `library.py` function `try_write` itself.

There are two other locations that call `try_write`: `importer.py/manipulate_files` and `library.py/try_sync`.

PR#1428 adds the config test to `art.py/embed_item`, for a third occurrence of similar code.

**Comment by sampsyo** [comment]
Thanks for the report, and for the fix! This is indeed a problem.

**Comment by reynhout** [comment]
A better fix, hopefully in the correct place:

https://github.com/reynhout/beets/commit/febcef1b07c1ab9a68d5337da1e81d3669cb8080

**Comment by sampsyo** [comment]
That looks awesome; thanks. If you can just add a quick note to the changelog about the fix, this will be ready to merge. :smiley:

**Comment by reynhout** [comment]
OK, will do.

How should I add a test the `embedart` plugin? Should it go into `test_importer` or `test_embedart`? Should it be its own class (`EmbedartPluginTest`?)

I don't see code I could reuse for testing plugins from the import CLI command. Looks like I'd need to reproduce the setup and teardown bits into a new class. Is there a simpler way? Thanks!

**Comment by sampsyo** [comment]
Great! If you open a new PR with the new change, we can merge that now.

Then the tests can come later. As you have inferred, they will be a little involved. Some setup and teardown will indeed be needed—some of the other plugin tests (e.g., `test_fetchart.py`) can provide a template.
