### ISSUE TITLE
AAC files not imported

### ISSUE THREAD

**Issue by hindsholm** [sampsyo/beets#1432]
I have a bunch of aac files that I would like to import into beets.

I don't want to package them as m4a, because my Squeezebox Radio is unable to play m4a files, but aac files are fine.

The files are OK, mediainfo returns this:
```
General
Complete name                            : 002_F853056C281BA3B7E040010A0D062C49.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 8.84 MiB
Overall bit rate mode                    : Variable

Audio
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LC
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 8.84 MiB (100%)
```

The files also play OK in RhytmBox on Linux 14.10.

However, when I do a `beet import -v .`, this is the result:
```
user configuration: /home/morten/.config/beets/config.yaml
data directory: /home/morten/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 7, 7))
library database: /mnt/delle/music/beets.blb
library directory: /mnt/delle/music
Sending event: library_opened
Sending event: import_begin
No files imported from /home/morten/tmp/tdcp_elisabeth
Sending event: import
Sending event: cli_exit
```

I am no expert in Python, but it seems to me, that mediafile.py does not really handle .aac files.

Please let me know, if I can help solve this issue. I think beets is just great!

**Comment by sampsyo** [comment]
Looks like you've got raw [ADTS](http://wiki.multimedia.cx/index.php?title=ADTS) files. You're right that beets doesn't support them, mainly because they cannot include metadata (AFAIK).

Maybe it would be better to catalog your library as full .m4a files and use `convert` to produce player-ready files on occasion? If you really want these raw files in your library, then we can consider passing them through but not writing tags, but I'm not sure how useful that will be.

Do you know more than I do about this format? Do other tools somehow store tags on them?

**Comment by hindsholm** [comment]
It seems that aac metadata is indeed not very well supported. The command line tool `id3v2` is able to add metadata, but it somehow makes the file unplayable on some of my devices :-(

I think will look for a conversion to another format which will allow me to both tag and play the files. They are a minor part of my library, most of which is in FLAC. Using convert is not really what I want, because I want my Squeezebox server to serve my library directly.

Thank you for fast response - keep up the good work on beets!
