### ISSUE TITLE
warn('%s: %r' % (err, data), ID3Warning): Windows

### ISSUE THREAD

**Issue by dajo** [sampsyo/beets#1434]
I've having trouble pinpointing the cause of this, but I am receiving large amounts of garbled text (it overwhelms my buffer of 10000 rows) and then `warn('%s: %r' % (err, data), ID3Warning)` 

I'm on Windows running from source. Even without verbose logging, I receive garbled output to stdout.

**Comment by dajo** [comment]
I maxed out my buffer to 32768 rows. Here's a gist of the beginning of one of those blocks with -vv output: https://gist.github.com/dajo/6f2e6d7c48c15fb17cbf

**Comment by lazka** [comment]
I've added this warning in the last mutagen release. Previously files generating the warning failed to load instead. I guess I'll remove them with the next release.

Can you figure out which mp3 file generates them and send me one? reiter.christoph@gmail.com

**Comment by dajo** [comment]
Turned threading off to better isolate, and I did track one file down. [Mp3Tag](http://www.mp3tag.de/en/) indicates that it's a !BAD ID3v2. Sending it your way.

**Comment by dajo** [comment]
Finally, I should say that forcing the rewrite of the tags with MP3Tag or a similar tool clears up the issue.

**Comment by sampsyo** [comment]
OK! Thanks, both of you. I'll close this as a Mutagen thing.

**Comment by lazka** [comment]
Fixed in https://bitbucket.org/lazka/mutagen/issue/223

**Comment by lazka** [comment]
A new release is up on the cheese shop..

**Comment by sampsyo** [comment]
Thanks, @lazka! Awesome as always.
