### ISSUE TITLE
Feature: manual override of Musicbrainz match

### ISSUE THREAD

**Issue by reynhout** [sampsyo/beets#1438]
A problem I'm running into fairly often while importing my large (completist) library:

* Multiple releases from a single artist have the same title in Musicbrainz.
* The releases are distinguished by year, country of release, and/or release type (single, EP, LP, LPx2, etc).
* beets uses the Musicbrainz data to re-tag each release as the same "album", which confuses some other media players (e.g. iTunes) into considering all tracks to be part of a single release. (In fact, iTunes for some preference sets will move the files into the same directory if the album tags change to match!)

beets already flags the second import of the same "album" as probably unexpected, and gives the user a few options to resolve: `[S]kip new, Keep both, Remove old?`.

I'd like a fourth option, something like: `reTitle new album`, which would accept all of the other Musicbrainz corrections (track title capitalization, etc) but offer the user a chance to set the album title explicitly. Automatic with options would be awesome, but more tricky than valuable, I think.

Some common examples and possibly-preferable substitute `TALB` tags:
* A single (with otherwise unavailable B-sides) with the same title as the full length: "Titlename (single)"
* An EP with the same name as the full length: "Titlename (EP)"
* The UK or JP release of a recording which has additional tracks: "Titlename (JP)"
* An artist that released two records with the same title, in different years: "Titlename (2003)"
* An album that was remastered and rereleased: "Titlename (2005 remaster)"

Is there an existing way of handling this sort of situation, other than skipping and revisiting manually?

If not, I can code this up for my own use. If there's support for the feature in mainline beets, I can also make it clean and add tests, etc.

I would appreciate your thoughts!

**Comment by sampsyo** [comment]
Indeed, manually editing metadata—either during import or even afterward—would resolve lots of situations like this. We have a proposal for that in #396. Could you perhaps add your thoughts there?
