### ISSUE TITLE
beets writing both lowercase and camelcase fields when importing

### ISSUE THREAD

**Issue by sondr3** [sampsyo/beets#1439]
I'm curious about this, I've run into problems a few times where MPD/ncmpcpp would behave very strange when editing music in the tag editor and I asked around on IRC and it seems the biggest problem is that beets writes multiple identical fields.

So you'd have artist/Artist, albumartist/AlbumArtist and so on which confuses some players. Musicbrainz Picard doesn't do this and I was curious on why this is done? I've considered using the null plugin do not write some of these duplicate tags but just wanted to ask :)

**Comment by sampsyo** [comment]
It's for compatibility with other tools. Unsurprisingly, I consider this a bug in ncmpcpp. :smiley: Check out #350.
