### ISSUE TITLE
Beets is confused about music directory location after update

### ISSUE THREAD

**Issue by mxmerz** [sampsyo/beets#1445]
I just updated beets to version 1.3.13 and now I’m getting these error messages when beets finds an album that is already in my library:

```
Tagging:
    Hoobastank - The Reason
URL:
    http://musicbrainz.org/release/43b24a11-4a70-3148-b2c2-9c21a36ef409
(Similarity: 100.0%) (CD, 2003, DE, Island)
 * Same Direction
 * Out of Control
 * What Happened to Us?
 * Escape
 * Just One
 * Lucky
 * From the Heart
 * The Reason
 * Let It Out
 * Unaffected
 * Never There
 * Disappear
This album is already in the library!
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-01 Same Direction.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-02 Out of Control.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-03 What Happened to Us_.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-04 Escape.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-05 Just One.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-06 Lucky.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-07 From the Heart.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-08 The Reason.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-09 Let It Out.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-10 Unaffected.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-11 Never There.mp3'
could not get filesize: [Errno 2] No such file or directory: '/Volumes/Hobbes/music/Hoobastank/The Reason/01-12 Disappear.mp3'
Old: 12 items, MP3, 222kbps, 41:56, 0.0 B
New: 12 items, MP3 11, AAC 1, 226kbps, 41:56, 69.1 MB
[S]kip new, Keep both, Remove old? 
```

Beets appears to look for the files in `/Volumes/Hobbes/Musik/`, a folder where I used to keep a different beets library (I switched libraries by changing the `library` and `directory` config file options). Now, I have my library file and directory somewhere else, under `/Volumes/mordor/music/`:

```yaml
### Library ### 

## Musik auf mordor
directory: /Volumes/mordor/music/beets
library: /Volumes/mordor/music/beets/.beets-lib.blb

[…]
```

I already confirmed that this is the config file beets uses by checking the output of `beet config -p` and by confirming that beets does move newly imported music files to the correct library directory.

Could you point me to what I’m doing wrong?

**Comment by tomjaspers** [comment]
See #1421 

You basically have to run `beet move` to move your music to the new directory after having changed the path in the config file.

**Comment by mxmerz** [comment]
I did not move my music files, I began a new library file and imported everything again with beets. Also, this change was made weeks ago and I did not run into any problems – only when I updated beets today did these error messages start to pop up.

An additional observation I made: When I type `r` to let beets remove the old music files, beets moves the new files to the correct directory, but does not delete the old ones. (The new files all get a filename ending in `.1.mp3`.)

**Comment by sampsyo** [comment]
The thing to do when changing directories and importing everything again is to delete the library database and start from scratch. Alternatively, you could ask beets to do the move for you using `beet move`, but the former is probably what you want in this case.
