### ISSUE TITLE
Issues migrated from Google Code are missing detail

### ISSUE THREAD

**Issue by untitaker** [sampsyo/beets#1453]
The links to code.google.com redirect to a completely unrelated GH issue, so only the title is left. For many issues this is not a problem, and I am not sure if there's anything that could be done against it.

**Comment by sampsyo** [comment]
Yes, those old issues are in bad shape. It's still possible to hunt for the Google Code ID and manually go to https://github.com/google-code-export/beets/issues/THE_ID, but that's definitely a pain.

Maybe we can write a one-off script to update all of those descriptions to point to the migrated location?

**Comment by untitaker** [comment]
I'd be up for it.

**Comment by sampsyo** [comment]
Cool. I think if I make you a collaborator, you should have permission to modify issue descriptions—can I trust you to test things out to avoid accidentally changing too many issues? :smiley:

**Comment by untitaker** [comment]
Yeah, I'll try. :)

**Comment by untitaker** [comment]
I'd have a prototype ready. Could you give me access, temporarily?

**Comment by sampsyo** [comment]
Yep! Granted. No need to revoke it, really; just use your power for good and not evil. :sparkles:

**Comment by untitaker** [comment]
Ok I've replaced all links. Would it make sense to paste the whole conversation into the issue bodies, or is it fine as-is?

**Comment by sampsyo** [comment]
Awesome! This worked perfectly! Thanks! :smiley:

Let's leave it like this—I think it would get a little messy if we included the whole conversation inline.

**Comment by untitaker** [comment]
Ok great.

**Comment by untitaker** [comment]
Oh, what we *could* do is to lock discussion on the migrated issues, to keep discussion inside this bugtracker. Do we have access to google-code-export/beets?

**Comment by sampsyo** [comment]
Sadly, no—and I don't know who to ask to get access. It would sure be nice if *all* of those projects were locked as read-only.

**Comment by untitaker** [comment]
I've resorted to commenting in a large fontsize on all issues there. I've only done this for open issues though.

**Comment by sampsyo** [comment]
OK, that sounds right! Thanks.
