### ISSUE TITLE
Handling of the results of multiple plugins registered for one event

### ISSUE THREAD

**Issue by mried** [sampsyo/beets#1463]
While writing a plugin to stop the import of files already present at the library (like discussed here: #1441), I stumbled over the result handling when more than one plugin is registered to the `imort_task_created` event. Plugins may return `ImportTask` objects to change the imported files or change an album import into a singleton import for example.
Right now we have: If there are two plugins registered for the event and they do nothing but returning the tasks, the tasks will be duplicated. So the returned tasks are concatenated and then executed.
I think the behaviour should be changed so that the results of the first plugin are passed to the second one as input. This way, we will get some sort of a pipeline.
One bad thing about this is: The order in which the plugins get executed is important.
Is this a goal we (I :smile:) should work on?

**Comment by sampsyo** [comment]
Urgh, you're right that the current behavior is not right! Thanks for pointing that out.

Chaining the results would make sense in this particular case, but it would make the story much more complicated for other events. (It wouldn't be possible, for example, to have an event take an Item and return a boolean—then, if two plugins were activated, then the second one would get a boolean instead of an Item!)

Maybe import-input-filtering is a special enough case that it needs a completely separate design from standard events? Or maybe we can think of a clever way to get the right compositional behavior out of the current call/return event system… although I don't have any great ideas right now.

**Comment by mried** [comment]
Well, at least we agree this behavior isn't correct :wink:
You're definitely right that chaining won't work for all events. Right now, the `import_task_create`event is the only one where chaining can work. So one possible way would be to create chained event emits only for this event. All other events are handled like they are right now. But I'm not sure if it is a good idea to create two different event emitting techniques.

**Comment by sampsyo** [comment]
Yeah, two event "modes" would certainly be weird too. Maybe we could just change the event to return a Boolean, where any single plugin that returns True drops the task? That would be enough for filtering, although it's less general.

**Comment by mried** [comment]
Doing so would break my automatic singleton detection... So that's not an option for me :wink: 

I'll see if I can put the "Don't import files from the library when `-L` is not set"-logic into the importer itself without writing a plugin. This won't help us with chained plugin calls, of course.

**Comment by mried** [comment]
I finally found a solution for this problem by writing a *plugin*. It takes the `import_task_created` event and calls other plugins in a chained way so the output of the first plugin is passed as the input to the second and so on. I've placed it here: https://github.com/mried/beetsplug/blob/NotAgainPlugin/beetsplug/multipletaskcreated.py
Should I add it the basic plugins which are shipped with beets?

**Comment by sampsyo** [comment]
Cool! This is a creative solution. For the moment, let's leave it out-of-tree since it's relatively specialized. We can explore rolling in functionality like this if it becomes a more general use case.

**Comment by mried** [comment]
That's absolutely ok for me. I'll close this issue (and #1495).
