### ISSUE TITLE
Duplicate files not removed when folder name isn't changed

### ISSUE THREAD

**Issue by rjayasin** [sampsyo/beets#1471]
![arctic_monkeys_-_am_2015-05-23_23-46-40](https://cloud.githubusercontent.com/assets/4087768/7786984/776f0382-01a6-11e5-8163-6dd3505aa11f.png)

Upon importing an album in the library directory with the final folder name, all files remain. I'm not entirely sure this is a bug, seeing as I should probably import folders from a different location, but I'm curious to get another opinion.

**Comment by sampsyo** [comment]
Yes, this is intended -- beets will never delete data unless you ask it to. The Getting Started guide has more recommendations about how to set up your directories.
