### ISSUE TITLE
python-mpd is old and crusty, beets should start using python-mpd2

### ISSUE THREAD

**Issue by Somasis** [sampsyo/beets#1472]
Assuming that at some point in time `beets` needs to run on Python 3 (which it does eventually, because Python 2 is being phased out), there will be an issue concerning `python-mpd`; `python-mpd` is not compatible with Python 3, nor is it really even maintained upstream anymore. The [last update was in December of 2010](https://pypi.python.org/pypi/python-mpd/), and it's website is down as well.

[`python-mpd2`](https://github.com/Mic92/python-mpd2), however, is maintained and sees fairly active development. It is a fork of `python-mpd`, and has [a document explaining porting](https://github.com/Mic92/python-mpd2/blob/1c7e8f246465110ccb2d64df829c6dbdcdc74c9e/doc/topics/porting.rst) from `python-mpd` on the repository. Aside from the stickers API, which I'm not even sure `beets` uses, it looks fairly easy to replace.

I think that it would be better to use python-mpd2 for these reasons. Any thoughts?

**Comment by sampsyo** [comment]
Seems like a great idea! And porting should be minimal effort. :sparkles: Would you be interested in flipping the switch and checking that stuff still works?

**Comment by Somasis** [comment]
Certainly. I'll submit a pull req once I'm done.
