### ISSUE TITLE
Query for a path containing whitespace doesn't return anything

### ISSUE THREAD

**Issue by mried** [sampsyo/beets#1491]
After importing some files inside a directory containing spaces, I'm not able to list them using the `path` field.
```
beet ls -f '$path'
/music/Depeche Mode/Sounds of the Universe/01 - In Chains.mp3
/music/Depeche Mode/Sounds of the Universe/10 - Perfect.mp3
...
```
Using the path above to get the same result, leads to no found files.
```
beet ls path:"'/music/Depeche Mode/Sounds Of The Universe'"
```
I also tried several combinations of `"`, `'` and `\ ` to be sure my shell (`bash` on MacOS X) doesn't break it.

What am I doing wrong or is this a bug?

**Comment by sampsyo** [comment]
Weird—this works for me on a path with spaces:

    $ beet ls -p path:"/Users/asampson/Music/Non-Album/Aesop Rock"
    /Users/asampson/Music/Non-Album/Aesop Rock/None Shall Pass.mp3

No need for any additional escaping beyond telling your shell to treat the query as a single argument. I'm not sure what's different here…

**Comment by mried** [comment]
Ehh... After looking at my firs comment again, I have to admit there was a typo in my query :flushed:. I messed up with the case of some letters. Maybe it was a bit late ... :wink:
