### ISSUE TITLE
CLI configuration option (--config) doesnt work on windows?

### ISSUE THREAD

**Issue by Schweinepriester** [sampsyo/beets#1504]
as the title says, it doesnt seem to work on windows (win7, 64bit)?

it just prints the options, as if just `beet` was entered.

i assume i tried every possible combination, but maybe i'm just missing something. please advise how it should work so i can check :)

**Comment by sampsyo** [comment]
Can you please paste exactly what you typed and exactly what beets printed so we can get a better view of what you're trying to do?

**Comment by Schweinepriester** [comment]
partially see Schweinepriester/beets-config#6

as i understand the docs, i should be possible to load an additional config file, right?

<https://beets.readthedocs.org/en/v1.3.13/reference/config.html#command-line-option>

> Alternatively, you can use the ``--config`` command-line option to indicate a
YAML file containing options that will then be merged with your existing
options (from ``BEETSDIR`` or the default locations). This is useful if you
want to keep your configuration mostly the same but modify a few options as a
batch. For example, you might have different strategies for importing files,
each with a different set of importer options.

i'm trying to achive:

have the first config per `BEETSDIR` (set to `E:\beets`)  automatically loaded, containing:

```yaml
directory: F:\Audio\Mediathek\Musik
library: E:\beets\musiclibrary.blb
```

then, use `beet -c PATHTOFILE` or `beet --config=PATHTOFILE`, to load additional options

=> shouldnt all of those:

- `E:\beets\beets-config>beet -c config.yaml`
- `E:\beets\beets-config>beet --config=config.yaml`
- `E:\beets\beets-config>beet --config="E:\beets\beets-config\config.yaml"`
- `E:\beets\beets-config>beet --config=E:\beets\beets-config\config.yaml`

work? instead it echos the help as if i would just call `beet`

i hope this clarifies what i'm trying to achieve :)
if not i'm happy to provide more information

**Comment by sampsyo** [comment]
Yep! You have it right; you just still need to specify what you want to do too.

    $ beet --config foo.yaml list
