### ISSUE TITLE
Error with replaygain gstreamer

### ISSUE THREAD

**Issue by bearcatsandor** [sampsyo/beets#1505]
When trying to import a set of wavpack tracks with replay gain on using gstreamer, i get the following message and then everything just hangs:
(beet:19370): GStreamer-CRITICAL **: gst_pad_set_event_function: assertion 'GST_IS_PAD (pad)' failed

My configuration for that is:
replaygain:
    albumgain: yes
    backend: gstreamer

If i comment out those lines, the error is gone. 

I ran it with verbose on, and i stuck what i got into a pastebin to avoid lots of lines in this error report. That gist is located at https://gist.github.com/953c91f4dfa1b83e290d

I realise that's not much  to go on, but is there anything i can do to help solve this?

**Comment by sampsyo** [comment]
I'm not gstreamer-knowledgable enough to grok that error message, but perhaps someone else will have more insight.

**Comment by lazka** [comment]
This is usually a sign of mixing GStreamer 1.0 and 0.10 (gi vs gst)

**Comment by sampsyo** [comment]
I would believe that. @bearcatsandor, can you confirm that you're using Chroma or BPD or some other GStreamer 0.10 plugin simultaneously with ReplayGain?

**Comment by icedtoast** [comment]
I have the same error message I have both Chroma and replaygain enabled

**Comment by bearcatsandor** [comment]
I do have both .10 and 1.0 installed on my gentoo system. Does beets (git version) require .10 or 1.0 currently?

(sorry for my delay, i lost track of this thread)

**Comment by sampsyo** [comment]
The trouble is that different parts of beets require different version. BPD uses 0.10, Chroma still uses 0.10, but ReplayGain uses 1.0. Using more than one of these simultaneously is known to cause problems; we're working on getting everything up to speed on 1.0

**Comment by bearcatsandor** [comment]
I've installed the gstreamer 0.10 plugins for wavpack and plugins-good (which contains the replay gain sinks) and get the same issues. If you don't want to troubleshoot here that's fine, but if you don't mind, what else might i be missing?

**Comment by sampsyo** [comment]
Just to check again: Do you have both the `chroma` and `replaygain` plugins installed? If so, this is a known issue (and we're working on it). Otherwise, we may need to dig deeper.

**Comment by bearcatsandor** [comment]
Yes i do, unless there is a specific gst chroma plugin for 0.10 installed.

**Comment by sampsyo** [comment]
OK, that explains it. No fix yet, but you can follow along on the work to bring Chroma to Gstreamer 1.0 here: https://github.com/sampsyo/audioread/pull/23

**Comment by bearcatsandor** [comment]
Replaygain with the gstreamer backend seems to be working now. Thanks all!
