### ISSUE TITLE
sys.excepthook error when using beets in bash script

### ISSUE THREAD

**Issue by petwri** [sampsyo/beets#1506]
When I am using beets in a bash script and do a redirection of the input, like

beet import $foo < /dev/tty

I get a sys.excepthook error after the input which is causing the script to hang. I don't know where this error is coming from, is there maybe a workaround to just redirect it?

Btw: beets version is 1.3.13, bash version 4.3.30 on Ubuntu 15.04.

**Comment by petwri** [comment]
I just checked again, it doesn't depend on redirecting the input from tty, the sys hook error keeps coming up:

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

That's where the script is hanging.

**Comment by sampsyo** [comment]
To clarify: this happens every time you invoke beets? Only with the import command? Only in a bash script? *Every* time it appears in a bash script, or only after certain other commands? Or only at the end of a bash script? Does it happen with other shells, or just bash? Can you paste the full script, and how you're invoking it?

**Comment by petwri** [comment]
Thanks for the reply, i'll try asap, so far it only occured with the import command on bash, even in minimal bash scripts.

**Comment by petwri** [comment]
Ok, I tried a simple minimal script, and when using </dev/tty to parse the input from bash to beets, the script hangs after the import. I ran it in beets' debug mode with -v, and the last line I get is "Sending event: cli_exit". The bash script doesn't move on from there. When removing the </dev/tty, beets tells me "error: stdin stream ended while input required" because the input is not being parsed properly. Any ideas?

**Comment by petwri** [comment]
Ok, I just realized that the sys.excepthook error sometimes appears randomly, even when beets seems to have finished a certain command already. I the CLI, a new prompt appears, and out of nowhere, the error is printed. Really hard to reproduce it. All I can say is that beets successfully finished the commands.

**Comment by petwri** [comment]
I gave it another try, just figured out that it doesn't depend on the input parsing, even when I call beets with '/usr/local/bin/beet -c $BEETS_CONFIGFILE -v import -q -P -C -W "$ALBUM"' it doesn't work. The last line printed from the debug log is "Sending event: cli_exit", then the bash script hangs.

**Comment by petwri** [comment]
https://github.com/sampsyo/beets/issues/1507
