### ISSUE TITLE
ls -af produces sys.excepthook error

### ISSUE THREAD

**Issue by petwri** [sampsyo/beets#1507]
Whenever I call "beet ls" with the "-af" option and specify a path, like

beet ls -af '$album' path:/media/Media1/

beets hangs for a while, and then throws out the sys.excepthook error. It works fine with only -a, only -f, as well as some other queries besides a path. Beet version is 1.3.13.

**Comment by sampsyo** [comment]
Thanks for the additional information. This is really strange—needless to say, I can't reproduce the hang and crash here.

Any chance `/media/Media1` is a network filesystem?

**Comment by petwri** [comment]
No, it's not. And it works perfectly fine with a fresh library. Is there any way to check my musiclibrary for db-errors? A cleanup procedure?

**Comment by sampsyo** [comment]
There's no specific DB-cleaning step in beets, but you could try moving your database file aside (it's in `~/.config/beets`) and starting a new one as a test.

Are there any other clues you can give us about unique aspects of your system setup that might be related to the problem?

**Comment by petwri** [comment]
As said, it works fine with a new library. I'm using Ubuntu 15.04 on a headless machine through ssh, although the same error also appears in a screen environment. The drive is a ext4-format usb hdd. What else could help?

**Comment by sampsyo** [comment]
Oops, sorry I missed that.

I don't see anything suspicious in that description. One thing we could try: if you can share your problematic library file, maybe we can try reproducing on other machines (and confirming that it might be a corrupt SQLite database).

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you want to try investigating your library file.
