### ISSUE TITLE
Track numbers are not sorted correctly

### ISSUE THREAD

**Issue by bearcatsandor** [sampsyo/beets#1511]
With the following config parameters in my file:

format_item: $artist - $original_year - $album - $title - $track
sort_item: artist+ original_year+ album+ disc+ track+  

I get "10" immediately after "01"

Iced Earth - 1996 - The Dark Saga - Dark Saga - 01
Iced Earth - 1996 - The Dark Saga - The Suffering: A Question of Heaven - 10
Iced Earth - 1996 - The Dark Saga - I Died for You - 02
Iced Earth - 1996 - The Dark Saga - Violate - 03
Iced Earth - 1996 - The Dark Saga - The Hunter - 04
Iced Earth - 1996 - The Dark Saga - The Last Laugh - 05
Iced Earth - 1996 - The Dark Saga - Depths of Hell - 06
Iced Earth - 1996 - The Dark Saga - Vengeance Is Mine - 07
Iced Earth - 1996 - The Dark Saga - The Suffering: Scarred - 08
Iced Earth - 1996 - The Dark Saga - The Suffering: Slave to the Dark - 09

**Comment by sampsyo** [comment]
Huh, you're right! I can reproduce this even more easily like this:

    $ beet ls -f '$album $track $title' ANY_QUERY track+

I don't know why this is happening but we definitely need to fix it.

**Comment by bearcatsandor** [comment]
Thank you for the confirmation of my findings. I look forward to the fix. You've no idea how irritating it is to use beet play only to hear The Wall in some strange order. :"P

**Comment by tomjaspers** [comment]
For anyone interested in fixing it, it's caused by the numbers being sorted as strings in sqlite, in which case `['01', '10', '02']` makes sense. 

In `FixedFieldSort` the field needs to be casted as integer. E.g., `field = "CAST ({} AS INTEGER)".format(field)` would fix the track numbers (but of course break other sorts).

This should be generalized to cast all the fields to their type, as it probably is causing more problems.

**Comment by sampsyo** [comment]
Looks like this is coming from the case-insensitive sort option (#1429). We're using `ORDER BY LOWER(track)` in our SQL, which is implicitly converting the track number (which is stored as an integer) to a string before sorting. Everything works fine if you turn off case-insensitivity. Bad bad bad!

As @tomjaspers notes, this should probably depend on the field's type. Or if we can nail some kind of workaround that only enables case-insensitivity when comparing strings in SQLite, while not impacting other types, then we can dodge the issue for now.

**Comment by sampsyo** [comment]
I don't see any obvious workaround, so maybe the right solution is exactly as @tomjaspers proposes: an extra field on `dbcore.Type` that indicates whether case-insensitivity makes sense for the type (i.e., it's string-like). Then we need to make sorts aware of which type of field they're sorting.

**Comment by tomjaspers** [comment]
@sampsyo Thankfully there was an easier fix using the `CASE WHEN...` construct in SQL. The values are now only `LOWER()`'d when the columns are *text* or *blob*. The latter is needed for the paths.

I've added tests and docs, so it should be good now.

**Comment by sampsyo** [comment]
Fantastic; thanks for finding that trick, @tomjaspers.
