### ISSUE TITLE
Cannot load Discogs Plugin

### ISSUE THREAD

**Issue by tommueller** [sampsyo/beets#1517]
Hi,

just installed the Discogs Plugin on Linux Mint 17. When I start beets now I get this:

** error loading plugin discogs
Traceback (most recent call last):
  File "/usr/share/beets/beets/plugins.py", line 191, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/share/beets/beetsplug/discogs.py", line 20, in <module>
    from discogs_client import DiscogsAPIError, Release, Search
ImportError: cannot import name DiscogsAPIError

Any Ideas?

Thanks!
noise

**Comment by sampsyo** [comment]
Can we get a little more detail? Especially:

* Which version of beets?
* Have you tried the latest beets source from git?
* Which version of `discogs_client`?

**Comment by tommueller** [comment]
Well tried to find out the version of discogs_client and for whatever reason its working now ... thanks I guess ... :)

**Comment by sampsyo** [comment]
Great!
