### ISSUE TITLE
Query Regex: Not recognized as an internal/external command

### ISSUE THREAD

**Issue by klreeher** [sampsyo/beets#1520]
Am attempting to use regex in a query, and when I use the doc's example, I get the following:

    >> beet list 'artist::Ann(a|ie)'
    'ie)'' is not recognized as an internal or external command,
    operable program or batch file.

beets version 1.3.13, with duplicates, fetchart, fromfilename 
python 2.7.9

**Comment by sampsyo** [comment]
Hmm, it looks like your shell is interpreting those parentheses as special instructions. Are you on Windows?

If so, can you try double quotes, or escaping the parentheses with backslashes?

**Comment by klreeher** [comment]
Sadly, I am on windows, and yep, that was the issue. Used " instead of ', and it worked.

**Comment by sampsyo** [comment]
Awesome; thanks for checking that out. I'll make a note to amend the documentation.
