### ISSUE TITLE
Unable to install on Ubuntu 14.04... not compatible with PyYAML 3.10?

### ISSUE THREAD

**Issue by dowcet** [sampsyo/beets#1526]
I just installed beets via pip in Ubuntu 14.04. When I run `beet` I get the following traceback:

    File "/usr/local/bin/beet", line 9, in <module>
      load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
    File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1104, in main
      _raw_main(args)
    File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1090, in _raw_main
      subcommands, plugins, lib = _setup(options, lib)
    File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 972, in _setup
      from beets.ui.commands import default_commands
    File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 32, in <module>
      from beets import importer
    File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 47, in <module>
      'ALBUMS'])
    File "/usr/lib/python2.7/dist-packages/enum.py", line 197, in __init__
      raise EnumBadKeyError(key)
    enum.EnumBadKeyError: Enumeration keys must be strings: [u'SKIP', u'ASIS', u'TRACKS', u'MANUAL', u'APPLY', u'MANUAL_ID', u'ALBUMS']

It also looks like cannot upgrade PyYAML from 3.10 to 3.11 via pip (at least not without removing a bunch of other packages on my system). Could that be the source of the problem?

**Comment by sampsyo** [comment]
You seem to have the wrong `enum` package installed, somehow—you need the one packaged as `enum34`, not `enum`. An ordinary `pip install beets` should get the right one.

**Comment by dowcet** [comment]
I see the following folder on my system: `/usr/local/lib/python2.7/dist-packages/enum34-1.0.4.egg-info`.

If I run `pip install beets` again right now, I get the following:

```
Requirement already satisfied (use --upgrade to upgrade): beets in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.27 in /usr/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): munkres in /usr/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): unidecode in /usr/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): musicbrainzngs>=0.4 in /usr/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/dist-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): jellyfish in /usr/local/lib/python2.7/dist-packages (from beets)
```

Not sure if any of that info helps, but I have no idea what to do next.

**Comment by hannespetur** [comment]
You have two packages named enum, and python is resolving enum to `/usr/lib/python2.7/dist-packages/enum.py` instead of `/usr/local/lib/python2.7/dist-packages/enum/`. The easiest way to fix this is to remove the `/usr/lib/python2.7/dist-packages/enum.py` file, but keep in mind that could break other modules depending on it. If you'd rather not remove it you can also use virtual envs.

**Comment by dowcet** [comment]
OK, I installed `virtualenv` and it looks like beets is working fine with that, thanks.
