### ISSUE TITLE
multiple self-titled albums for a single artist

### ISSUE THREAD

**Issue by bearcatsandor** [sampsyo/beets#1527]
Beets version: Git
I have the first few albums by Days of the New.  They are all self-titled as follows:
1997 - Days of the New
1999 - Days of the New
2001 - Days of the New

Beets does pull them correctly from musicbrainz with the proper IDs, but when you pull the second one into the collection it treats the first one as a duplicate, and when you pull the third one in it treats the second one as a duplicate.

I'd imagine Peter Gabriel fans have this problem as well.

What can i do to solve this? I have:
default: %lower{%the{$albumartist}/$original_year-$album%aunique{}/$disc-$track-$title}
comp: %lower{compilations/$original_year-$album%aunique{}/$disc-%the{$artist}-$track-$title}
singleton: %lower{singletons/%the{$artist}-$title}
as my path, but that would only effect file names not the db, but why are they seen as dupes if the albumdisambig is being taken into account?

The albumdisambig are there when i do an info
   albumartist_sort: Days of the New
    albumdisambig: Green Album

**Comment by sampsyo** [comment]
The duplicate detector in the importer is currently not configurable: it just finds identical artist and album names. (It's totally separate from the path configuration and the disambiguation functionality.) #1133 proposes to fix this.
