### ISSUE TITLE
import --quiet should write a file that can be user edited and reimported

### ISSUE THREAD

**Issue by hrehfeld** [sampsyo/beets#1538]
It would be awesome if we could run

     $ beet import --quiet

which then writes a file similar to a temporary commit message file. It would contain the interactive prompt:

    # lines starting with # will be ignored
	# (32 items)
    # Tagging:
    #     Dead Brothers - Dead Music for Dead People
    # URL:
    #     http://musicbrainz.org/release/c775bc5b-26d9-4da6-8b3b-b464040d3147
    # (Similarity: 83.0%) (unmatched tracks) (CD, 2000, CH, Voodoo Rhythm Records)
    # Unmatched tracks (16):
    #  ! Dead Brothers Stomp (#1) (3:02)
    #  ! I've Always Known (#2) (2:04)
    #  ! Farmer Boy (#3) (2:42)
    #  ! Besame Mucho (#4) (2:14)
    #  ! Roger (#5) (0:54)
    #  ! She Collects Postcards (#6) (5:03)
    #  ! Banjo Villa Against Tarass Boulba (#7) (0:51)
    #  ! Crying (#8) (4:38)
    #  ! Hora (#9) (2:46)
    #  ! Allons Aux Paquis! (#10) (2:11)
    #  ! Somewhere Between Dog & Wolf (#11) (2:58)
    #  ! Buy It! (#12) (1:11)
    #  ! Good Time Religion (#13) (5:04)
    #  ! Orally (#14) (1:01)
    #  ! Ramblin' Man (#15) (3:57)
    #  ! [untitled] (#16) (1:08)
    # (A)pply, [S]kip, (U)se as-is, as (T)racks, (G)roup albums, Requery (i)nteractively
    # Enter search, enter Id, aBort? 
    /music/beets_/ Dead Music for Dead People - Voodoo Rhythm Records - c775bc5b
	<optional temporary uuid here>

I would then put a character with whatever choice I decide on:

    # Enter search, enter Id, aBort? 
    /music/beets_/ Dead Music for Dead People - Voodoo Rhythm Records - c775bc5b
    <optional temporary uuid here>
    a

and the next item would follow.

Then i could call

    $ beet import --file

and beets would apply my choices.

This would help with the dreadful importing stage. (I am importing my library since... a few days ago, and it's still going on)

**Comment by sampsyo** [comment]
Thanks for the suggestion! Can you please add your thoughts to #1375, which describes approximately the same machinery (minus the text-file-editing interface)?
