### ISSUE TITLE
beets import "unable to read full data"

### ISSUE THREAD

**Issue by knightofni** [sampsyo/beets#1540]
I've installed beets on an ubuntu box. It works fine (including playing music form the web interface), however when running import, i run into the following message :

```
beet import /mnt/bucket/MedievalMusic/
```
(after selecting Apply)
```
error writing /mnt/bucket/MedievalMusic/Celtic/Celtic Music - Wolf Blood.ogg: unable to read full data
```
I thought it might be a permission problem, so I've changed the permissions to allow everything (`chmod -R 777 MedievalMusic`), and it hasn't solved the problem.

What is the meaning of `unable to read full data`, and how can i avoid it ?

Notes : 
1. i'm quite new to the linux world, so i may have missed something obvious)
2. `/mnt/bucket/` is an s3 bucket mounted thanks to https://github.com/s3fs-fuse/s3fs-fuse

**Comment by sampsyo** [comment]
Sounds like you might have a broken audio file. Can you check that it works with other software? And, if so, share the file so we can take a look?

**Comment by knightofni** [comment]
@sampsyo Yes, it's most likely a file problem, as yesterday i was able to tag some files from another source.

I've sent you a link to the file by email (adrian@radbox.org)

It plays fine on my local machine (OSX : Vox Player or VLC). Maybe some corrupted headers ?

**Comment by sampsyo** [comment]
Strangely, I was able to import and modify that file just fine. I'm not sure why you're seeing an error—is it still going on if you try manipulating the same file you sent me once again?

**Comment by knightofni** [comment]
Ok, that file now works. Other files that used to not work, now work. 
Some others still don't.

Theory : I'm playing the files through Plex server. After Plex plays the file, it sort "repairs" them. Going to check that.

**Comment by LordSputnik** [comment]
If you're comfortable typing some Python code, it might be worth trying to load these not-working files with mutagen to see if it raises any exceptions when accessing/modifying metadata.

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if the problem arises again so we can try to reproduce it.
