### ISSUE TITLE
No way to disable "Various Artists"?

### ISSUE THREAD

**Issue by yam655** [sampsyo/beets#1566]
I never use "Various Artists". It makes more sense to treat compilation albums the same way people treat short-story anthologies: The editor is used for the artist's name. This means that if Goodrich or Target or ALDI releases a Christmas album containing music by various artists, I use the Album Artist of "Goodrich" or "Target" or "ALDI". Disambiguation of a "Christmas *{YEAR}*" album happens automatically because I use all of the available metadata.

This allows me to keep my hundreds of Song Fight! <http://songfight.org/> albums separate from, say, my Spin Tunes <http://spintunes.blogspot.com/> albums, or the various collections released by labels on NetLabel Day <http://netlabelday.blogspot.com/p/releases-2015.html>.

Sure, they're all by "various" artists, but they're released by totally different groups, and the groups that release them actually matter to me.

At first I thought this would be easy. I saw in the default configuration where the paths explicitly included "Various Artists" if it was a compilation. So, I did the logical thing and made the "comp" entry exactly the same as my "default" entry before I imported any tracks.

I didn't actually clean up my tags before I began. I imported an album before I realized it didn't have an album artist. My sample data is freely available: <https://archive.org/details/07LOGOSAMPHIAWithTheBranFlakesInidadbodja>

(That's the only album in my Beets database right now. This means I can do things like "beet info 9" and get a single track.)

So I fixed "albumartist" and tried to "beet mv" the album to the correct location. It remained in "Various_Artists".

So I changed "comp" to "False" and tried to "beet mv" the album to the correct location. It remained in "Various_Artists".

It looks like beets/importer.py guesses whether an album is "Various Artists" and then overrides the album artist -- even when importing "as-is" and the album had an existing album artist.

More than that, it looks like there's special behavior that varies specifically when the albumartist is "Various Artists" (ignoring the -- still useful -- "comp" flag). In addition to failing my use-case, that makes things less clear for folks interested in localizing. (I figure you're taking care of this in the localized spellings of artists, however the code would be clearer if you just used the "comp" flag.) This appears to take place in "beets/ui/command.py" as well as "beetsplug/lastgenre/__init__.py"

I understand that the importer overrides things, but right now, "beet info" reports the correct albumartist and reports "comp: False" and yet "beet mv" still puts it in that silly "Various_Artists" folder.

**Comment by sampsyo** [comment]
The "Various Artists" string comes from MusicBrainz. More here: https://musicbrainz.org/doc/Style/Unknown_and_untitled/Special_purpose_artist

> It looks like beets/importer.py guesses whether an album is "Various Artists" and then overrides the album artist -- even when importing "as-is" and the album had an existing album artist.

True. This is used to fix up situations where people don't have album artists set, which can lead to unexpected behavior.

You probably want to use `beet modify -a albumartist=...`. (Remember the `-a` flag to update the album instead of the tracks.) Does that do what you want?

**Comment by yam655** [comment]
Interesting. Since I only had one album, it's possible that I thought simply changing the albumartist on all of the tracks was enough. I didn't think to try the "-a" flag.

"beet info" doesn't take a "-a" command. Does that mean there's some metadata that's hard to view?

In that particular case, I manually set all the flags -- including the Album Artist flag. I added the album to MusicBrainz after fixing the metadata, but wanted to work with the version that hadn't been imported so that didn't have to worry about adding non-canonical data to MusicBrainz. When I re-imported my music it was in the correct folder.

So, when the album is imported with an albumartist things seem to work correctly. 

I think you can close this as user-error, though it's possible this should be documented somewhere.

**Comment by sampsyo** [comment]
Cool.

> "beet info" doesn't take a "-a" command. Does that mean there's some metadata that's hard to view?

FWIW, the usual way is to use the `list` command:
$ beet ls -a '$albumartist'
