### ISSUE TITLE
Import crashes with gst error

### ISSUE THREAD

**Issue by bearcatsandor** [sampsyo/beets#1567]
This may not be a beets error at all, but this just started happening after a git update today (at commit 4038f191da3d62f603aca8f12b5949d6e16c10ed). It happens with anything that i try to import.

```
beet import -I ./               

/home/hometheater/audio/carpenters/2000-gold__greatest_hits_[xrcd2_remastered] (20 items)
Tagging:
    Carpenters - Gold: Greatest Hits
URL:
    http://musicbrainz.org/release/dfea5aef-21ac-44e5-ad20-5bacb9bac6fe
(Similarity: 99.1%) (media) (CD, 2000, JP, A&M Records, Inc., XRCD2 remastered)
 * Yesterday Once More
 * Superstar
 * Rainy Days and Mondays
 * Goodbye to Love
 * It's Going to Take Some Time
 * I Won't Last a Day Without You
 * For All We Know
 * Jambalaya (On the Bayou)
 * Touch Me When We're Dancing
 * Please Mr. Postman
 * I Need to Be in Love
 * Solitaire
 * We've Only Just Begun
 * (They Long to Be) Close to You
 * This Masquerade
 * Ticket to Ride
 * Top of the World
 * Only Yesterday
 * Sing
 * Calling Occupants of Interplanetary Craft (The Recognized Anthem of World Contact Day)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? A
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: timed out
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
echonest: IO error: Echo Nest Unknown Error
sys:1: Warning: cannot register existing type 'GstObject'
sys:1: Warning: g_once_init_leave: assertion 'result != 0' failed
sys:1: Warning: g_type_register_static: assertion 'parent_type > 0' failed

(beet:23247): GStreamer-CRITICAL **: gst_pad_set_event_function: assertion 'GST_IS_PAD (pad)' failed
```

It just sits there like that for an hour till i break it with cntrl-c
After terminating it, if it do a beet ls artist:carpenters that album pops up, but the files have not been moved into the directory.
If i then do a 'beet remove' on that query, removing those items from the database, doing a 'beets import' on those files gives me "No files imported from /home/hometheater/audio/carpenters/2000-gold__greatest_hits_[xrcd2_remastered]  Skipped 1 paths." 

i have to use the -I switch to try again.

Did the gstreamer requirements change recently?

**Comment by sampsyo** [comment]
As of the most recent `audioread`, the `chroma` plugin now uses GStreamer 1.x (instead of 0.10). Could that have caused any havoc?

**Comment by bearcatsandor** [comment]
I have both gst .10 and gst 1.0 installed. My version of chromaprint is 1.2. Is that too old?

**Comment by sampsyo** [comment]
You could try temporarily uninstalling 0.10 (and making sure audioread and pyacoustid are up to date).

**Comment by lazka** [comment]
I'd recommend to use something like this in beets so no old bindings can get loaded by accident.

```
    import sys
    sys.modules["gtk"] = None
    sys.modules["glib"] = None
    sys.modules["gst"] = None
    sys.modules["gobject"] = None
    sys.modules["gnome"] = None
```

**Comment by jrobeson** [comment]
shouldn't `gi.require_version()` be enough?

**Comment by lazka** [comment]
> shouldn't gi.require_version() be enough? like
gi.require_version('Gst', '1.0')

0.10 wasn't using gobject introspection so this wont help.

**Comment by jrobeson** [comment]
so I'm confused as to what would trigger the loading of the old libraries in the first place if nothing calls them?

**Comment by sampsyo** [comment]
I think we can safely blame conflicting GStreamer versions---this should be fixed (except for `bpd`!) as of the latest `audioread`.
