### ISSUE TITLE
Empty metadata: Additional check for empty artist and album metadata

### ISSUE THREAD

**Issue by knutshub** [sampsyo/beets#1575]
During the import of a lot of albums that are not in musicbrains, I'm using the function 'Use as-is'. But sometimes I have files that do not have artist and album information. In this cases beets point to the same folder and I can only choose 'Skip' this or 'Remove' the other files. 

It would be nice to an intermediate step, that gives the option to 'Enter search' as previously, or 'Enter artist and album name manually' to avoid the case of overwriting the folder with no empty name.

This gives the user two opportunities: first, to restart the search with different data or second to create an own folder manually.

PS: I searched for similar topics, but couldn't find one.

**Comment by fxthomas** [comment]
Did you try using the "As [T]racks" option? This lets you process each file individually in a given folder.

**Comment by sampsyo** [comment]
Yes, manually entry would be useful. #396 outlines a general idea, which I think covers this use case. Could you please add your thoughts there about perhaps automatically suggesting manual entry if metadata is missing?

**Comment by knutshub** [comment]
@fxthomas I never tried this option. But I will.
@sampsyo Sorry, I didn't saw that issue before. Thanks!
