### ISSUE TITLE
Mark albums that are missing in musicbrainz

### ISSUE THREAD

**Issue by knutshub** [sampsyo/beets#1576]
After importing a lot of albums, I realized that it would be a nice feature to mark albums that can't be found on musicbrainz, because no one added them.

Afterwords, the user can go through this list and add the albums manually in musicbrainz that they can be found by other user.

I don't have a good solution for this yet:
maybe a parameter, that creates an .txt file with the folder names of the albums that are missing or in the path (eg. $unknown -> create a * (star) somewhere in the path, if the album is missing).

**Comment by claman** [comment]
I really like this idea.

**Comment by fxthomas** [comment]
If you can make sure that the only albums that don't have MusicBrainz tags are _really_ not in the MB database, then you can list all albums with no MB info :

    beet ls -a 'mb_albumid::^$'

Does this correspond with what you had in mind?

**Comment by sampsyo** [comment]
I endorse @fxthomas's suggestion. :smiley: There's also the import log, which can write to a text file any time you choose "use as-is," a good indication that you didn't find what you were looking for. Do those two strategies cover what you're looking for?

**Comment by knutshub** [comment]
Thanks you both for your suggestions!

@fxthomas The command looks good. It solves my problem. I didn't know that.
@sampsyo I haven't used the import log yet. But I will check it out.
