### ISSUE TITLE
convert: transcode files from playlist

### ISSUE THREAD

**Issue by nininhocovre** [sampsyo/beets#1580]
I have a playlist of my favorites songs and wanted to convert them for playing in my car.

The songs comes from multiple albums, so creating a query to list then would not be possible.
Is it possible to use a playlist instead of query on convert command?

Thanks

**Comment by sampsyo** [comment]
It's not possible to use a playlist file (e.g., an .m3u) directly, but you can use beets' "or" operator in queries to specify the set of songs from any album you want to transcode: http://docs.beets.io/en/v1.3.14/reference/query.html#combining-keywords
