### ISSUE TITLE
Case insensitive search for a file does not work

### ISSUE THREAD

**Issue by mried** [sampsyo/beets#1587]
Imagine you have a file at `/path/to/library/A/File.mp3`. Executing `beet ls -f $path` will give us
```
/path/to/library/A/File.mp3
```
So I would expect to get a result when executing `beet ls path:"/path/to/library/A/File.mp3"`, but beets doesn't find the file.

I tried to find the bug but didn't succeed. One thing I noted is the where clause of the `PathQuery` (line 103 of `library.py`): The bound parameter is in lower case but the data at the database might contain upper case letters. Therefore, a check like `path = ?` might fail even if it shouldn't. So I changed it to `lower(path) = ?` but that didn't change the described behavior.

What am I doing wrong?

**Comment by sampsyo** [comment]
That's odd—I can't reproduce this on either of my main systems (one OS X, one Arch Linux). Typing `beet ls path:` and the path to a file works fine. My OS X disk is case-insensitive and the Linux filesystem is of course case-sensitive.

Any idea what might be different about your system?

**Comment by nathdwek** [comment]
I can attest that sometimes it seemed to me that `beet ls path:<path>` would behave weirdly, but I always thought  the problem was that I did not enter the path correctly from a bash point of view (protecting with quotes, escaping characters, etc). So every time it happened, I end up changing the syntax a bunch of times and it ends up working eventually (and often surprisingly). But again, I always thought this was coming from me not being able to remember the syntax accurately when it comes to long files with a lot of unicode gibberish.

Maybe I'll try to reproduce this and then see if something pops up.

**Comment by pkess** [comment]
I also tried to reproduced it, but without success.

To avoid any problems with escaping characters, quotes, etc.: Should we introduced an output option to the ls command which will print the query at first and then prints the results (and a summary maybe)

```
beet ls path:"/path/to/library/A/File.mp3"
```
could give an output like
```
Searching for:
path:"/path/to/library/A/File.mp3"

Results:
Beatles - Let it be - Let it be

Summary:
Found 1 track
```

What do you think?

**Comment by sampsyo** [comment]
Some additional debugging output might serve this role well too.

**Comment by nathdwek** [comment]
I think it could be a useful debug info to have but that it indeed wouldn't belong to every day output.

**Comment by mried** [comment]
After digging a bit more into the code I found something which might help to understand what's going on here. I guess the root of the problem is the type of the `path`-column at the database: It's a BLOB. Using a BLOB column within a where clause can be tricky sometimes.
I've changed the where clause from
```
({0} = ?) || ({0} LIKE ? ESCAPE ?)
```
to
```
(lower({0}) = lower(?)) || (lower({0}) LIKE lower(?) ESCAPE ?)
``` 
and now it seems to work for me. But I'm really unsure if this is the right solution.

Any comments?

**Comment by sampsyo** [comment]
Aha! I think so! In the case-insensitive case (sorry), the pattern is lower-cased: https://github.com/sampsyo/beets/blob/master/beets/library.py#L71

So checking equality as in `{0} = ?` isn't right; we also need to lower-case the value from the database.

Does just changing it to this work?

    (lower({0}) = ?) || ({0} LIKE ? ESCAPE ?)

That is, the pattern is already lower-cased, so no need for `lower(?)`. And LIKE is already case-insensitive, so leave that alone. I think we just need `lower` on the value in the equality.

**Comment by mried** [comment]
No, that doesn't do the trick. But you are right with the `LIKE` part of the where clause: we don't need the `lower` there. So the following works perfect for me (at least with the test cases I've got here...):
```
(lower({0}) = lower(?)) || ({0} LIKE ? ESCAPE ?)
```
But I'm still not sure why we have to do a `lower` for the parameter since the string is already in lower case. Maybe Python and SQLite create something different when using `lower`?

**Comment by sampsyo** [comment]
Good thinking. Do you think you might be able to use print-debugging to track down a case where Python's `path.lower()` doesn't match SQLite's `lower(path)`? Then we can really nail this bug.

In any case, if there really is a difference, then perhaps we should keep `LOWER({0}) = LOWER(?)` in that query and then *remove* the lower-casing on the Python side.

**Comment by mried** [comment]
I did as you suggested: Selected `lower(path)` and used `path.lower()` in Python and printed the byte representation of each character. They are both absolutely identical.

Removing the lower-casing on the Python side seems to have no effect, hence everything is still working perfectly. I'll prepare a PR containing these changes.
