### ISSUE TITLE
fetchart: Reconcile file types with embedart

### ISSUE THREAD

**Issue by Kolbasz12** [sampsyo/beets#1588]
Is there a way to make the fetchart plugin ignore image formats that are not supported or convert them from not supported formats to ones that are supported?

I have some files I was updating, fetching and embedding art.  For the most part it just ran, but every time it hit a gif image, it threw an error.  fetchart pulled the gifs during import, so if there was a way to make it ignore gifs on import or convert them, this would avoid the error.

Specifically:

embedart: not embedding image of unsupported type: image/gif

**Comment by sampsyo** [comment]
Thanks for reporting. We do filter on type but, weirdly, the plugins disagree on their whitelist:
https://github.com/sampsyo/beets/blob/master/beetsplug/fetchart.py#L41
https://github.com/sampsyo/beets/blob/master/beets/art.py#L76

MediaFile says PNG, not GIF:
https://github.com/sampsyo/beets/blob/master/beets/mediafile.py#L664

Investigating.

**Comment by Kolbasz12** [comment]
as a note, I did a test with one of the albums where I saw the error.

I did a fetchart -f, it pulled new art, i then ran embed art and it said it is not embedding because the art already is embedded...

or, does fetch art also embed it?

**Comment by sampsyo** [comment]
`fetchart -f` only forces fetching; it does not re-embed. (For that, you'll need to run the `embedart` command.)

**Comment by Kolbasz12** [comment]
ok, thats what I thought, so it is interesting that before it said not embedding gif, but when I force pull a new image it does not embed because it already has art.  I will check the file to see what it has later tongiht
