### ISSUE TITLE
Allow delete on duplicate skip

### ISSUE THREAD

**Issue by Kolbasz12** [sampsyo/beets#1590]
I want to request a feature/enhancement. 

Currently for duplicate files/albums,  we can keep both,  remove and skip.  This is OK for a handful of albums ,  but when importing lots,  it stinks. Manually going back,  finding and deleting the folders. 

As with the remove old option,  how hard would it be to add a remove new?  I mean I can still skip if I want,  but being able to just delete as well would be awesome.

**Comment by sampsyo** [comment]
Good idea: please see #1064.
