### ISSUE TITLE
mp3gain no longer in certain distributions, python-rgain is an better alternative

### ISSUE THREAD

**Issue by DjSlash** [sampsyo/beets#1597]
mp3gain is no longer available on [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761847) and [Ubuntu 15.04](https://answers.launchpad.net/ubuntu/+source/mp3gain/+question/264529). Not checked other distro's, but I guess other Debian/Ubuntu-derivatives will follow.

The software itself seems also no longer to be maintained, when I look at it's [website](http://mp3gain.sourceforge.net/).

I have stumbled upon something else: [rgain](https://bitbucket.org/fk/rgain/), a python library which is included in Debian&Ubuntu, namely as [python-rgain](https://packages.debian.org/jessie/python-rgain).

**Comment by sampsyo** [comment]
Yeah, it's a shame that project is unmaintained, but fortunately the plugin has several other backends:
* GStreamer
* PyAudioTools
* bs1770gain

And `rgain` is actually a wrapper for GStreamer's RG analysis, which we use directly.

**Comment by Bercio** [comment]
What do you mean with "the plugin has several other backends"? Is mp3gain not needed to run the plugin ? I'm asking 'cause I've gstreamer installed but beets still asks for mp3gain to be installed

**Comment by sampsyo** [comment]
Yes, but you'll need to configure it. Please read the docs. http://docs.beets.io/en/v1.3.15/plugins/replaygain.html
