### ISSUE TITLE
Rehoming an existing database?

### ISSUE THREAD

**Issue by howardjones** [sampsyo/beets#1598]
I've just moved all my music onto a new NAS, including the beets database directory. Everything is in the same relative structure, but the base path is different. Now when I import, I get errors like this:

    This album is already in the library!
    could not get filesize: [Error 2] The system cannot find the file specified: u'\\\\\\/mnt/music/Cleaned/SingleArtist/Andy Stott/Andy Stott - Faith in Strangers [2014]/01 Andy Stott - Time Away.mp3'

(/mnt/music is the old NAS' music share, vs /volume1/Music on the new one)

That's not very surprising, but is there are way to have beets rewrite all the paths? Even better, is there a way to just keep the relative paths in the database? I have this share mounted as different paths on different PCs (e.g. a drive letter on Windows, but a directory mountpoint on Linux) so the full path will never be correct on *something*. I can see that I'd have to promise that all files fall within the base path, but it would improve the portability.

**Comment by nathdwek** [comment]
You are looking for [`beet move`](https://beets.readthedocs.org/en/v1.3.14/reference/cli.html?highlight=move#move).

I would recommend `beet move -dc` and possibly first a dry run with `-p`.

However, in order to be able to move the files, beets has to be able to find them first (Even if you just want to modify the paths in the db); so you should probably move back to your old setup first if possible.

If that's not possible, there should be a way to do some magic with `beet modify` and some string substitution.

**Comment by howardjones** [comment]
Moving back isn't an option... I think I'll just re-import the already-clean data then, if the only option is to move/copy the files anyway. I can fix up a few albums where the 'bonus disk 2' didn't get picked up at the same time.

I was hoping to be able to do something like 
    beet modify path:/mnt/music path=~ s/\/mnt\/music/\/volume1\/Music/
(to inject a little perlism)

I don't have any custom fields or tags though, so it should be a case of a (long-running) beet import -q

**Comment by sampsyo** [comment]
@nathdwek has the "recommended method" right. In your situation, though, you might consider a non-autotagged import (-A) to quickly reconstruct the database based on the tags on the files.

**Comment by jdheyburn** [comment]
Apologies for coming back to an old thread but for me, copying from local from one device to NFS stored on another was easier to modify the DB using SQL as opposed to doing numerous moves.

```sql
UPDATE items
SET "path" = CAST(REPLACE(CAST("path" AS TEXT),'/path/old', '/path/new') AS BLOB)
 where artist = "Khruangbin";
```

You will also need to update attribute `artpath` in table `albums` using the same method above too. Commands taken from [this source](https://sqlitetoolsforrootsmagic.com/search-replace/).

**Please back up your db file before running these commands.**

**Comment by phirestalker** [comment]
> Apologies for coming back to an old thread but for me, copying from local from one device to NFS stored on another was easier to modify the DB using SQL as opposed to doing numerous moves.
> 
> ```sql
> UPDATE items
> SET "path" = CAST(REPLACE(CAST("path" AS TEXT),'/path/old', '/path/new') AS BLOB)
>  where artist = "Khruangbin";
> ```
> 
> You will also need to update attribute `artpath` in table `albums` using the same method above too. Commands taken from [this source](https://sqlitetoolsforrootsmagic.com/search-replace/).
> 
> **Please back up your db file before running these commands.**

Thanks a bunch, saved my bacon!!
