### ISSUE TITLE
beets-play: Cleanup code doesn't run in `play_music()`.

### ISSUE THREAD

**Issue by nathdwek** [sampsyo/beets#1600]
The `play_music()` function in beets-play calls `interactive_open()`, which ends python execution rather then forking a new process. For this reason, cleanup code responsible of the deletion of the temporary playlist after the invocation of the player doesn't actually run.

>We have two options:
>* Make the `play` plugin use a different spawning mechanism (leaving `interactive_open` for `config -e` >and the like).
>* Add an optional flag for `interactive_open` to avoid `exec`ing in place.

**Comment by nathdwek** [comment]
Any opinions?

**Comment by sampsyo** [comment]
My opinion is: :+1: :exclamation: 

I don't immediately have a preference for one road or the other, but I do think we should choose one of them. :smiley:

**Comment by nathdwek** [comment]
I finally started to implement what I thought was gonna be a quick fix. However, it turns out that simply forking does not work as expected because there are race conditions between the third party command opening the playlist and the python execution which deletes the playlist.

I think the best we could do without introducing an arbitrary wait time between the creation of the playlist and its deletion, which really seems like bad monkeypatching to me, would be to simply wait for the command to return to delete the playlist (or wait for an execution to be raised to pass it through). However, that means that python threads pile up each time you do `beet play [query]` which feeds songs to the same instance of a player (which is my use-case); and that seems really bad to me.

Or, we could just not delete the temporary playlist (they are in `/tmp` after all, and only a few kB each), and stick with pure forking to handle exception or further logging.

Opinions? This is getting a bit more tricky suddenly :cry:

**Comment by sampsyo** [comment]
Ugh! You're right; this is a bit more complicated than I originally imagined.

Here's one silly idea: when starting `play`, remove the playlist from the last execution. That way, we'll only leak one file at most—at the slight cost of a potential race if someone invokes `play` twice really quickly.

**Comment by nathdwek** [comment]
Fixed in #1785 .
