### ISSUE TITLE
`not` operator for query

### ISSUE THREAD

**Issue by Profpatsch** [sampsyo/beets#1604]
There should be a not operator for queries (or it should be documented).

Example: I want to find all album by artist Evanescence, but not their album “Evanescence”:

    beet list "artist:evanescence -album:evanescence"

or maybe

    beet list "artist:evanescence not album:evanescence"

The second one doesn’t really show how far it binds (e.g. is it `(not one) two` or `(not one two)`), though.

**Comment by sampsyo** [comment]
Yes, we should indeed! See #819. And thanks for the ideas about syntax.

**Comment by Profpatsch** [comment]
Example: I want to find all album by artist Evanescence, but not their album “Evanescence”:

    beet list "artist:evanescence -album:evanescence"

or maybe

    beet list "artist:evanescence not album:evanescence"
