### ISSUE TITLE
fetchart plugin documentation for itunes store is out of date

### ISSUE THREAD

**Issue by bengadbois** [sampsyo/beets#1610]
https://github.com/sampsyo/beets/blob/master/docs/plugins/fetchart.rst#itunes-store

```
$ pip install python-itunes
Collecting python-itunes
  Could not find a version that satisfies the requirement python-itunes (from versions: )
No matching distribution found for python-itunes
```

You cannot ```pip install python-itunes``` anymore

Edit: appears to be a pip bug in recent versions, but the following works: ```https://pypi.python.org/packages/source/p/python-itunes/python-itunes.tar.gz ```

**Comment by bengadbois** [comment]
```
$ pip install python-itunes
Collecting python-itunes
  Could not find a version that satisfies the requirement python-itunes (from versions: )
No matching distribution found for python-itunes
```
Perhaps this is a pip bug...?

**Comment by Somasis** [comment]
That sounds more like an issue with `python-itunes` being python2 only.

```
somasis@cicero:~/ % pip --version
pip 7.1.2 from /usr/x86_64-pc-linux-gnu/lib/python3.4/site-packages (python 3.4)
somasis@cicero:~/ % pip2 --version
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
somasis@cicero:~/ % pip show python-itunes
somasis@cicero:~/ % pip2 show python-itunes
---
Metadata-Version: 1.0
Name: python-itunes
Version: 1.0
Summary: A simple python wrapper to access iTunes Store API
Home-page: https://github.com/ocelma/python-itunes
Author: Oscar Celma
Author-email: ocelma@bmat.com
License: http://www.gnu.org/copyleft/gpl.html
Location: /usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages
Requires:
```

**Comment by sampsyo** [comment]
Weirdly; I'm having the same trouble:

	$ pip2 install --user python-itunes11:11:43PM jasmine:~
	Collecting python-itunes
	  Could not find a version that satisfies the requirement python-itunes (from versions: )
	No matching distribution found for python-itunes

I'm actually not sure what that means. Any insight?

**Comment by jackwilsdon** [comment]
It seems to be a known problem with python-itunes. Check out ocelma/python-itunes#9 for a bit more information. Currently you can do this to install python-itunes: `pip install -e git+https://github.com/ocelma/python-itunes.git#egg=itunes` (as suggested by @caxap), however it does feel a bit 'hacky'.

**Comment by sampsyo** [comment]
That's a little depressing. Thanks for figuring it out, @jackwilsdon.

Maybe one of us should volunteer to take over the PyPI listing from the author and fix the filename.

**Comment by owcz** [comment]
Per https://github.com/beetbox/beets/issues/2371, the documentation should be updated again to remove mention of this package altogether, as it's not working at all (are there no other means for importing iTunes art?)
