### ISSUE TITLE
Error writing tags to Ogg Vorbis files

### ISSUE THREAD

**Issue by JoeDat** [sampsyo/beets#1611]
I'm encountering an intermittent issue tagging Ogg Vorbis files. When writing changes, I occasionally see the following error:

Sending event: write
'\x00\x00\x1b\x83', expected 'OggS', at 0x1229a36

- Doesn't occur with all ogg vorbis files
- On one run, it may fail on a particular file.  On the next run, it succeeds.
- It occasionally re-reads and writes fine. Other times, it'll hang on the file indefinitely. 

I'm running the latest stable version on Ubuntu 14.04 LTS.  My files are stored on a Readynas Duo v2, accessed via cifs with full rw permissions.

**Comment by sampsyo** [comment]
Even though this is intermittent, can you isolate any files that make it happen more often? We'll run experiments to try to reproduce the issue.

Have you tried comparing against running locally on the same files? It's possible that the CIFS network filesystem is to blame rather than the files themselves.

**Comment by JoeDat** [comment]
It definitely performs much better with local files.  I've run it a few times with a local copy of some ogg files, and it's not an issue.  I can't really isolate any files that are worse than others.  Each run is oddly a different experience with the same set of files. 

Given that it's only when writing to files on the cifs share, if you still consider it worthy of your time to pursue, I'll send you a few files to experiment with.

**Comment by sampsyo** [comment]
Very strange. Yeah, I guess the files probably won't help.

It does sound like intermittent incorrect data being relayed over the network filesystem. Please do update us if there's a way we can reproduce the issue.

**Comment by JoeDat** [comment]
I'll the bug out for now, and maybe have it re-opened if more come of this.  It doesn't really feel like a beets problem at this point.  Thanks!!
