### ISSUE TITLE
bpd. warning: MPD 0.16 required

### ISSUE THREAD

**Issue by groundnuty** [sampsyo/beets#1615]
With soft. versions as bellow. MPD clients report an error as shown in the issue title.

beets version 1.3.14
plugins: bpd, chroma, discogs, duplicates, embedart, fromfilename, info

mpc  -h paas@127.0.0.1 -p 6600
warning: MPD 0.16 required
volume:100%   repeat: off   random: off   single: off   consume: off

ncmpcpp -h mo@127.0.0.1 -p 6600
ncmpcpp: MPD < 0.16.0 is not supported

**Comment by sampsyo** [comment]
Please see #800.
