### ISSUE TITLE
Feature Request: Skip to manual entering of MusicBrainz ID

### ISSUE THREAD

**Issue by lfm83** [sampsyo/beets#1616]
When importing really large albums (like a 56-CD box http://musicbrainz.org/release/a334fe44-27a5-43dd-b1da-369ddad5cde7), if the music is not pre-tagged in a perfect way, waiting for beets to check the usual number of non-matches against this huge directory can be very time-consuming (and at least on my computer, equivalent to infinitely long).
It would be very useful to have - assuming we're using the --flat option, which guarantees that it's just one album entity we're talking about - an option to skip Beets' guessing of the correct album and directly proceed to entering a MusicBrainz ID.
As far as I can see (but maybe I'm wrong here), this would be an almost trivial addition to the program, but it could be immensely helpful.

If a feature like this already exists and I just missed it, I apologize.

**Comment by sampsyo** [comment]
Yes, a very good idea -- please see #170.
