### ISSUE TITLE
Feature request: tag ignoring

### ISSUE THREAD

**Issue by arabar** [sampsyo/beets#1619]
There's one idea that came to my mind. As I am a little bit pedantic about music library it would be great to have some plugin that cleans all tags not necessary for user.
For example I want to have only `artist`, `album` and `title` tags in music. Plugin would remove everything what is not one of these tags.
There could be two ways to do that. First - tell plugin what tags it should remove, second - tell plugin what tags it should leave (and get rid of rest).
Config would be like:
```
ignore:
    do: year, genre
```
or:
```
ignore:
    dont: artist, album, year
```

I'm still new into Python but I will try to write something like this. However, first I have to ask it would hard to write plugin like that.

**Comment by sampsyo** [comment]
Hi! Have you tried the `zero` plugin? I think it does exactly what you want, using your blacklist idea.

**Comment by arabar** [comment]
Oh, sorry that I didn't check that. It's what I was looking for (in half :))
It clear everything what is written in config. Ideally it would clear everything other than few tags.
But I have to ask - is there any regex hack that may turn blacklist into whitelist?
Now I have to write about 20 fields in config, leaving only 5 necessary. It would be better to write these five as not-to-clear. Something like `!album` meaning - clear anything but album field.
Speaking of regex - why `*` and `.` doesn't work? There are many tags with `albumartist_` or `mb_` prefix I want to get rid of.

**Comment by sampsyo** [comment]
No, the plugin doesn't support any manner of pattern, regex or otherwise. It's just a list of fields.

If you're interested, would you mind opening a feature request ticket for adding something like `keep_fields` as a whitelist alternative to its current blacklist behavior?
