### ISSUE TITLE
Song Credits Information MusicBrainz

### ISSUE THREAD

**Issue by Almarsan** [sampsyo/beets#1622]
Hallo :)

I was wondering if there is any chance, maybe there is already a plugin or other function able to retrieve the complete information of a song from MusicBrainz. For example, here in this release of "Little Earthquakes" of Tori Amos, we have mandolin, drums, bass, percusion, ukulele, piano, background vocals, mixer etc etc etc:

http://musicbrainz.org/release/66b1a283-08e3-4096-b4b6-38bb8cba30ab

Of course not in all the releases there are these kind of fields.

I guess it would be only to show when you do a query in the beets database, because inside the ID3 metadata tags there would be only space for composer, lyricist and not so much. Maybe include this credits of the song in the comments would not be a bad idea.

Anyway, only to know if there is already something around this question, and how to proceed :)

**Comment by sampsyo** [comment]
Yes, we would love to get *all* the MusicBrainz data! Perhaps you can add your thoughts to the ticket that's tracking this idea, #1547.
