### ISSUE TITLE
Import Lyrics from Genius

### ISSUE THREAD

**Issue by mxmerz** [sampsyo/beets#1626]
Might it be possible to add http://genius.com as a source to the `lyrics` plugin? They have an API, documented at https://docs.genius.com/ and a vast collection of song lyrics (eg. for “Neongrüner Auswurf” by German group [Trailerpark](http://musicbrainz.org/artist/64d73a2c-714e-48d5-95ab-bc1f406bcc71): [MusicBrainz](http://musicbrainz.org/recording/b387088e-df44-4d6c-a2cb-f7a1dd3598d9), [RapGenius](http://genius.com/Trailerpark-neongruner-auswurf-lyrics)).

(It appears that [Musixmatch has the lyrics as well](https://www.musixmatch.com/lyrics/Trailerpark/Neongr%C3%BCner-Auswurf), but the plugin doesn’t seem to find them.)

**Comment by sampsyo** [comment]
Seems like a great source. I can't quite tell from the docs whether the API actually exposes lyric text, but it's worth exploring.

I vaguely recall someone on IRC talking about workin on getting lyrics from Genius. It might be worth searching around to see if they made any progress.

**Comment by mxmerz** [comment]
Wow that was fast! Thank you @sadatay and @sampsyo! Just tried it out, works like a charm!
