### ISSUE TITLE
Need help with :AttributeError: type object 'NoneQuery' has no attribute 'field'

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1634]
So, I'm trying to get the NoneQuery integrated in the query.
I added :
```
if key is not None and term == "":
        query_class=query.NoneQuery
        return key, term, query_class
```
 to querypqrse.py 
in 
```
def parse_query_part(part, query_classes={}, prefixes={},
                     default_class=query.SubstringQuery):
```
and add
```
if query_class is query.NoneQuery:
        return query_class(key.lower(), pattern)
```
in
```
def construct_query_part(model_cls, prefixes, query_part):
```
so that when I do
```
beet ls  lyrics:
```
I get
```
AndQuery([NoneQuery(u'lyrics', )]) <beets.dbcore.query.NullSort object at 0x7fdeff0d4710>
query AndQuery([NoneQuery(u'lyrics', )])
```
as q in return in
```
def parse_sorted_query(model_cls, parts, prefixes={}):
```
but then I always get this when I run
```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/ui/commands.py", line 972, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/ui/commands.py", line 967, in list_items
    for item in lib.items(query):
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/dbcore/db.py", line 533, in _get_objects
    if not self.query or self.query.match(obj):
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/dbcore/query.py", line 442, in match
    return all([q.match(item) for q in self.subqueries])
  File "/home/wintersj/Downloads/gitdownloads/beets/beets/dbcore/query.py", line 156, in match
    return not item[self.field]# or item[self.field] is None
AttributeError: type object 'NoneQuery' has no attribute 'field'
```
Has this somethimg to do with
```
@classmethod
    def match(self, item):
        try:
            return  item[self.field] is None
        except KeyError:
            return True
```
in the 
```
class NoneQuery(FieldQuery):
```
Is it because it is a classmethod with a reference to self ? (Does that make sense?)

If I hardcode it like
```
return not item["lyrics"] 
```
I get results,
Any help appreciated....

**Comment by sampsyo** [comment]
I concur! That method should not be decorated with `classmethod`. We apparently just never used `match` on that query type. Does revving the decorator help?

**Comment by jmwatte** [comment]
Great,
now that works. It takes it's time, like the regex. Now I can do things like
beet ls beatles lyrics:
or
beet ls -af'$rg_album_gain - $album' rg_album_gain:

and it will give me all my beatles that don't have lyrics
So it's like MISSING of getting the regex lyrics::^$
cool.
Now let's see hat we can do for NOT ...
things like
beet ls artist:"tom ^waits" 
beet ls artist:^"tom waits"^Beatles^"rolling stones"
beet ls artist:^"johan sebastian"Bach
beet ls "let it" ^be
beet ls -a beatles album:^help^"hard days night"
beet ls genre:^christmas

Any suggestions greatly welcome of course.
I'll play with it  for a few days.
Should I push this now Adrian or see what I can come up with the NOT?
well, the syntax is one thing ... programming another

**Comment by sampsyo** [comment]
Seems good! Could you please open a PR for the NoneQuery addition? It would be great to just double-check that we're not messing up any existing behavior.

Then, yes, onward to NOT!
