### ISSUE TITLE
fromfilename: Gather more information (medium, year, label, etc.) from filenames

### ISSUE THREAD

**Issue by ekjaker** [sampsyo/beets#1642]
Most of my albums that need importing are in a folder that has information that could be useful for better matching the album with the correct (MusicBrainz) release.

Example: "Darkstar - Need You_Squeeze My Lime [HDB010] - WEB_FLAC_Lossless"

Above example brings in the releasenumber (HDB010) and media (WEB). Very often, one can also find the year in the album folder name.

Could it be possible to check the folder name for some predefined words and if they are present, give the match with the same a higher rating? A bit like the 'preferred' option works for the importer, but now dynamic, based on the folder.

Easiest ones will probably be the medium: CD, WEB or VINYL.
YEAR could be useful as well.
LABEL and RELEASE would be great , but a lot more difficult to recognize, so maybe not possible to implement.
REMASTER, BONUS TRACKS, COUNTRY might also be useful.

thx for having a look!

Ekjaker

**Comment by pkess** [comment]
+1
I also think this would be a very useful extension

**Comment by sampsyo** [comment]
Good ideas!

Have you seen the `fromfilename` plugin? It does something similar, but mostly as a fallback in case files are missing their metadata altogether. That would be a good place to start, though, and extend it to harvest more data that's easy to identify.

**Comment by ekjaker** [comment]
```fromfilename``` indeed seems to have a large part already implemented of this idea. If I understand ```fromfilename``` correct, following things need to be changed/added to ```fromfilename``` to implement this: 
1. **create an option: use ```fromfilename``` as tagging aid.**This will effectively activate  ```fromfilename``` even if songtitles are present. So instead of using it as fallback, have it run before hitting MusicBrainz (and possibly Discogs). 
2. **add the foldername as source** for ```fromfilename``` to use. This can be added to ```fromfilename``` regardless of using it as aid for tagging with songtitles present or not. Even if there are no songtitles present (the original use of ```fromfilename```), the information of the path/foldername might be useful
3. **add fields** used by ```fromfilename``` that can be used for searching: media, year, label,...

But ideally, I think also extra changes might be necessary to the **importer**:
The importer would use the ```albumname``` and ```albumartist``` fields to poll MusicBrainz, and use the info from ```fromfilename``` as extra info for the rating process, and as such give better recommendations as candidates. e.g. without this, a cd version might be proposed as number one with a 95%, but due to this added info, the web release is rated higher and might even get a 97% because there was "WEB" in the foldername.

**Comment by sampsyo** [comment]
Yes, this seems like it's on the right track. Fortunately, the changes the importer itself should be minimal or nonexistent, since it already has the machinery to do weighting like that.

**Comment by ekjaker** [comment]
I guess #1554 is requesting something similar, only here the request is a bit larger: not just album/albumartist/year but also information like medium.

**Comment by sampsyo** [comment]
Good point. I'll merge this into #1554 by indicating that we should think about more fields.
