### ISSUE TITLE
UI optimization

### ISSUE THREAD

**Issue by ekjaker** [sampsyo/beets#1643]
### Introduction
To improve the UI, I'd like to propose some options/settings. These are focused on these general goals:
* customization: allowing different UI settings for different personal tastes and preferences
* good default settings
* a clear and easily viewable and understandable UI
* facilitating the tagging process

Putting everything in curses would be awesome of course, but also a big change. So below some suggestions for the current CLI-UI.

#### standardization of output:

One of the issues, in my opinion, with the UI, is that the information printed on screen necessary for making the necessary tagging decisions, is not consistent. This means that it is on different locations on the screen, with more or less lines printed, depending on the album. All this makes for a difficult experience, because the user's eyes have to search for the location of the info on the screen for each album.
* **limit 'random' output lines** coming in between the regular lines of info: next to the -v and -vv options maybe add extra levels such as -brief or -minimal that limit the output to the bare necessities, filtering out any extra errors/issues.
* **Applying the same logic in plugins**, for instance there is a print_ignored option in the copyartifacts plugin, put no option to have no output at all for this plugin, meaning the output of all copied log and cue files jumps in between the other lines. A '-q' or 'no output' option for plugins.
* having the option to put a '**clear screen**' command in front of extra new album. This puts our starting point on top of the screen every time, greatly improving the usability. Issue might be that we can't see previous info anymore by scrolling up, but this might be solved by extending the log file with more logging levels (error, warning, info, verbose,...)
* Most of the interaction is asked of the user for Medium recommendations, assuming one has a already reasonably tagged library. Make sure the initial question is always asked with the same layout, so **no display of possible corrections with the initial question** (for instance with multicd's) or titles. Add a more info action with that information.        
* **print the line with actions on 1 line**, not 2. so...

> [A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums, Enter search, enter Id, aBort?

instead of...

> [A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?

#### making the UI easier to read / navigate
Some minor tweaks might make the UI easier to read and to find the necessary information.

* First and foremost, and probably the most important suggestion: **highlight the first line of every album tagging output, being the path.** In effect, that's what states what is being processed, it is like the title of a chapter in a book, an therefor would greatly benefit from being easy to find. Now I often find myself in the situation of knowing what is being suggested but not what for. Not only that, the path of an album often contains information that can help identifying the correct release, such as the year and the media (web; cd, vinyl). The highlighting of the title can be done in many ways, or a combination of these, such as: indentation, larger font, bold, but mainly colors (see below). But I would definitely suggest to do this by default, even hardcode it if it is not easily feasible through options. 
* **More fields/items in the output that can be colored.** Now we only have these: text_success, text_warning, text_error, text_highlight, text_highlight_minor, action_default and action. But to really optimize the UI (and being able to customize) we need more options, such as: title/path (see above), candidate, default text color, tagging, URL,....
* **More and better use of indentation**: a basic one would be to indent everything relating to the processing of one album, except the title. It would really help knowing what output belongs to which album. Further indentations could be the candidates, all corrections, multi-cd,...
* **Add more hard returns / blank lines to differentiate what is on screen.** For instance add a blank line when going from more candidates back to the actions menu.
* **Change the default coloring.** Although very logic, the green yellow and  red color scheme is so harsh that they draw to much attention away from other important information. I'm still playing around with the options that are now available, and will do a recommendation later on. Of course, with more options / fields to color, this can be optimized even further (see above). Mind you, the goal is not turn the output in a Christmas tree, but to use coloring in such a way that it improves readability.

I'm sorry, this has become a lot more than expected, and quite a big read. It's basically just a bunch of ideas thrown together, probably some of them bad ones, difficult to implement, or just not feasible. But I also think there are some there that could greatly improve the experience and workflow of the tagging process that can be realized with limited effort (title/path highlighting). And others that might take more time to implement, but would certainly prove valuable (option for every plugin to limit output).

Unfortunately, I'm not a coder, but I have a huge backlog of albums that needs to be tagged and organized which can be used as testing ground for trials of above suggestions. So please let me know if I can help testing or in some other way.

Ekjaker

**Comment by sampsyo** [comment]
Thanks for all these ideas! It's great to start discussion on how things could improve. There's a related discussion on the importer interface at #1593—maybe we can try to summarize all the ideas in both of these threads? We could start a wiki page where we distill the actionable stuff and start getting into some details.

**Comment by ekjaker** [comment]
Just been going through #1593. Some really good ideas there as well. And some the same (such as the need to make the first line more easily identifiable.
Shame I started this new thread, it should have been added there. I'll summarize the ideas form both threads into a new text and add it there, So we can close this one and keep it central.

**Comment by sampsyo** [comment]
Sounds good; closing this issue.
