### ISSUE TITLE
How to move files when album-artist changes?

### ISSUE THREAD

**Issue by sym3tri** [sampsyo/beets#1644]
Hi, I'm a bit new to beets... loving it so far!

Maybe this is a bug, or maybe I'm doing something wrong. There's one thing I can figure out...

If I import 2 albums by the same artist and the album-artist tags are messed up on 1 of them, they'll both get imported into 2 separate album artist folders. 
i.e.
```
/full-album
    /Sun Ra
        /Astro Black
    /The Sun Ra Arkestra
       /Atlantis
```

In this case I want both artist and albumartist to be `Sun Ra`.

If I change the tags with `beet mod artist="Sun Ra" albumartist="Sun Ra"`, everything works as expected and is confirmable via `beet ls` or `beet info`, but when I try to `beet write` or `beet move` nothing happens. The incorrect directory is still used, the directory structure above is still used but what I actually want is:

```
/full-album
    /Sun Ra
        /Astro Black
        /Atlantis
```

Is there a way to get this to work as I want? Or is this a bug with `beet write`?
(beets version 1.3.14)

**Comment by sampsyo** [comment]
You'll want to use the album flag to modify the album-level metadata (`beet mod -a albumartist="Sun Ra"`).

This is indeed confusing; it's not just you! See also #561.

**Comment by sym3tri** [comment]
ah... thanks!
