### ISSUE TITLE
scrub: Restore album art in `auto` hook

### ISSUE THREAD

**Issue by Kolbasz12** [sampsyo/beets#1657]
recently finished importing all media into beets.  Upon completion I decided to check replaygain as it was not something I did during import.

did a basic query, beet replaygain year:2015

It does as expected, going through and adding replaygain to all files, but what was not expected is the fact that it clears the embeded album art.

I can look at a folder, change view so the art appears and as replaygain goes through the files, one by one the embedded art disappears.  

it is corrected by running beet embedart, but it seems like that shouldnt be needed.  Would beets be doing any other processing that would call to clear art?

**Comment by sampsyo** [comment]
As I mentioned on the mailing list, could you please do some investigation to see if anything else in your config could be causing this? For example, try turning off other plugins (e.g., zero) and checking whether the behavior still occurs.

We also need full bug report details (version, OS, etc. -- see the FAQ).

**Comment by Kolbasz12** [comment]
I do have zero plug-in enabled, but if that is executed,  wouldn't embedart
execute too like on my regular imports?

**Comment by sampsyo** [comment]
Yes, that would be the *expected* behavior—but this is a bug report, so we need to investigate the unexpected.

**Comment by Kolbasz12** [comment]
OK, running 1.3.16 in a docker container.

The previously assumed relation to the zero plugin is inaccurate.  I removed it from my configuration all together and the art is still being removed.  I uploaded the data to pastebin that shows the info call to a track showing the art is TRUE.  the version number, then the verbose replaygain and finally info where it shows art as FALSE, let me know if anything else is needed at this time.  

http://pastebin.com/EYMcYeE6

**Comment by sampsyo** [comment]
Great; thank you for investigating that. To complete the report, can you please check your other plugins in a similar way?

Please also post your configuration and other standard bug report details.

**Comment by Kolbasz12** [comment]
It appears the issue is with the scrub plugin.  As soon as I remove it, replaygain leave the art alone.

as soon as I put it back, the art is removed.  So, whether this is by design, I am not sure.

scrub:
    auto: yes

**Comment by sampsyo** [comment]
Thanks for narrowing it down! Strangely enough, I can't reproduce this: I tried enabling `scrub` with the `auto` option, and:

```
$ beet info performers | grep art:
               art: True
$ beet replaygain performers
replaygain: analyzing Air - 10 000 Hz Legend - Electronic Performers
$ beet info Performers | grep art:
               art: True
```

And even:

```
$ beet scrub performers
scrub: scrubbing: [...]
scrub: restoring art
$ beet info Performers | grep art:
               art: True
```

That is, `beet info` confirms that the art is still present, even when I invoke scrub explicitly.

I'm not sure what else to try. Please let me know if you have any additional information that can help me reproduce the problem.

**Comment by Kolbasz12** [comment]
OK, so I guess the only other thing I could offer is this, my configuration.

When I stripped it down completely, things broke and beets would not start.  So I figure it easiest to post as is, minus scrub...

I mean I guess it is entirely possible that some other plugin with scrub is the cause, but that seems odd.  If you are able to test with my config and it still works, shelf the issue as I can just as easily still run embed art after replay gain...  obviously not ideal, but it does the trick and works without making it a pain in the ass.

**Comment by sampsyo** [comment]
Yes, it does seem possible that another plugin could be the cause. I don't quite have the bandwidth to try adapting your complete config—could you please try disabling other plugins and see if turning one off fixes it?

And if an empty config causes your beets to crash, that is definitely a problem we should investigate!

**Comment by Kolbasz12** [comment]
what is an empty config and what is the bare minimum?

I stripped out everything, all plugins leaving only replaygain and info

I left my paths, import and replay gain sections

<code>
plugins: replaygain info
directory: /opt/downloads/music/beets
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: yes
per_disc_numbering: no
#color: yes
id3v23: yes
clutter: ["Thumbs.DB", ".DS_Store", "*.flac", "*.jpg", "*.ini", "*.jsp", "*.nfo", "*.m3u"]

paths:
####    default: $albumartist/$original_year - $album%aunique{}/$track - $title
# year part not working can still get 0000    default: $artist/%if{$original_year,$original_year,$year} - $albumartist - $album%aunique{}/$track - $title
    default: $albumartist/$year - $album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title ($year)
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track - $title 
ginal_year: yes

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
#    original_date: yes
    log: /config/beet.log

replaygain:
    auto: no
    overwrite: yes
    backend: command<\code>

**Comment by Kolbasz12** [comment]
how empty can my config be?  I thought I could strip it all the way down, but this is not the case...
the following fails to load:

plugins: replaygain info
directory: /opt/downloads/music/beets
library: /config/musiclibrary.blb

paths:
    default: $albumartist/$year - $album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title ($year)
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track - $title 

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

replaygain:
    auto: no
    overwrite: yes
    backend: command

**Comment by sampsyo** [comment]
What do you mean by "do not start"? Is there an error message?

A completely empty configuration should work.

**Comment by Kolbasz12** [comment]
der.  I found it.  I am using docker and there must be a call to the web plugin somewhere, somehow.

Once I looked at the docker container log, I saw it wanted the web plugin, I added it and now it starts and I can test replaygain...sorry for the confusion, it is my own dumb fault.

**Comment by Kolbasz12** [comment]
OK, that was fun.  Empty config with replaygain and info only leaves the art alone as you saw, so now I will try to add things back one at a time to see if I cannot pinpoint the issue...

**Comment by Kolbasz12** [comment]
OK, found the plugin that is clearing the art.  It is being cleared by the scrub plugin when running replaygain.  If I run a regular import the art is pulled and imported fine, but for replaygain, scrub is clearing album art.

scrub:
    auto: yes

**Comment by sampsyo** [comment]
OK, thanks for narrowing that down.

It looks like scrub's `auto` mode doesn't do anything to restore album art, unlike the explicit `beet scrub` command. In fact, you can even see this when doing a `beet modify`---the `replaygain` connection was a red herring.

**Comment by Kolbasz12** [comment]
So, for my sanity, does this mean that every time a command is executed all plugins in my config still run?

In the case of all my imports, the art was still there and I only started to use replaygain after I imported everything.  The point is that scrub didnt affect my normal imports even though it was present.

I am just trying to grasp how this only became an issue with replay gain and my only thought was regarding the order of and how all my plugins execute when running an import.

**Comment by sampsyo** [comment]
> So, for my sanity, does this mean that every time a command is executed all plugins in my config still run?

Not exactly. Not all plugins run all the time -- it depends on the plugin. The scrub plugin in particular runs *every time tags are written*. That's unlike most import-related plugins (say, `embedart`), which only run *during import*.

**Comment by Kolbasz12** [comment]
ah, that makes sense.  so in my case, when my imports ran, embedart, kept the art or added it as needed, picking up after scrub.  But, as noted, replaygain is not an import, so scrub is removing the art and embed art is not there to add it back.

So, now that that makes sense, is there any way to know which plugins run during which tasks and also, is there a specific order plugins execute?  meaning, would there be a case when scrub runs after embedart?  Is the order predefined or is there something that can control/change execution order?  such as the order in which they appear in the config?

**Comment by sampsyo** [comment]
> So, now that that makes sense, is there any way to know which plugins run during which tasks

The documentation is the canonical source for that. I note, however, that the scrub docs are wrong --- any interest in helping fix that, to make it clear that it runs on *every* write, including not limited to imports?

> is there a specific order plugins execute?  meaning, would there be a case when scrub runs after embedart?  Is the order predefined or is there something that can control/change execution order?  such as the order in which they appear in the config?

No, there is no specific order and it is not controllable. The idea is that it shouldn't matter: plugins should be written carefully so that they don't interfere with each other and so that order isn't important.

**Comment by Kolbasz12** [comment]
I can modify the doc, but how should it read?  I mean technically, if scrub is not observing its setting, then there is no way to make the document correct, without simply removing the configuration section.

auto: yes is supposed to set scrub to run only on import, but it is running still for all tasks and therefore, breaks when run with replay gain.

make sense?  scrub is currently broken, so there is no good way to edit the doc, other than noting that it will run every time beets runs.  Or am I missing something?

**Comment by sampsyo** [comment]
Yes, sorry for not being clear. Scrub *should* run on every write (I think?); the bug is just that it doesn't restore the album art when it does so. So we can just change the sentence in the docs about when the hook runs.

**Comment by reiv** [comment]
Is there a reason scrub should run on every write, rather than just imports? If its purpose is to remove extraneous tags then it would just be wasting time (and slowing everything down, too) running on every write since Beets itself does not add any untracked tags. Is there something I'm missing here?

**Comment by sampsyo** [comment]
It's definitely debatable! Here's the only difference: if someone has the importer configured not to write to files, then the `scrub` plugin can run when they eventually run `beet write` explicitly. But maybe they should just then take responsibility for running `beet scrub` too if they want that.

**Comment by reiv** [comment]
I think the speed advantages afforded by only hooking into `import` would outweigh the need to be a little more explicit when invoking the plugin manually, but that's just my $0.02.

**Comment by sampsyo** [comment]
Yeah, on further reflection I agree. Let's change the plugin to only run on import, like the docs say.

**Comment by Kolbasz12** [comment]
Since the document doesnt say exactly what it does, I need to ask.  What tags are actually scrubbed by scrub?  is it all of them?  Or just the ones not in musicbrainz or something?  also, if we are to discuss performance increases, I would be curious the time it takes to process something with scrub and without it.  I cannot imagine the performance increase being all that significant.  but regardless, clearly understanding what it is doing and how it is doing it and when is key for defining the plugin in the document.

**Comment by sampsyo** [comment]
It removes all the tags not supported by beets. That is, it deletes the tags, and then re-adds only what beets has in its database.

**Comment by Kolbasz12** [comment]
so will you just remove the configuration setting "auto" yess/no?  since that was supposed to control it running only on import?

meaning you will force it within the plugin to only run on import (unless called directly), removing the need for any other explicit configuration.

so, if I have a tag, bacon.  since it is not a beets tag, it would be cleared and not put back, while artist is  cleared but put back

**Comment by sampsyo** [comment]
No, we'll make the `auto` setting control running on import. So you can still turn it off if you only want to run explicitly.

> so, if I have a tag, bacon.  since it is not a beets tag, it would be cleared and not put back, while artist is  cleared but put back

Right.

**Comment by Kolbasz12** [comment]
So,  auto: yes in the config says run on import only.  If nothing is in the config, then it never runs unless called explicitly beet scrub?

**Comment by sampsyo** [comment]
The setting defaults to "yes." But if you turn it off, then you're right.

**Comment by sampsyo** [comment]
OK, I just pushed the following changes:

* The plugin actually runs on import, instead of on every write.
* When it does so, it uses the same logic as the explicit command to restore album art.

@Kolbasz12, can you check that the plugin now behaves how you expect it to?

**Comment by Kolbasz12** [comment]
Yes,  I will update and test.  And report.  It might be a few days,  but
once tested,  I will report. Thanks!

**Comment by Kolbasz12** [comment]
just ran replay gain in 1.3.17 and it did not clear the art. after successfully completing, art was still true

**Comment by sampsyo** [comment]
Thanks!
