### ISSUE TITLE
fedora COPR: python-munkres conflicts with munkres

### ISSUE THREAD

**Issue by azrdev** [sampsyo/beets#1658]
(Maybe there's a better place for this, then please redirect)

I enabled the [COPR](https://copr.fedoraproject.org/coprs/afreof/) for Fedora 22, to install beets and its dependencies. Upon running `dnf upgrade` which wants to pull `beets 1.3.13-2.fc22`, I get the following error:
```
Error: Transaction check error:
  file /usr/lib/python2.7/site-packages/munkres.pyc from install of python-munkres-1.0.7-1.fc22.noarch conflicts with file from package munkres-1.0.7-3.noarch
  file /usr/lib/python2.7/site-packages/munkres.pyo from install of python-munkres-1.0.7-1.fc22.noarch conflicts with file from package munkres-1.0.7-3.noarch

```

**Comment by sampsyo** [comment]
I'm not a Fedora packaging expert, but maybe someone else can help.

Is removing plain `munkres` an option? (It's not a beets dependency.)

**Comment by azrdev** [comment]
@sampsyo If beets doesn't need the `munkres` package, we should remove the dependency. If nothing else in the copr needs it, we should remove the package from the repo.

**Comment by sampsyo** [comment]
Sounds good. I'm not familiar with the COPR, but beets needs the Python library called `munkres`. Whichever package encapsulates that, that's the dependency we need to keep.

**Comment by azrdev** [comment]
`dnf repoquery --requires beets` tells me that beets currently (1.3.13) requires python-munkres *and* munkres.

`dnf repoquery --list python-munkres` tells me what files are contained in the package (which is not installed, due to the conflict with munkres):
```
/0001-Remove-hash-bang-from-munkres.py.patch
/munkres-1.0.7.tar.gz
/munkres.spec
/usr/lib/python2.7/site-packages/munkres-1.0.7-py2.7.egg-info
/usr/lib/python2.7/site-packages/munkres.py
/usr/lib/python2.7/site-packages/munkres.pyc
/usr/lib/python2.7/site-packages/munkres.pyo
/usr/share/licenses/munkres/LICENSE
```

munkres *is* installed, and contains:
```
rpm -ql munkres                                                                                                                         :(
/usr/lib/python2.7/site-packages/munkres-1.0.7-py2.7.egg-info
/usr/lib/python2.7/site-packages/munkres.py
/usr/lib/python2.7/site-packages/munkres.pyc
/usr/lib/python2.7/site-packages/munkres.pyo
/usr/share/licenses/munkres/LICENSE
```

So actually, it looks like python-munkres is just a duplicate of munkres.

**Comment by sampsyo** [comment]
So it seems! Strange. Yep, looks like the right course of action is to just delete one.

**Comment by azrdev** [comment]
@sampsyo do you intend to do so & fix this? Still, I cannot update.

**Comment by sampsyo** [comment]
No, I don't control the COPR (and, alas, I don't know who does).

**Comment by azrdev** [comment]
I did write him an email, now he replied that I should remove his COPR: It's not needed since beets is in [the official fedora repos](https://apps.fedoraproject.org/packages/beets) by now.

**Comment by sampsyo** [comment]
Excellent news! Thanks for looking into it.

**Comment by storrgie** [comment]
This is awesome!

**Comment by sampsyo** [comment]
Could one of you help me validate a new paragraph for the Getting Started guide? Something like this:

> On **Fedora** 22 or later, there is a [beets package][fedora] that you can install by typing `yum install beets`.

[fedora]: https://apps.fedoraproject.org/packages/beets

Is that right?

**Comment by storrgie** [comment]
Fedora changed over to DNF from yum in their release of 22. There appears to be three packages for beets:
```
beets.noarch : Music library manager and MusicBrainz tagger
beets-plugins.noarch : Plugins for beets
beets-doc.noarch : Documentation for beets
```

So the install procedure would be:
```
sudo dnf install beets beets-plugins beets-doc
```

I'm _so_ happy that I can snag this from my distro now.

**Comment by sampsyo** [comment]
Thanks! I put that command in the docs.
