### ISSUE TITLE
need some coding help for a plugin...

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1660]
This worked yesterday... :(
I have a plugin which today does not load anymore.
I did update my linux-box at night..
Anyway...
when I have this line

     # -*- coding: utf-8 -*-

at the top of my plugin letters.py file, beets says 

    error: unknown command 'letters'
 
when I remove it I get the 
  
    SyntaxError: Non-ASCII character '\xe2' in file /home/jmw/Documents/beets/beetsplug/letters.py   on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

this is the offending line

    PUNCT = "[!\"#$%&'‘()*+,-./:;?@[\\\\\\]_`{|}~]"

So, the question is how to solve it.
Any suggestions?
I got the latest build from github (28Okt2015_12:00)

Thx
jm

**Comment by amishb** [comment]
Hi there you could use, this for a more consistent and safer implementation. 

````import string
PUNCT = string.punctuation
````

**Comment by sampsyo** [comment]
If you want to use unicode characters like ‘ in the source, you'll need to declare that encoding for the Python file.

It's hard to see why the command isn't being recognized without more information—do you have the source available anywhere?
