### ISSUE TITLE
Reggae and dancehall in the genre tree

### ISSUE THREAD

**Issue by Freso** [sampsyo/beets#1661]
Right now we have `reggae` and `dance hall` under `caribbean and latin american`. This is fine. But then `ska` is its own "top" genre, with the child `dancehall`. I would say that `dance hall` should be a child of `dancehall` so it can get normalised, and I would either place everything under `caribbean and latin american` or make a `reggae` a top genre with `ska`, `dancehall`, `roots reggae`, `dub`, `ragga` etc. as children.

(We also have `ragga jungle` under `ska` and `ragga-jungle` under `oldschool jungle` (under `drum and bass`).)

**Comment by sampsyo** [comment]
Hmm, yes—that "dance hall" discrepancy is particularly glaring. A top-level reggae, separate from Caribbean/Latin, makes sense to me. (Although I'm only a casual reggae listener!)

100% approved if you'd like to make changes.

**Comment by Freso** [comment]
[AudioGalaxy's genre tree](https://web.archive.org/web/20100106112227/http://audiogalaxy.com/list/glossary.php) also had "reggae" as a top level genre, with dancehall et al being sub genres of that. One historical note is that ska actually is a precursor to reggae, not the other way around, but as Wikipedia [notes](https://en.wikipedia.org/wiki/Reggae) (emphasis mine):

> Reggae is a music genre that originated in Jamaica in the late 1960s. ***While sometimes used in a broad sense to refer to most types of popular Jamaican dance music***, the term reggae more properly denotes a particular music style that was strongly influenced by traditional mento and calypso music, as well as American jazz and rhythm and blues, especially the New Orleans R&B practiced by Fats Domino and Allen Toussaint, and evolved out of the earlier genres ska and rocksteady.

So I think it is probably okay to use "reggae" as the top genre, as long as we also add "roots reggae" as a way to include "real" reggae for the distinguished reggae listeners.

I'll try and get this changed tomorrow. Way too late to even be up right now to begin with…

**Comment by Freso** [comment]
Or not… Definitely bed time now!

**Comment by sampsyo** [comment]
Nice! Thanks, @Freso. :sleeping:
