### ISSUE TITLE
EmbedArt Plugin: remove_art_file doesn't seem to work

### ISSUE THREAD

**Issue by kooimens** [sampsyo/beets#1662]
I'm running beets version 1.15. The EmbedArt plugin isn't removing the art file from the file system. 
Logfile: http://pastebin.com/n10bbdpS
Config: http://pastebin.com/ztrjd16C

**Comment by Schweinepriester** [comment]
+1

Config: http://pastebin.com/bqTDtUg6
Exemplary Log (via `beet -vv import`): http://pastebin.com/DxGabj0C

**Comment by Kolbasz12** [comment]
have you tried with maxwidth commented out?  I know there was a time embedart was failing for me because I didnt install imagemagik or pils, not sure if it relates though

**Comment by sampsyo** [comment]
Thanks for the reports! It looks like @jackwilsdon only added the functionality for an explicit `beet embedart` command in #1591. Also covering the automatic import hook would be a good idea.

**Comment by Schweinepriester** [comment]
great, thanks! :)
