### ISSUE TITLE
"No matching release found" when given musicbrainz ID

### ISSUE THREAD

**Issue by howardjones** [sampsyo/beets#1665]
I've just had beets 1.3.15 tell me for a couple of different albums that "No matching release found for 14 tracks." even after being given a musicbrainz ID for a 14 track version that (as far as I can see) matches the files I have on disk. There's no error to suggest it's failing to pick up the data from musicbrainz...

For example:

	Finding tags for album "Various Artists - A Whiter Shade Of Doowop".
	Candidates:
	1. Various Artists - A Compilation of Warped Music (20.3%) (tracks, id, album, ...) (CD, 1998, US, SideOneDummy Records)
	2. Various Artists - A Treasury of Baroque (19.9%) (tracks, id, album, ...) (CD, 1995, CA, Excelsior)
	3. Various Artists - Shade 45: Sirius Bizness (19.1%) (tracks, id, album, ...) (CD, 2004, US, Shady Records)
	# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
	Enter search, enter Id, aBort? i
	Enter release ID: https://musicbrainz.org/release/85ed5bdc-3b70-4c24-8037-12d3ede64f20
	No matching release found for 25 tracks.
	For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
	[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort? i
	Enter release ID: 85ed5bdc-3b70-4c24-8037-12d3ede64f20
	No matching release found for 25 tracks.

Even though that musicbrainz ID is for a 25 track compilation (and actually the only release of that record), and my ripped copy is also 25 tracks, in the same order.

How can I fault-find this?

**Comment by sampsyo** [comment]
Strange. Can you try running in verbose mode?

**Comment by howardjones** [comment]
Aha... I think the 'required tag' line should be visible in non-verbose mode when you supply an MB ID like this.

	/volume1/Music/Cleaned14/SingleArtist/Desmond Dekker/Desmond Dekker - The Best of Desmond Dekker [0000] (18 items)
	No matching release found for 18 tracks.
	For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
	[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort? i
	Enter release ID: https://musicbrainz.org/release/063759fa-6eb3-4db7-8c18-d6a9ec222be3
	Tagging Desmond Dekker - The Best of Desmond Dekker
	Searching for album ID: https://musicbrainz.org/release/063759fa-6eb3-4db7-8c18-d6a9ec222be3
	Evaluating 1 candidates.
	Candidate: Desmond Dekker - The Best of Desmond Dekker
	Ignored. Missing required tag: year
	No matching release found for 18 tracks.
	For help, see: http://beets.readthedocs.org/en/latest/faq.html#nomatch
	[U]se as-is, as Tracks, Group albums, Skip, Enter search, enter Id, aBort?

**Comment by sampsyo** [comment]
Glad you found it. Sounds like a reasonable (although surprisingly non-trivial) additional log message if you're interested in adding it.
