### ISSUE TITLE
'scrub' doesn't scrub

### ISSUE THREAD

**Issue by simonbcn** [sampsyo/beets#1670]
beets git version
```
beets version 1.3.16
plugins: convert, embedart, fetchart, info, lastgenre, replaygain, scrub
```
I import a FLAC file with a comment tag but `scrub` doesn't delete it.

**Comment by sampsyo** [comment]
Scrub is not supposed to delete the command tag. Perhaps you meant to use the `zero` plugin?

**Comment by simonbcn** [comment]
https://beets.readthedocs.org/en/v1.3.15/plugins/scrub.html 
> **Scrub Plugin**
> The `scrub` plugin lets you remove extraneous metadata from files’ tags. If you’d prefer never to see crufty tags that come from other tools, the plugin can _**automatically remove all non-beets-tracked tags**_ whenever a file’s metadata is written to disk by removing the tag entirely before writing new data. 
...
> **Automatic Scrubbing**
> To automatically remove files’ tags before writing new ones, just enable the `scrub` plugin ...

By reading this I've understood that scrub would remove all tags before save the new ones.

**Comment by simonbcn** [comment]
With the `zero` plugin, it writes garbage to the comment field:
```
....
zero:
  fields: comments
  update_database: true
```
`beet info -i comment ...` doesn't show anything but:
```
$ mid3v2 -l Música/Avicii/Stories/01\ -\ Waiting\ for\ Love.mp3             
IDv2 tag info for Música/Avicii/Stories/01 - Waiting for Love.mp3 
COMM=iTunNORM=eng= 00002206 00002206 0000550E 0000550E 00000000 00000000 00008E88 00008E88 00000000 00000000
....
```

**Comment by sampsyo** [comment]
Ah, I understand how that could be unclear. The plugin removes everything beets doesn't support, but built-in beets fields (including comments) are preserved.

iTunNORM is an embodiment of the ReplayGain tag.

**Comment by m-urban** [comment]
Just stumbled over this issue and have to [cross-link to another comment](https://groups.google.com/d/msg/beets-users/0_mRoT9HIV8/zYsjo82mAgAJ) for future reference, as it contains the explanation for a problem that I was losing some hair over:

[@sampsyo said:](https://groups.google.com/d/msg/beets-users/0_mRoT9HIV8/zYsjo82mAgAJ)
> Are you referring to the **iTunNORM field**? That’s not considered a comment by beets; it’s an implementation of ReplayGain normalization. Unfortunately, **eyed3 labels it as a “comment” for some reason.**

This applies to eyeD3, evidently amaroK, too, and probably other players/tools as well…
