### ISSUE TITLE
WARNING: document isn't included in any toctree

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1688]
good evening...
I'm trying to submit a new plugin but I get this error from the building process:
WARNING: document isn't included in any toctree
Anyone know what I'm doing wrong?
grtz
jm

**Comment by sampsyo** [comment]
Good question. You need to add the name to the `.. toctree::` list in [`docs/plugins/index.rst`](https://github.com/sampsyo/beets/blob/master/docs/plugins/index.rst). That tells Sphinx to render your new documentation file.
