### ISSUE TITLE
User defined keyword tags in beets

### ISSUE THREAD

**Issue by igordertigor** [sampsyo/beets#1694]
I really like beets for music management. I also really like organizing things by keyword tags. This way, I can have a song marked as being nice as background for a romantic dinner and uplifting when starting my day by marking it for example with 'romantic|uplifting'. I would like to be able to filter my library by for example: beet ls usertag:uplifting   ->   only items that are tagged as uplifting
beet ls usertag:uplifting|romantic   ->  only items that are tagged as both uplifting AND romantic
And so on.
I started writing a plugin to do this. Naively, I thought I could just extend the MediaFile by adding a new field 'usertag' and then have functions for adding tags and removing them. For example, to add a tag, one would first get the id for the desired track (say we want to add a tag to the track with id=1) and then:
beet addtag 1 uplifting
Unfortunately extending the MediaFile didn't seem to work and I get the following backtrace:

Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.16', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/ingo/hacking/beets-usertag/beetsplug/usertag.py", line 9, in add_usertag
    if item['usertags'] is None:
  File "/usr/local/lib/python2.7/dist-packages/beets-1.3.16-py2.7.egg/beets/dbcore/db.py", line 230, in __getitem__
    raise KeyError(key)
KeyError: 'usertags'

Here is the content of the file usertag.py which contains the plugin up to now. What am I missing?

from beets.plugins import BeetsPlugin
from beets.ui import Subcommand
from beets import mediafile

def add_usertag(lib, opts, args):
    id = int(args[0])
    item = lib.get_item(id)
    if item['usertags'] is None:
        usertags = []
    else:
        usertags = item['usertags'].split('|')
    usertags.append(' '.join(args[1:]))
    item['usertags'] = '|'.join(usertags)
    item.write()
add_tag_command = Subcommand('addtag',
                             help='add user defined tag',
                             aliases=('at',))
add_tag_command.func = add_usertag

def remove_usertag(lib, opts, args):
    id = int(args[0])
    item = lib.get_item(id)
    print(item.keys)
    if item['usertags'] is None:
        return
    usertags = item['usertags'].split('|')
    idx = usertags.index(' '.join(args[1:]))
    usertags.pop(idx)
    item['usertags'] == '|'.join(usertags)
    item.write()
rm_tag_command = Subcommand('rmtag',
                            help='remove user defined tag',
                            aliases=('rt',))
rm_tag_command.func = remove_usertag

class UserTagsPlugin(BeetsPlugin):
    def __init__(self):
        super(UserTagsPlugin, self).__init__()
        self.import_stages = []
        tagfield = mediafile.MediaField(
            mediafile.MP3DescStorageStyle('usertags'),
            mediafile.MP4StorageStyle('usertags'),
            mediafile.StorageStyle('usertags'),
            mediafile.ASFStorageStyle('usertags'),
        )
        self.add_media_field('usertags', tagfield)

    def commands(self):
        return [add_tag_command, rm_tag_command]

**Comment by sampsyo** [comment]
If I were you, I'd avoid meddling with MediaFile altogether. As long as you're okay with your tags just living in the beets database and not on the files themselves, you can just use beets' flexible attributes.

The rest of your code looks at first glance like it should work as-is without defining a MediaField.

Neat plugin idea, BTW!

**Comment by igordertigor** [comment]
Cool, thanks. Here is the first version: https://github.com/igordertigor/beets-usertag

**Comment by sampsyo** [comment]
Awesome!
