### ISSUE TITLE
Tags not appearing in Windows Explorer

### ISSUE THREAD

**Issue by o-ze** [sampsyo/beets#1698]
I'm using beets on ubuntu 15.04 installed on an ext4 filesystem. 
My music library is located on an ntfs partition since I dual boot both operating systems. After tagging a few albums with beets, all tags are applied but a few albums don't show these tags in windows explorer although they are there whenever the file is opened using any media player.
I'm not sure if this is a windows bug or an issue from beets, but to overcome it I have to open these albums in another tagging utility in windows, select all the files and press save so that these tags can be viewed in the file manager again.

There is another issue regarding the library file, whenever I assign a path for the library file in the config,
I get this error
    "database file /var/music.blb could not be opened"

**Comment by sampsyo** [comment]
Please see the FAQ. http://docs.beets.io/en/v1.3.15/faq.html#not-change-my-id3-tags
