### ISSUE TITLE
Duplicates plugin errors out on merge attempt

### ISSUE THREAD

**Issue by m0nkey-br4in** [sampsyo/beets#1699]
First we find several duplicates:

    > beet dup -Fp Hazardous Dubs
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3
    
Then we try to merge them (and I hope beets does the right thing):

    > beet dup -M Hazardous Dubs
    Traceback (most recent call last):
      File "C:\tools\python2\Scripts\beet-script.py", line 9, in <module>
        load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
      File "C:\tools\python2\lib\site-packages\beets\ui\__init__.py", line 1163, in main
        _raw_main(args)
      File "C:\tools\python2\lib\site-packages\beets\ui\__init__.py", line 1153, in _raw_main
        subcommand.func(lib, suboptions, subargs)
      File "C:\tools\python2\lib\site-packages\beetsplug\duplicates.py", line 153, in _dup
        merge=merge):
      File "C:\tools\python2\lib\site-packages\beetsplug\duplicates.py", line 329, in _duplicates
        objs = self._merge(objs)
      File "C:\tools\python2\lib\site-packages\beetsplug\duplicates.py", line 316, in _merge
        objs = self._merge_items(objs)
      File "C:\tools\python2\lib\site-packages\beetsplug\duplicates.py", line 274, in _merge_items
        fields = [f for sublist in Item.get_fields() for f in sublist]
    AttributeError: type object 'Item' has no attribute 'get_fields'

   
I don't know what actually should have happened - I've not used beets to merge duplicates before

**Comment by sampsyo** [comment]
Thanks! I believe I've fixed this. Could you please try out the fix and see if it works?

**Comment by m0nkey-br4in** [comment]
OK, now the plugin doesn't crash. But it doesn't merge anything either:

    > beet dup -Fp Hazardous Dubs
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3

    > beet dup -M Hazardous Dubs
    6blocc - Hazardous Dubs EP Part 3 - Shyne Dub
    6blocc - Hazardous Dubs EP Part 3 - Murderer Dub
    6blocc - Hazardous Dubs EP Part 3 - Pundjabi Dub
    6blocc - Hazardous Dubs EP Part 3 - The Anthem
    6blocc - Hazardous Dubs EP Part 3 - Tribes
    6blocc - Hazardous Dubs EP Part 3 - No Freaks

And the duplicate tracks are still there:

    > beet dup -Fp Hazardous Dubs
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\02 Shyne Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\04 Murderer Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\03 Pundjabi Dub.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\05 The Anthem.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\06 Tribes.mp3
    G:\Music\Music\6blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3
    G:\Music\Music\6Blocc\Hazardous Dubs EP Part 3\01 No Freaks.mp3

Why does this happen and what was supposed to happen?

**Comment by sampsyo** [comment]
Good question. I'll need to defer to someone more familiar with the duplicates plugin. But if you're able to nail down exactly what's supposed to happen, then yes, please do file another bug.

**Comment by pedros** [comment]
Hi @sampsyo, I guess this would be me. Sorry about that @m0nkey-br4in. Would it be possible for you to send me your beets library file, so I can replicate what's happening?

**Comment by pedros** [comment]
@m0nkey-br4in: nevermind my earlier request. The plugin is, I think, doing what it should, although perhaps the documentation for the `merge` option is not clear. See the examples involving merging at https://beets.readthedocs.org/en/latest/plugins/duplicates.html.

Essentially, running `--merge` on tracks simply copies missing fields from one track to another. It needs to be paired with some other strategy for actually removing the duplicates. For example, `--delete`, or `--move`.
