### ISSUE TITLE
MetaSync cannot parse the library xml of iTunes 12.3

### ISSUE THREAD

**Issue by m0nkey-br4in** [sampsyo/beets#1700]
I use iTunes on Windows
(My username is edited out in the following snippets, but it contains only ASCII letters and numbers)
The plugin is configured like this:

    metasync:
        source: itunes
        itunes:
            library: C:\Users\<username>\Music\iTunes\iTunes Music Library.xml
            
The file is actually there (and when it's not there the error message is different). Then this happens:

    > beet -vvv metasync
    user configuration: C:\Users\<username>\AppData\Roaming\beets\config.yaml
    data directory: C:\Users\<username>\AppData\Roaming\beets
    plugin paths:
    Sending event: pluginload
    library database: C:\Users\<username>\AppData\Roaming\beets\library.db
    library directory: G:\Music\Music\beets
    Sending event: library_opened
    metasync: loading iTunes library from C:\Users\<username>\Music\iTunes\iTunes Music Library.xml
    metasync: Unknown metadata source 'itunes'
    metasync: No valid metadata sources found
    Sending event: cli_exit
    
10-15 seconds pass after the message `metasync: loading iTunes library...` and before the next one. And previous ones are printed almost immediately after each other. So I'm guessing it actually loads and tries to parse the file

**Comment by sampsyo** [comment]
Thanks for the report! I just pushed a fix.

**Comment by m0nkey-br4in** [comment]
Thanks! Now it reads the file

**Comment by christiankopac** [comment]
Sorry for writing on this issue but I'm on OSX running iTunes 12.3.1.23 and having exactly the same problem. The path and filename are correct.
``` 
metasync 
  source: itunes
  itunes:
    library: /Volumes/HDD/Music/iTunes/iTunes Library
```
and when running `beet -vvv metasync` I get exactly the same message:
```
user configuration: /Users/<username>/.config/beets/config.yaml
data directory: /Users/<username>/.config/beets
plugin paths: /usr/local/lib/python2.7/site-packages/beetsplug
Sending event: pluginload
artresizer: method is (2, (6, 9, 2))
library database: /Users/user/Music/Beets/database.db
library directory: /Volumes/HDD/Music/Library
Sending event: library_opened
metasync: loading iTunes library from /Volumes/HDD/Music/iTunes/iTunes Library.xml
metasync: Unknown metadata source 'itunes'
metasync: No valid metadata sources found
Sending event: cli_exit
``` 
after the `metasync: loading iTunes library from...` message it takes about 30 seconds and then it shows the metasync errors. Tested with `1.3.16`

**Comment by sampsyo** [comment]
Hi, @christiankopac—can you check that you have the latest source from git? 1.3.16 isn't released yet, so this fix is only available if you're on the latest master branch.

**Comment by christiankopac** [comment]
Pulled latest master branch. It is working now. Thanks @sampsyo !
