### ISSUE TITLE
Trying to import some asian named artists but wants to have them tagged/named with English names

### ISSUE THREAD

**Issue by daks** [sampsyo/beets#1705]
Hello,

I'm using beets 1.3.15 and trying to import this album https://musicbrainz.org/release-group/97454d04-fcba-4870-b186-6da35a205f6b. It has an asian name for artist and album but also an English alias for the artist.
As I prefer to have English names, after founding this issue #412 and this setting https://beets.readthedocs.org/en/v1.3.15/reference/config.html?highlight=language#languages, I edited my configuration to 

    import:
        language: en

When I import the album beets still name it with its original name

    beet import /tmp/잠비나이

    /tmp/잠비나이/차연 (9 items)
    Tagging:
        잠비나이 - 차연
    URL:
        http://musicbrainz.org/release/8f71eeee-f06b-4a81-bddd-d98369074a3a
     (Similarity: 100.0%) (CD, 2012, KR, GMC RECORDS)

What do I need to do to tag and name my files with English names?

Thanks.

(it seems that i don't have a korean font installed on my system)

**Comment by bearcatsandor** [comment]
I've been curious about this myself, since i'm a big fan of 菅野よう子 (Yoko Kanno) .I've got 300 of her tracks and if i actually import her directory i'll have many of her albums and tracks in Japanese. 

I can't query the album 連続テレビ小説「ごちそうさん」オリジナル・サウンドトラック ゴチソウノォト even if i could remember that or knew what it said with my US keyboard.

**Comment by sampsyo** [comment]
@daks: The setting name is `languages`, not `language`. :stuck_out_tongue_winking_eye:

@bearcatsandor: That transliterated release is is called a "pseudo-release". See #654 regarding absorbing pseudo-releases.

**Comment by daks** [comment]
@sampsyo oh... in fact, the search highlight on RTD made me thought it was 'language'.
