### ISSUE TITLE
mbsync: query with artist: fails

### ISSUE THREAD

**Issue by m-urban** [sampsyo/beets#1707]
I just discovered something strange, when I tried to perform an `mbsync` operation. I have a bunch of songs by the band A-Ha:

```
$ beet list artist:"A-Ha"
01 │ The Sun Always Shines On T.V.… │         A-Ha         │ The Sun Always Shines On T.V. │             Rock/Pop │ 2003
01 │ You Are The One [7" Remix]     │         A-Ha         │    You Are The One [Remix]    │                 Rock │ 1988
…
```

Now I ran
```
$ beet mbsync artist:"A-Ha"
```
which didn't do anything. However, running
```
$ beet mbsync album:"You are the one"
month: 00 -> 11
disc: 00 -> 01
day: 00 -> 21
disctotal: 00 -> 01
original_day: 00 -> 21
tracktotal: 00 -> 03
original_month: 00 -> 11
```
resulted in the displayed changes. It seems that for some reason, `mbsync` doesn't like the `artist:` -filter. This behavior can be reproduced with other artists, too.

**Comment by sampsyo** [comment]
The `mbsync` command uses an album-level query to find albums, so you'll need to use `albumartist:a-ha`. It doesn't match individual tracks unless they're singletons (i.e., not part of an album) because it wants to do whole albums at a time whenever possible.

**Comment by m-urban** [comment]
That makes a lot of sense, thanks for explaining. I do need to add that it's not overly intuitive, though. We should consider throwing an error message when run with a tracklevel filter and adjust the documentation.

**Comment by sampsyo** [comment]
Yeah, it's definitely confusing. See also #309, which would help automatically make `artist:` queries meaningful in album contexts.
