### ISSUE TITLE
Drop PIL (and use e.g. Pillow instead)

### ISSUE THREAD

**Issue by Schweinepriester** [sampsyo/beets#1709]
To cite [someone on stackoverflow](https://stackoverflow.com/questions/20060096/installing-pil-with-pip):

> Use Pillow instead, as PIL is basically dead. Pillow is a maintained fork of PIL.

Pillow could indeed be an alternative, maybe with none to minial effort:

- <https://pypi.python.org/pypi/Pillow/2.2.1> => <https://pypi.python.org/pypi/Pillow/3.0.0>
- <https://github.com/python-pillow/Pillow>

I know, we can do all(?) the image stuff with ImageMagick, but to install it on windows ~~is~~ was a pain, and since PIL is supported at the moment...
Background: I'm collecting the dependencies for all the beets plugins I use in an [requirements file](https://pip.pypa.io/en/stable/user_guide/#requirements-files) and PIL throws errors since its dead...

**Comment by sampsyo** [comment]
Yes, sounds good. IIRC, Pillow is a drop-in replacement—i.e., it gets imported under the name `PIL`—so we just need to update the docs and metadata. Any chance you could volunteer to update that?

**Comment by Schweinepriester** [comment]
Cool! Yes, i think i can do this.
Should I mention the original PIL in the docs or just replace PIL by Pillow?

Also, since you're mentioning metadata, i would have thought of <https://github.com/sampsyo/beets/search?l=rst&q=PIL&utf8=%E2%9C%93>, which files more?
Mention Pillow in python comments?

**Comment by sampsyo** [comment]
Yeah, let's just say Pillow; no need to also call out the original.

I was thinking of metadata in setup.py, but it looks like it's not listed there—so no problem.
