### ISSUE TITLE
Changing location of individual files in library

### ISSUE THREAD

**Issue by igordertigor** [sampsyo/beets#1726]
Occasionally songs imported into beets have incorrect paths (they were not on musicbrainz and incorrectly tagged, they were assigned different albums but belonged to one, ...). I have about two dozen files that I would like to manually move to the correct locations. Ideally I would correct the tags on these files and then do something like "beet update id:nnn" on each one of them. It seems though as if this is not implemented. Am I missing something or is this really a usecase that beets doesn't cover (yet)?

**Comment by sampsyo** [comment]
Correct; there's no (obvious) way to manually set the path of an item. This is because beets wants your filenames to be rule-based, so if anything changes in the future, the filenames can be kept consistent.

The usual thing to do if the tags are wrong is to fix them with `beet modify`. Then your path formats should fix the filenames automatically by moving things around. Would that work for your situation?

**Comment by igordertigor** [comment]
In fact, that was the first thing I tried, but it didn't work. Any good way to figure out why it didn't in my case?

**Comment by sampsyo** [comment]
Whether the `modify` command moves files does depend on whether your import configuration has `move` or `copy` enabled. To explicitly update filenames to match the new metadata, you can try the `beet move` command (possibly with the `--pretend` flag at first).

**Comment by igordertigor** [comment]
Well, that was what I figured yesterday as well, it just didn't go all the way. It's rather late here right now. I'll give it another try tomorrow and get back to you.

**Comment by igordertigor** [comment]
Hm, that doesn't seem to work. I changed my beets config to enable move and write during imports (both were disabled before, while copy was enabled). Would I have to re-import my whole library? I would rather want to avoid that and hack an explicit move command myself. See below for an example of what I did.

$ cat .config/beets/config.yaml
directory: ~/Music/
plugins: usertag
format_item: $id - $artist - $album - $title
asciify_paths: yes

per_disc_numbering: no
paths:
    default: $albumartist/$album%aunique{}/$track $artist - $title (${bpm}BPM)
    singleton: Various/Separate/$artist - $title (${bpm}BPM)
    comp: Various/$album%aunique{}/$track $artist - $title (${bpm}BPM)

import:
    write: yes
    move: yes
    incremental: yes
    languages: en, de
    group_albums: yes
$ beet ls id:484 -f '$path' /home/ingo/Music/Mymusic/Chicago/14 Chicago - Feel [w_horns] [Remastered Version] (2007) (80BPM).mp3
$ beet modify id:484 albumartist=Chicago album="The Best of Chicago, 40th Anniversary Edition" artist=Chicago title="Feel [w/horns] [Remastered Version] (2007)"
Modifying 1 items.
No changes to make.
$ beet ls id:484 -f '$albumartist / $album / $artist - $title'
Chicago / The Best of Chicago, 40th Anniversary Edition / Chicago - Feel [w/horns] [Remastered Version] (2007)
$ beet move --pretend id:484
Moving 1 item.
Source                                                                                                   Destination
/home/ingo/Music/Mymusic/Chicago/14 Chicago - Feel [w_horns] [Remastered Version] (2007) (80BPM).mp3  -> /home/ingo/Music/Mymusic/Chicago/14 Chicago - Feel [w_horns] [Remastered Version] (2007) (80BPM).mp3

**Comment by igordertigor** [comment]
Seems like there is a newline missing on the beet ls id:484 -f '$path' statement.

**Comment by sampsyo** [comment]
If you want to change an album-level field, you probably want to use `beet modify -a` to change an entire album.

**Comment by igordertigor** [comment]
Actually not. This is a single file that was incorrectly imported. I have a couple of those, but they are typically not album specific. It's really this one track that has been moved to an incorrect album. A similar thing also happens if autoscanned albums had differing artist labels (e.g. "Janet Jackson" for most of the tracks and then one "Janet Jackson feat. Q-Tip". It seems like something that wouldn't be difficult to hack into place, but I'd prefer a more beets-native solution.

**Comment by sampsyo** [comment]
I see---so is the goal here to disassociate the track from the album? If so, `beet modify album_id=` might do the trick.

**Comment by igordertigor** [comment]
Great that seems to do the trick. Do I have to delete the (now empty) album? I'm also not quite sure if I would call this "disassociate the track from the album" or rather "associate with another album" (the correct one). Does beetws allow tracks to have no associated album?

**Comment by sampsyo** [comment]
> Do I have to delete the (now empty) album?

Nope; it should disappear automatically.

> Does beetws allow tracks to have no associated album?

Yes. In beets, these are called "singletons." The docs should have more if you search for that term.
