### ISSUE TITLE
Your way for handling non-ASCII artists and tracks names?

### ISSUE THREAD

**Issue by lliseil** [sampsyo/beets#1729]
beets 1.3.16 on Arch linux here. Casual user slowly getting in, consolidating a music collection with ~1K Oriental pieces (mostly Arabic, Chinese and Japanese).
Beets works rather fine for Western artists :) But importing the non-Western tracks hardly works, probably because of a wrong set-up or methodology on my part.

* For non-Western Artists and Tracks with some reliable metadata, I barely get over (50%) but `As Tracks` often works. An issue is that beets takes the non-ASCII names, which I don't want (theoricaly fine but hinders further use on any system/device with a latin keyboard or poor unicode support). This keeps me from writing *any* ID tag or filename into the files --and so, to clean the "Latin" part of them. E.g:
````
David Bowie Ryuichi Sakamoto - Merry Christmas Mr. Lawrence (Furyo).mp3 (1 items)
Correcting tags from:
    David Bowie Ryuichi Sakamoto - 
To:
    坂本龍一 - Three         # unreadable (conjsole)/searchable
URL:
    <snip>.
(Similarity: 12.9%) (missing tracks, album, artist, tracks) (CD, 2013, Decca Records)
 * Merry Christmas Mr. Lawrence (Furio) (#0) (5:46) -> Merry Christmas Mr. Lawrence (#10) (5:35) (title, length)
````
* For those with broken metada, detection does not work even with tracks (unknown album and else lent by friends while travelling). And Accoustic fingerprinting is often errr, funny:
```
    $ beet import -alpW POP/VA\ Best\ Arabic\ Music\ Collection\ Of\ All\ Times/
    ...As Tracks
    POP/VA Best Arabic Music Collection Of All Times/SHATER..REMIX.mp3
    Tagging track: DJ Smash - Space Dust
    URL:
        http://musicbrainz.org/recording/dbe4628a-817e-4af8-8fe7-41e91e73c58d
    (Similarity: 100.0%)

    POP/VA Best Arabic Music Collection Of All Times/بنوتة.mp3
    Tagging track: Frank Sinatra - Nancy
    URL:
        http://musicbrainz.org/recording/419894fb-6dd6-4897-a269-7a09fcb45b67
    (Similarity: 100.0%)
```
So a Palestinian dabke (rythmed dance) is now known as Franck Sinatra's daughter name? hmmmmm pffffff :'-)

Is there a way to make Beets first deal with the *best matches*? Or shoulld we manually guess-and-move in a different location, eg. all files that could take profit of an Acoustic fingerprint or manual search?

I'd like to hear of your set-up and or strategy for handling non-ASCII art. E.g. in term of file structure before importing, config.yaml/overrides and plugins.

**Comment by sampsyo** [comment]
> An issue is that beets takes the non-ASCII names, which I don't want (theoricaly fine but hinders further use on any system/device with a latin keyboard or poor unicode support).

If you like ASCII-only filenames, you might like the `asciify_paths` config option.

> For those with broken metada, detection does not work even with tracks (unknown album and else lent by friends while travelling). And Accoustic fingerprinting is often errr, funny:

Yes, acoustic fingerprinting can have false positives.

> Is there a way to make Beets first deal with the best matches? Or shoulld we manually guess-and-move in a different location, eg. all files that could take profit of an Acoustic fingerprint or manual search?

I don't think I quite understand—do you want to deal with high-confidence matches first and then low-confidence matches in a separate pass? If so, then yes: configuring beets to move files after it imports them seems like a good strategy. Just make sure you have a backup in case it does something unexpected!

**Comment by lliseil** [comment]
> If you like ASCII-only filenames, you might like the `asciify_paths` config option.
Option does a great job, along with `language` for preferred aliases. Clearly I overlooked them before. An option to get the artists/art's names in both original and Latin languages would be optimal (like how IMDB/the TVDB do for movies and documentaries), but I bet it's not feasable with ID Tags?

>>Is there a way to make Beets first deal with the best matches?
> I don't think I quite understand—do you want to deal with high-confidence matches first 
`none_rec_action: skip` also helps the import workflow. This way I can import *best matches* first in the collection, and deal with the more « obscure » (from a Western PoV) later on (hundred of Skip/Enter search/as Tracks avoided). Rather than being stuck every two tracks and lacking the time to finish.

**Comment by sampsyo** [comment]
Yes, there's not currently a good way to keep multiple languages for the same music.

I'm glad things are working out OK!
