### ISSUE TITLE
Need info on queries

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1750]
So I search for this ...
```
jmw at huba in ~/Desktop 
$ beet ls album:symphony 15  artist:shostakovic -f'$artist-$title -$album'
Dmitri Shostakovich-I Allegretto -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-II Adagio - Largo - Adagio -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-III Allegretto -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-IV Adagio - Largo - Adagio - Allegretto -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-II quarter note =152 -Symphony No. 2 in B major, Op.14
```

As you can see, I also get a bit of Symphony nr 2 because of the 15 in the title. Because album only takes the first word and 15 goes into the general search(if I got that correct)
But if I do "symphony 15" of course I get nothing because it searches for the exact term, I guess..
So is there a way of saying : album should contain these words without it being so all or nothing?
The only way I can do it now is
```
$ beet ls album:15 album:symphony  artist:shostakovic -f'$artist-$title -$album'
Dmitri Shostakovich-I Allegretto -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-II Adagio - Largo - Adagio -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-III Allegretto -Symphony No. 15 in A major, Op. 141
Dmitri Shostakovich-IV Adagio - Largo - Adagio - Allegretto -Symphony No. 15 in A major, Op. 141
 ```

grtz
jmw

**Comment by sampsyo** [comment]
Good points here. The trick to understanding this is the shell. Beets doesn't see the quotes at all in a command like `beet ls album:'symphony 15'`. The shell interprets the quote and passes to beets the single string without quotes `album:symphony 15`, which is then matched as a substring query.

So there's little that beets can do about reinterpreting the quoted string or the whitespace. A query like `album:symphony album:15` is the way to go, at least for now. There's also the `fuzzy` plugin, which can help in cases like this.
