### ISSUE TITLE
"paths:" for multi-disc releases

### ISSUE THREAD

**Issue by Joshfindit** [sampsyo/beets#1751]
Multiple discs is a hot button topic, and I'm not attempting to bring a big solution, just something like this:

```
paths:
    default: $albumartist/$albumartist - $album [$year]%aunique{}/$track $artist - $title
    multidisc: $albumartist/$albumartist - $album [$year]%aunique{}/CD$disc.$track $artist - $title
```

By default, all single CDs have `$disc` set to 01, and I'd rather avoid having all single discs named the same as their multi-disc siblings.

**Comment by sampsyo** [comment]
You could use the `multidisc` inline definition from the FAQ: http://docs.beets.io/en/v1.3.15/faq.html#create-disc-n-directories-for-multi-disc-albums

Together with a path condition like `multidisc:1`.
