### ISSUE TITLE
paths: in config file does not appear to support the regexp syntax

### ISSUE THREAD

**Issue by thevorpalblade** [sampsyo/beets#1753]
I'm trying to use the following line in my config file
````bash
    paths:
        genre::[bB]ook: /usr/data/Audiobooks/
````

(Since not all audiobooks have the same genre, but this regexp matches most of 'em)
What I expect: Things tagged with genre:"Books and Spoken Word" or "Audiobooks" will be stored
in /usr/data/Audiobooks/
What happens: Nothing is stored in that directory, and no error is thrown.

Here is my config.yaml:
```bash
directory: /usr/data/Music_beets
library: /usr/data/musiclibrary.blb

plugins:
    inline bpd fromfilename mbsync replaygain convert duplicates missing chroma #discogs 

replaygain:
    backend: gstreamer

import:
    write: yes
    copy: yes
    autotag: yes
    resume: ask
    incremental: yes
#    none_rec_action: asis
#    quiet_fallback: asis
    log:    /home/matthew/.beets/import.log

per_disc_numbering: yes

paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0


paths:
    genre::[bB]ook: /usr/data/Audiobooks/
````

**Comment by sampsyo** [comment]
Looks like you have two `paths` sections. Can you combine them?

Also keep in mind that the criteria are tested in order—so ones listed earlier override ones listed later.

**Comment by thevorpalblade** [comment]
Ah, good catch, thanks!

I've modified my config file to have one ```path```` section, which is as follows:
```bash
paths: 
    genre::[bB]ook: /usr/data/Audiobooks/ 
    default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title 
    singleton: Non-Album/$artist/$title 
    comp: Compilations/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title 
 ```
Unfortunately, the behavior on ````beet move```` is the same, nothing in /usr/data/Audiobooks/

**Comment by sampsyo** [comment]
Cool; looks good so far. That should be valid YAML and such.

Next, can you verify that the music you're thinking of actually matches that query? That is:

    $ beet ls 'genre::[bB]ook'

Or even, if you prefer:

    $ beet move 'genre::[bB]ook'

**Comment by sampsyo** [comment]
Oh, and sorry for missing this before, but paths here can't be absolute. They're always relative to the same base directory (`directory`), even if they start with /. Any chance these are getting put in `/usr/data/Music_beets/usr/data/Audiobooks/`?

You might consider setting your `directory` to `/usr/data` and then prefixing your other paths with `Music_beets`.

**Comment by thevorpalblade** [comment]
Ah, that's definitely it. They are being put in usr/data/Music_beets/_/usr/data/Audiobooks/
The underscore surprised me, there is a variety of poorly-tagged gems in that directory!

Thanks, this bug report should probably be closed. Sorry for the trouble!
