### ISSUE TITLE
Beet queries very slow on custom fields

### ISSUE THREAD

**Issue by kooimens** [sampsyo/beets#1757]
I specified some custom album and item fields in my config:
http://pastebin.com/Ti3wHbi1

If I try `beet list -a added:2015-12-11` the albums added today are returned within a second. Try with `beet list -a added:2015-12-11 herkomst:discogs` it takes more than a minute. Same for queries on custom item level fields.

**Comment by sampsyo** [comment]
Yes, they're slow. There's no obvious fix—it's fundamental to the flexibility of flexible attributes that fixed attributes will be faster in SQLite—so we'll need to consider specific ideas for overhauling the schema.
