### ISSUE TITLE
Fetchart searches having problems

### ISSUE THREAD

**Issue by Nukien** [sampsyo/beets#1760]
I just noticed that cover art wasn't being found for some albums, so checked with **-v**

#### Google search uses old API that is no longer available

>fetchart: trying source google for album Yazz - The Natural Life
>fetchart: getting URL: https://ajax.googleapis.com/ajax/services/search/images?q=Yazz%2CThe+Natural+Life
&start=0&v=1.0
>fetchart: error scraping art page
>fetchart: Yazz - The Natural Life: no art found

So I tested some URLs directly ...
>https://ajax.googleapis.com/ajax/services/search/images?q=Yazz%2CThe+Natural+Life&start=0&v=1.0
>https://ajax.googleapis.com/ajax/services/search/images?q=The+Motels%2CAll+Four+One&start=0&v=1.0

and get an error page from google

>{"responseData": null, "responseDetails": "This API is no longer available.", "responseStatus": 403}

#### iTunes fails with **index out of range**

>fetchart: trying source itunes for album Yazz - The Natural Life
>fetchart: iTunes search failed: list index out of range

I'm assuming that this is when it can't find that particular cover, so this one is probably not an issue.  But it seems to happen a lot, and I thought iTunes had a good selection of cover art ...

**Comment by sampsyo** [comment]
Thanks for looking into both of these! It looks like we'll need to remove the Google source (there's no obvious alternative without a complete overhaul) and look more closely at the iTunes source.

**Comment by sampsyo** [comment]
OK, I removed the Google backend. I also improved the logging for the iTunes backend so it will emit a more sensible message like "no results for query X" rather than just the exception's text. In a couple of experiments, the backend was still able to find a couple of images for me, so I think it's still (basically) working.
