### ISSUE TITLE
Import of flac files with malformed tags fails

### ISSUE THREAD

**Issue by thevorpalblade** [sampsyo/beets#1761]
The following file is playable by (for example) VLC (which also has no problems reading the tags)
however, ````beet import```` on it fails with ````unreadable file: malformed.flac````
http://enterprise.drunkensailor.org:50000/malformed.flac

The flac file in question is indeed not a good file. It has lots (~270) of duplicate (and empty) ````STREAMINFO```` metadata blocks, and appears to have a mis-set ```last```` flag on the last one causing ````metaflac```` to interpret some of the audio data as tags.
Furthermore, ````flac -d```` fails (although after some source code digging I think the error it fails on is being triggered erroneously).

This very well may be a bug that should be handled upstream (or even just a wontfix). I'd done enough digging on it that I figured I may as well post something though.

**Comment by lazka** [comment]
Looks like the second last block should be a padding but has the streaminfo code set (followed by another padding, but that would be fine). mutagen fails as the sample rate in the wrong streaminfo block is zero which is not valid.

Do you know which application created the file?

**Comment by thevorpalblade** [comment]
No I don't. I obtained it from the Humble Music Bundle: ( http://blog.humblebundle.com/post/28062087940/introducing-the-humble-music-bundle ). The other albums from that bundle import fine.

**Comment by thevorpalblade** [comment]
What info should I collect?

**Comment by lazka** [comment]
See https://code.google.com/p/mutagen/issues/detail?id=117 and http://www.head-fi.org/t/606418/humble-bundle-other-indie-bundles-thread/15#post_8575167

**Comment by thevorpalblade** [comment]
If it's an issue just with those files (and it seems like it might be) I'll close the report. I was thinking it might have been indicative of some underlying non-robustness. Thanks!
