### ISSUE TITLE
Website has too much whitespace on the title

### ISSUE THREAD

**Issue by inexist3nce** [sampsyo/beets#1765]
*(Freso over at freenode told me to file an issue, so here I am)*

The title at http://beets.radbox.org/ has too much whitespace. The source for the html is located here: https://github.com/sampsyo/beets/blob/gh-pages/_layouts/main.html#L5
This is also probably the most unnecesary issue i've ever created.

**Comment by claman** [comment]
It probably has something to do with the rotating blurbs.

**Comment by inexist3nce** [comment]
I literally pointed out the issue and linked to it. Should I fork and make a pull request?

**Comment by sampsyo** [comment]
Please do open a pull request! Sadly, Liquid makes it really hard to control whitespace, so we'll probably need to resort to hacks.

It would also be helpful to know why this is a problem for you.

**Comment by inexist3nce** [comment]
I created the pull request -- it seems as if the whitespace could simply be removed from the html.

This is not an issue for me, nor for any browser. Its just that a friend's irc bot breaks and spams our channel with spaces and newlines.

**Comment by sampsyo** [comment]
Fixed in the PR.
