### ISSUE TITLE
Disambiguation not working with custom fields

### ISSUE THREAD

**Issue by Joshfindit** [sampsyo/beets#1775]
I have two copies of an album:

* Original CD ( 1995 )
* Remastered HDTracks release (2014 )

By default, I use `$year` in the folder name, so I thought a good workaround might be to create a `mastering` field and use it (`beets modify mastering=HDTracks album year:2014` which is very handy syntax).
It set successfully, but now I can't figure out how to disambiguate with it.

path: 

```
default: $albumartist/$albumartist - $album [$year]%aunique{,albumtype mastering year label catalognum albumdisambig}/%if{$multidisc,Disc $disc/}$track $artist - $title
```

`beet move` results in `album [1995]_no such field 'mastering'_`

**Comment by sampsyo** [comment]
Hmm; yes, I can see how this would get into trouble if only some albums have the field. Can you check whether this works if you add that field to *all* of the albums that need to be disambiguated? Some could have an empty string, or something like "none," but this might work as-is as long as there are no actual missing values.

**Comment by Joshfindit** [comment]
Ran `beet modify mastering=Unknown_mastering` (success), then ran `beets modify mastering=HDTracks album year:2014` again (success), then did `move album` and got the same thing: folders suffixed with `[2014]_no such field 'mastering'_`

**Comment by Joshfindit** [comment]
I did also notice that `beet info` doesn't show the `mastering` field. I double-checked to make sure they were set by doing `beet list mastering:HDTracks` and did get back the single album. Maybe the inability to see the custom field is related?

**Comment by sampsyo** [comment]
Cool; thanks for trying. I actually think the `info` issue is unrelated—it seems to be a problem with `%aunique` itself.

I just pushed a change that *might* fix this problem. Could you please clone the latest source and see if it works?

**Comment by Joshfindit** [comment]
I git-cloned, then did `./beet move album`, but it didn't make any changes.
Testing more thoroughly, it no longer did `[2014]_no such field 'mastering'_`, but did not use `mastering` as a disambiguation label.

For example, I did `%aunique{,albumtype mastering albumdisambig}`, and the files were moved to `album [1995] 133`

**Comment by sampsyo** [comment]
Hmm; that's too bad. This kind of thing can be hard to debug.

Can you show the metadata for all the albums involved? For example, something like:

    beet ls -af $path $albumartist $album $albumtype $mastering $albumdisambig

for the relevant albums.

**Comment by Joshfindit** [comment]
Info mildly redacted:

    /Volumes/Music/beets/Ani DiFr*nco/Ani DiFr*nco - Not a Pretty Girl [1995] [RBR007-D] Ani DiFr*nco Not a Pretty Girl album $mastering 
    /Volumes/Music/beets/Ani DiFr*nco/Ani DiFr*nco - Not a Pretty Girl [2014] [] Ani DiFr*nco Not a Pretty Girl album $mastering

**Comment by sampsyo** [comment]
Hmm; so they're both missing a value for `$mastering` according to this output?

**Comment by Joshfindit** [comment]
Correct, but when I run 

    beet list mastering:HDTracks

It returns the remastered album

**Comment by sampsyo** [comment]
Ah, the key is that `-a` flag—you'll need to modify (and inspect) albums, not individual tracks. Try `beet modify -a` and `beet list -a`.

**Comment by Joshfindit** [comment]
In retrospect, that's so obvious. I've been trying to disambiguate albums by using track metadata.
Set it with -a and it worked as expected. Lesson learned. :)

**Comment by sampsyo** [comment]
Wonderful! :sparkles:
