### ISSUE TITLE
change the path of the library without having to re-import ?

### ISSUE THREAD

**Issue by medyagh** [sampsyo/beets#1776]
I had mounted my external hard disk, now I wanna mount in a diffrent place or on a network, when I change the path of my library in the configuration I get thousands of messages that path is removed...for each single music. how can I change the path of my music library without having to re-import?

**Comment by sampsyo** [comment]
Please see this FAQ. http://beets.readthedocs.org/en/latest/faq.html#point-beets-at-a-new-music-directory
