### ISSUE TITLE
No debug output from logger in hooks

### ISSUE THREAD

**Issue by jackwilsdon** [sampsyo/beets#1781]
When using `log.debug` from a hook, there is no output produced. `log.error` works as expected, leading me to believe that the log level is changed when the hook is run.

Here's the code I am using to test this (named `logtest.py`):

```python
from __future__ import (division, absolute_import, print_function,
                        unicode_literals)

from beets.plugins import BeetsPlugin


class LogTestPlugin(BeetsPlugin):
    def __init__(self):
        super(HookPlugin, self).__init__()

        self._log.debug("Debug from init")
        self._log.error("Error from init")

        self.register_listener('cli_exit', self._hook_function)

    def _hook_function(self, *args, **kwargs):
        self._log.debug("Debug from hook function")
        self._log.error("Error from hook function")
```

And my configuration: 

```yaml
plugins: logtest
```

And here is the output from running `beet -v version`:

```
data directory: /Users/jack/.config/beets
plugin paths: 
Sending event: pluginload
logtest: Debug from init
logtest: Error from init
library database: /Users/jack/.config/beets/library.db
library directory: /Users/jack/Music
Sending event: library_opened
beets version 1.3.15
plugins: logtest
Sending event: cli_exit
logtest: Error from hook function
```

As you can see, the debug and error in `__init__` prints fine, however the debug does not print for the `_hook_function` method.

I am running this in a virtualenv after running `python setup.py install` (on Python 2.7.11) if that makes a difference.

**Comment by sampsyo** [comment]
Yes; I'm sorry this is not better documented! You should see the output if you use `-vv` (mnemonic: very verbose :smiley:). We added this second level of verbosity some time ago with exactly this meaning: `-v` will show you `debug` messages from beets core and explicitly-invoked plugin functions, but not from event listeners. The second level `-vv` shows all debug messages.

Maybe we should call this out more explicitly in the developer pages…

**Comment by jackwilsdon** [comment]
Aha, thanks! It would be nice to see it in `beet help`.

**Comment by sampsyo** [comment]
Done. I also added more details to the docs.
