### ISSUE TITLE
Editing MBID in import → enter Id is impossible

### ISSUE THREAD

**Issue by nagisa** [sampsyo/beets#1789]
When I have to enter the MBID of release (e.g. release has been just entered into MB) I’d prefer to just copy the URI of the release (something along the lines of `https://beta.musicbrainz.org/release/{mbid-here}`) and remove irrelevant parts. The entry, however, disallows editing line properly: you cannot move cursor in the line or edit the line in any useful manner.

**Comment by sampsyo** [comment]
You can just paste the entire URL. http://docs.beets.io/en/v1.3.16/faq.html#enter-a-musicbrainz-id
