### ISSUE TITLE
feature request, import from network file servers (like smaba)

### ISSUE THREAD

**Issue by medyagh** [sampsyo/beets#1791]
I can access my music library through a network file server but beets isn't happy with it.
```
~$ beet -v import smb://openelec13/disk19/Music/
user configuration: /home/medya/.config/beets/config.yaml
data directory: /home/medya/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/medya/beet_music_library.blb
library directory: /home/medya/.config/beets/smb:/openelec13/disk19/Music_New
Sending event: library_opened
error: no such file or directory: smb://openelec13/disk19/Music/
```

I use ubuntu 15.10,
and my file server is OpenElec through my wifi, I can access my openelec disk in file manager with read/write access.

**Comment by sampsyo** [comment]
You can do this if you actually mount the network filesystem (you might try googling for something like "mount samba share ubuntu"). I don't think we'll build in support for URL schemes like `smb://`—I think your file manager is getting it via GVfs. If that's the case, Wikipedia suggests that you might be able to find the mountpoint under `~/.gvfs`: https://en.wikipedia.org/wiki/GVfs
