### ISSUE TITLE
Re-importer messes up album relation for singletons

### ISSUE THREAD

**Issue by rassie** [sampsyo/beets#1801]
This one will be long to describe, I'm sorry about the length, I couldn't pinpoint it further. The main point is that the reimporter apparently assigns a wrong album to singletons. Here's how you can try it: 

Preparation:

1. Reset your `beets` database or make a new one for the test.
2. Create an empty directory for the test (e.g. `/tmp/beetstest`)
3. Select an artist from your collection with several albums and fill it with 
  - one complete album as a subdirectory
  - one track from that album as a singleton
  - one track each from two other albums by that same artist

So in my case I've got (I've taken something from Metallica):

```
$ ls -1 /tmp/beetstest/
01. Blackened.mp3
01. Fight Fire With Fire.mp3
01. Hit the Lights.mp3
(1983) Kill 'em All
```

Step 1: Import the singletons

1. `beet -v import -AWC /tmp/beetstest/*.mp3`
2. **Test**: `beet move -p 'path:/tmp/beetstest/'`
3. **Observe** that everything is as expected so far: the files would be renamed to their respective album and track, e.g. (I've patched the output, so it's slightly different than in the released `beets` version) 

```
$ beet move -p 'path:/tmp/beetstest/' 
Moving 3 items.
/tmp/beetstest/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/01. Fight Fire With Fire.mp3 ->
/music/Metallica/(1984) Ride the Lightning/01. Fight Fire With Fire.mp3

/tmp/beetstest/01. Blackened.mp3 ->
/music/Metallica/(1988) …and Justice for All/01. Blackened.mp3
```

Step 2: Import the album

1. `beet import -AWC /tmp/beetstest/\(1983\)\ Kill\ \'em\ All/`
2. **Test**: `beet move -p 'path:/tmp/beetstest/'`
3. **Observe** that everything is _still_ correct:

```
$ beet move -p 'path:/tmp/beetstest/' 
Moving 13 items.
/tmp/beetstest/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/(1983) Kill 'em All/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/(1983) Kill 'em All/02. The Four Horsemen.mp3 ->
/music/Metallica/(1983) Kill 'em All/02. The Four Horsemen.mp3

/tmp/beetstest/(1983) Kill 'em All/03. Motorbreath.mp3 ->
/music/Metallica/(1983) Kill 'em All/03. Motorbreath.mp3

/tmp/beetstest/(1983) Kill 'em All/04. Jump in the Fire.mp3 ->
/music/Metallica/(1983) Kill 'em All/04. Jump in the Fire.mp3

/tmp/beetstest/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3 ->
/music/Metallica/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3

/tmp/beetstest/(1983) Kill 'em All/06. Whiplash.mp3 ->
/music/Metallica/(1983) Kill 'em All/06. Whiplash.mp3

/tmp/beetstest/(1983) Kill 'em All/07. Phantom Lord.mp3 ->
/music/Metallica/(1983) Kill 'em All/07. Phantom Lord.mp3

/tmp/beetstest/(1983) Kill 'em All/08. No Remorse.mp3 ->
/music/Metallica/(1983) Kill 'em All/08. No Remorse.mp3

/tmp/beetstest/(1983) Kill 'em All/09. Seek & Destroy.mp3 ->
/music/Metallica/(1983) Kill 'em All/09. Seek & Destroy.mp3

/tmp/beetstest/(1983) Kill 'em All/10. Metal Militia.mp3 ->
/music/Metallica/(1983) Kill 'em All/10. Metal Militia.mp3

/tmp/beetstest/01. Fight Fire With Fire.mp3 ->
/music/Metallica/(1984) Ride the Lightning/01. Fight Fire With Fire.mp3

/tmp/beetstest/01. Blackened.mp3 ->
/music/Metallica/(1988) …and Justice for All/01. Blackened.mp3
```

Step 3. Run the re-importer on the singletons

1. `beet -v import -AWC /tmp/beetstest/*.mp3`
2. **Test**: `beet move -p 'path:/tmp/beetstest/'`
3. **Observe** that everything is _still_ correct:

```
$ beet move -p 'path:/tmp/beetstest/' 
Moving 13 items.
/tmp/beetstest/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/(1983) Kill 'em All/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/(1983) Kill 'em All/02. The Four Horsemen.mp3 ->
/music/Metallica/(1983) Kill 'em All/02. The Four Horsemen.mp3

/tmp/beetstest/(1983) Kill 'em All/03. Motorbreath.mp3 ->
/music/Metallica/(1983) Kill 'em All/03. Motorbreath.mp3

/tmp/beetstest/(1983) Kill 'em All/04. Jump in the Fire.mp3 ->
/music/Metallica/(1983) Kill 'em All/04. Jump in the Fire.mp3

/tmp/beetstest/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3 ->
/music/Metallica/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3

/tmp/beetstest/(1983) Kill 'em All/06. Whiplash.mp3 ->
/music/Metallica/(1983) Kill 'em All/06. Whiplash.mp3

/tmp/beetstest/(1983) Kill 'em All/07. Phantom Lord.mp3 ->
/music/Metallica/(1983) Kill 'em All/07. Phantom Lord.mp3

/tmp/beetstest/(1983) Kill 'em All/08. No Remorse.mp3 ->
/music/Metallica/(1983) Kill 'em All/08. No Remorse.mp3

/tmp/beetstest/(1983) Kill 'em All/09. Seek & Destroy.mp3 ->
/music/Metallica/(1983) Kill 'em All/09. Seek & Destroy.mp3

/tmp/beetstest/(1983) Kill 'em All/10. Metal Militia.mp3 ->
/music/Metallica/(1983) Kill 'em All/10. Metal Militia.mp3

/tmp/beetstest/01. Fight Fire With Fire.mp3 ->
/music/Metallica/(1984) Ride the Lightning/01. Fight Fire With Fire.mp3

/tmp/beetstest/01. Blackened.mp3 ->
/music/Metallica/(1988) …and Justice for All/01. Blackened.mp3
```

Step 4. Run the re-importer on the whole directory

1. `beet -v import -AWC /tmp/beetstest/`
2. **Test**: `beet move -p 'path:/tmp/beetstest/'`
3. **Observe** that the album title is wrong now for the singletons, however, their release years are correct:

```
$ beet move -p 'path:/tmp/beetstest/'
Moving 13 items.
/tmp/beetstest/(1983) Kill 'em All/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) Kill 'em All/01. Hit the Lights.mp3

/tmp/beetstest/01. Hit the Lights.mp3 ->
/music/Metallica/(1983) …and Justice for All/01. Hit the Lights.mp3

/tmp/beetstest/(1983) Kill 'em All/02. The Four Horsemen.mp3 ->
/music/Metallica/(1983) Kill 'em All/02. The Four Horsemen.mp3

/tmp/beetstest/(1983) Kill 'em All/03. Motorbreath.mp3 ->
/music/Metallica/(1983) Kill 'em All/03. Motorbreath.mp3

/tmp/beetstest/(1983) Kill 'em All/04. Jump in the Fire.mp3 ->
/music/Metallica/(1983) Kill 'em All/04. Jump in the Fire.mp3

/tmp/beetstest/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3 ->
/music/Metallica/(1983) Kill 'em All/05. (Anesthesia)-Pulling Teeth.mp3

/tmp/beetstest/(1983) Kill 'em All/06. Whiplash.mp3 ->
/music/Metallica/(1983) Kill 'em All/06. Whiplash.mp3

/tmp/beetstest/(1983) Kill 'em All/07. Phantom Lord.mp3 ->
/music/Metallica/(1983) Kill 'em All/07. Phantom Lord.mp3

/tmp/beetstest/(1983) Kill 'em All/08. No Remorse.mp3 ->
/music/Metallica/(1983) Kill 'em All/08. No Remorse.mp3

/tmp/beetstest/(1983) Kill 'em All/09. Seek & Destroy.mp3 ->
/music/Metallica/(1983) Kill 'em All/09. Seek & Destroy.mp3

/tmp/beetstest/(1983) Kill 'em All/10. Metal Militia.mp3 ->
/music/Metallica/(1983) Kill 'em All/10. Metal Militia.mp3

/tmp/beetstest/01. Fight Fire With Fire.mp3 ->
/music/Metallica/(1984) …and Justice for All/01. Fight Fire With Fire.mp3

/tmp/beetstest/01. Blackened.mp3 ->
/music/Metallica/(1988) …and Justice for All/01. Blackened.mp3
```

Hope you can make some sense out of it.

**Comment by sampsyo** [comment]
Hmm; this *might* be pretty easy to explain: the importer is running in album mode. That is, this:

> Step 3. Run the re-importer on the singletons
> 1. `beet -v import -AWC /tmp/beetstest/*.mp3`

is missing the `-s` flag, so beets is being instructed to tag each of those as a separate album.

And then, in this step:

> Step 4. Run the re-importer on the whole directory
> 1. `beet -v import -AWC /tmp/beetstest/`

the singletons are being re-imported *again*, still in album mode, along with the rest of your music. Because they all reside in a folder together, the album-mode importer groups them together into a single album.

**Comment by rassie** [comment]
OK, I see, the explanation about the album mode is solid. However: is it sensible? Depending on one's preferences, singletons might be located in the same directories as albums and it's not beyond reasonable to expect `beets` to figure it out -- otherwise you couldn't just import you previous collection in one command.

I'm going to read about album mode for a bit, before I'm ready to make proposals how to fix this :)

**Comment by rassie** [comment]
A quick inquiry: is there any downside to importing the collection in singleton mode?

**Comment by sampsyo** [comment]
Yeah, I definitely understand the desire to want a "re-import all my stuff, and keep its album-ness status instact" operation. How about using the `-L` (from-the-library) option to the import command? That is:

```sh
$ beet import -L  # step 1: re-import all albums
$ beet import -Ls  # step 2: the same for all singletons
```

**Comment by rassie** [comment]
This assumes that all singletons are already known to the library, which requires a proper import in advance. It seems that `--group-albums` might do what I need, tried that on the example above and it worked, now trying on a bigger collection.

Should we close this ticket, since it's working as documented, or maybe open a new one for discussion?

**Comment by sampsyo** [comment]
Yes, it does match stuff already in the library.

Is your goal to add new stuff that you've thrown into that folder (and basically do nothing with the files you've already imported)? If so, I feel like this has come up before... it's sort of the complement to `beet update`.

I'll close this one, but we can keep discussing here. If we get something concrete to work on, we can always open another ticket.

**Comment by rassie** [comment]
Basically I'm trying to migrate away from Picard which is per se not a collection manager but rather an advanced tagging and naming helper. A long time wish of mine has been to automate updating metadata and filenames of the whole collection (which is cumbersome in Picard to say the least), basically have something I could throw into monthly cron and forget about it.

(NB: I've even started extracting parts of Picard in the hope to write such a tool myself, but I've soon realized I'd need a proper database for more exquisite queries like "is this album missing tracks?", at which point I've stopped)

My music workflow is very simple: I tag new music with a tool of my choice (setting MusicBrainz IDs would be enough at this stage) and move the files somewhere underneath the main collection directory (`/music` in the example above). It's perfectly possible that I will still use Picard for that for the next couple of years. All I need from `beets` is to be that monthly cron tool.

That means that I don't need `beets` managing my collection from A to Z, but instead I need it to work with existing metadata (e.g. written with Picard). It _could_ also be the tool that updates the metadata, however, there is probably no reason why it should know where the metadata comes from. I can live with an extra step to "update the library", but that step should be completely repeatable, I could throw away the library and have it restored on the next run with virtually no data loss. Coming back to the original problem in this issue, there would be no distinction between singletons and albums in its current form, since it wouldn't be workable in automated setting at all.

I'm hope this has been a half-way coherent thought river, it's way past bedtime for me right now :)

**Comment by sampsyo** [comment]
I think I mostly understand. That gives me two ideas for alternative strategies:

- After you're done tagging with Picard, use `beet import` *with copying or moving enabled* to put the new music into your library directory. This keeps the database up to date incrementally with every new piece of music you add.
- Altenatively, keep your albums and singletons in separate directories under `/music` (or find another way to distinguish them). Then, to periodically refresh beets' database, just throw it away and reconstruct it with two `beet import -AWC` commands: one for singletons and one for albums.

Then, your cronjob can just run `beet mbsync`, if I understand correctly.
