### ISSUE TITLE
Typos in variables, methods & options

### ISSUE THREAD

**Issue by JesseWeinstein** [sampsyo/beets#1802]
Here are some typos I've noticed:

https://github.com/sampsyo/beets/blob/master/beets/ui/commands.py#L443 `def _summary_judment(rec):` should be `def _summary_judgment(rec):`

https://github.com/sampsyo/beets/blob/master/beetsplug/play.py#L44 ` 'warning_treshold': 100,` should be ` 'warning_threshold': 100,`

I'll submit a PR to fix them soon.

**Comment by sampsyo** [comment]
Agh; so embarrassing! Thanks!

**Comment by nathdwek** [comment]
Yup, I'm the one to blame for the second one. Just let me check if there are more instances of this particular spelling mistake.

**Comment by nathdwek** [comment]
You can base your PR on top of [fix-typos](/sampsyo/beets/tree/fix-typos)

**Comment by JesseWeinstein** [comment]
Yeah, I just saw it. I'd suggest we just support both config keys, for backwards compatibility.
