### ISSUE TITLE
Re-import should move album art (or remove the old album art file)

### ISSUE THREAD

**Issue by Smyds** [sampsyo/beets#314]
When updating the directory structure in the path format and reimporting the library to update the paths, the new directory contains the cover art, but the old directory still stays with the old cover art left inside.

**Comment by Kernald** [comment]
I have the same issue. My use-case wouldn't be covered by `beet move`, however: a release saw its release date corrected on MusicBrainz, so became `2012 - something` instead of `2011 - something`.

**Comment by sampsyo** [comment]
@Kernald For that purpose, you may want to look at the `mbsync` plugin.
