### ISSUE TITLE
Change permissions on moved files before writing

### ISSUE THREAD

**Issue by dimsuz** [sampsyo/beets#343]
I was trying to import my JC Superstar album. 
beets offered my a substitution of single quotes:
![screenshot from 2013-07-13 20 21 03](https://f.cloud.github.com/assets/42920/793023/5927e226-ebd8-11e2-8787-bd92b982f072.png)

I accepted and got this:
```Error: Permission denied while writing
 'Music/Andrew Lloyd Webber/Jesus Christ Superstar/16 Peter\xe2\x80\x99s Denial.mp3'```

The file itself was copied to the destination is not corrupt and playable:
```
ls ~/Music/Andrew\ Lloyd\ Webber/Jesus\ Christ\ Superstar/ -lh
total 2.1M
-r--r--r-- 1 dimka dimka 2.1M Nov  3  2011 16 Peter’s Denial.mp3
```

Notice that `\xe2\x80\x99` in file name.
Googling this string pops up quite some questions on StackOverflow regarding python and single quote unicode encoding.
I know very little of python programming, so hoping some expert will find an easy fix.

My OS is Arch Linux:
Linux dimsuzhost 3.9.9-1-ARCH #1 SMP PREEMPT Wed Jul 3 22:45:16 CEST 2013 x86_64 GNU/Linux
Python 2.7.5
FS is ext4

**Comment by jrobeson** [comment]
does the new permissions plugin solve this now? or not?

**Comment by sampsyo** [comment]
Good point, @jrobeson!
