### ISSUE TITLE
Packaging for fedora

### ISSUE THREAD

**Issue by Onuonga** [sampsyo/beets#375]
Hi,
I can take up packaging this for fedora. I do not think srpm is a good practice as during updates it is not included easily. It becomes more tedious to push updates to users.
if it is desired I can take this up as making RPM is pretty easy.
kindly advice.

**Comment by Onuonga** [comment]
Hmm. Sounds good. ok will work on it .

**Comment by afreof** [comment]
Hi

@Johnny: Thank you for the hint about copr. I'm working on that. (Setup a public web server...)
@Frankie: Would be great if you could test the scripts and spec files in my git repo and give me feedback. 

On Monday 05 January 2015 05.29:10 Frankie Onuonga wrote:
> Hmm. Sounds good. ok will work on it . 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sampsyo/beets/issues/375#issuecomment-68707291



--------------------
Adrian Freihofer
Gschwaderweg 29
8610 Uster
043 497 84 01

**Comment by Onuonga** [comment]
Sure thing @afreof

**Comment by afreof** [comment]
The packages are now provided by copr. At least building the packages and run beets from command line is now possible. For installation instructions please go to https://github.com/afreof/fedora-beets.

**Comment by sampsyo** [comment]
Cool! Is it time to add these instructions to the beets docs? If so, would someone mind opening a small PR that adds the right stuff?

**Comment by afreof** [comment]
Currently not all features of beets are tested. One issue which I already found is the web service. It basically works but a click on the play button triggers an exception on the server:
```
Exception happened during processing of request from ('192.168.99.175', 38346)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 595, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 653, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
I guess it is related to missing java script files. The Debian beets package depends on libjs-backbone, libjs-jquery and libjs-underscore. Currently none of them is available on my system. Does beets need them for playing audio files on the web page?

**Comment by sampsyo** [comment]
That traceback is benign; you can safely ignore it.

**Comment by afreof** [comment]
For Fedora 21 x86_64, beets is packaged. It's the right time to update the documentation now. I propose to update the documentation by the following installation steps:

yum install dnf dnf-plugins-core
dnf copr enable afreof/beets
yum update
yum install beets

With Fedora 22 (may 2015) the procedure will be simplified, since dnf is targeted to become the default package manager.

**Comment by sampsyo** [comment]
Thank you! I've added some instructions to the getting-started guide. Can you let me know if anything looks wrong?

**Comment by afreof** [comment]
Sorry the delay. Yes, this is fine. Thank you.

**Comment by sampsyo** [comment]
Thank *you* for your expertise, @afreof!

**Comment by afreof** [comment]
beets is now (Fedora 22 onwards) in the official Fedora Repository. The copr repository is obsolete.
