### ISSUE TITLE
Granular command-line logging specification.

### ISSUE THREAD

**Issue by dokterbob** [sampsyo/beets#430]
Allow for granular specification of verbosity level with the `-v` command line options. I've implemented something similar [here](https://github.com/dokterbob/spotify2piratebay/blob/master/spotify2piratebay/runner.py#L304). This allows `-v DEBUG`, `-v WARNING` and the likes.

In addiontion, I would also like to maintain legacy behaviour where `-v` simply increases the log level one from the default.

This is an attempt to split #327 up into several byte-sized features which can be concretely implemented.

**Comment by sampsyo** [comment]
We now have -vv thanks to #1320.

**Comment by dokterbob** [comment]
\o/

Many thanks you guys!
