### ISSUE TITLE
Optionally use faster string distance functions

### ISSUE THREAD

**Issue by sampsyo** [sampsyo/beets#646]
I set up a [benchmark for album matching](https://github.com/sampsyo/beets/blob/master/beetsplug/bench.py#L60) to investigate #609 and found that (after fixing some obvious problems) well over half of the matching time can be spent on edit distance calculation. There are some reasonable-looking C implementations of Levenshtein available:

* [editdistance](https://pypi.python.org/pypi/editdistance)
* [python-Levenshtein](https://pypi.python.org/pypi/python-Levenshtein)
* [jellyfish](https://pypi.python.org/pypi/jellyfish)

We should consider letting beets use these *optionally* if they're installed (and fall back to our simple Python implementation if they're not).

**Comment by jrobeson** [comment]
this could be closed now right? since jellyfish is now required.

**Comment by duailibe** [comment]
@jrobeson indeed. Thanks!
