### ISSUE TITLE
Option to remove external album art after embedding

### ISSUE THREAD

**Issue by RevenantOne** [sampsyo/beets#733]
I find the fetchart and embedart plugins really useful but once the album art has been embded I don't really have a use for the external cover.jpg file any more.

I'm unable to find any command to delete them or remove them from the library (please correct me if I'm wrong), so if I manually delete them beets will complain that they there are files missing for certain queries.

**Comment by Schweinepriester** [comment]
was about to open another issue for this, but here is just a push :)

i think this should be an option for `embedart`, something like: `removeArtFile: yes|no`

> Sure, an automatic hook to remove download art files would go in fetchart. But it seems like people might want to remove album art even if they're not embedding it (explicitly).

is there a use case where one would fetch albumart but then remove it?

if not, embedart it is :)

**Comment by Schweinepriester** [comment]
I just wrote a tiny (buggy? bad?) plugin, which fits for me so far: <https://github.com/Schweinepriester/beets-removeartfile>

Still hoping for a more sophisticated and better supported solution, though.
