### ISSUE TITLE
Boolean "not" operator in queries

### ISSUE THREAD

**Issue by kript** [sampsyo/beets#819]
I'd like to be able to do reverse matching regex in beets so I can create smart playlists with one or more specific exclusions, i.e.;

beet list ^(?!undesirable)$

or

smartplaylist:
    playlists:
        - name: notaudiobooks.m3u
          query: 'genre:^(?!(audiobook)|(spoken))$'

**Comment by Profpatsch** [comment]
Syntax ideas:

Example: I want to find all album by artist Evanescence, but not their album “Evanescence”:

    beet list "artist:evanescence -album:evanescence"

or maybe

    beet list "artist:evanescence not album:evanescence"

**Comment by sampsyo** [comment]
Added in #1728.
