### ISSUE TITLE
Normalise logging usage across the codebase

### ISSUE THREAD

**Issue by brunal** [sampsyo/beets#916]
Following this conversation : http://comments.gmane.org/gmane.comp.audio.beets.user/260
Most of the time logging in the codebase is eager. This should be fixed to use lazy logging.
Moreover @sampsyo expressed preference for the newer syntax (`"".format()`).
It's also the opportunity to export a pre-configured logger (e.g. `from beets.logging import log`)

1. Is it worth it?
2. Is there room for other improvements?

**Comment by sampsyo** [comment]
Done as of #1208.
